Feature: Aanvraagsoort TNOV en Opstellen verzoekschrift = Ja
Dit is een feature voor het testen van de functionaliteit voor Informeren Zorgaanbieder

  Background: https://ciz.atlassian.net/browse/ZSD-36408 Berekening 4: Juridische status afgegeven met correctie-1
    # Bij het uitvoeren van WzD-beoordelen voor aanvraagsoort = TNOV geldt dat altijd het veld 'Opstellen Verzoekschrift' + keuzes Ja en Nee enabled moet worden getoond. De schermen Informeren Rechtbank en Informeren Aanvrager worden getoond   
    # Het scenario dat Opstellen verzoekschrift = Nee en Aanvraagsoort = WzdRM moet leiden tot tot schermen Informeren Aanvrager en Zorgaanbieder 
    # wordt getest in test ZSD_26447_Subtask_ZSD-36479_Local_action_Correctie_vastleggen_uitspraak-TNOV
  #Juridische status afgegeven met correctie-1

  @Correctie_uitspraak_scenarios-36479_Local_action_Correctie_vastleggen_uitspraak-TNOV
  Scenario Outline:
    # Given We testen scenario: "<Scenario>"
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "12-01-2022" voor index: "2" op tab: "1"
    When Fill in veld value: "roepnaam-baby-Test" voor index: "3" op tab: "1"
    When Fill in veld value: "baby-Test" voor index: "4" op tab: "1"
    When Fill in veld value: "van den" voor index: "5" op tab: "1"
    When Fill in veld value: "Baby test" voor index: "6" op tab: "1"
    When Fill in veld value: "BT" voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "<wettelijkeRelatie>" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "<aanvraagdatum>" voor index: "1" op tab: "1"
    Then Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Aanvrager onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgaanbieder onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgverantwoordelijke onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Wzd-functionaris onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Tweede belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    When Druk op zaak: "WZD-TNOV" link voor: "<Scenario>" op tab: "1"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    ##### Controleren Administratieve volledigheid #######
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziektebiografie #####
    Then Druk op type: "button" met naam: "Datum toevoegen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziekte/Aandoening #####
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Wzd beoordeling - schermonderdeel Diagnose, ernstig nadeel en reikweidte #####
    When Zoeken en invullen value: "Afschrift van de beslissing tot opname van de zorgverantwoordelijke" voor index: "1" indexpijl: "0" op tab: "2"
    Then Druk op type: "checkbox" met naam: "Het ernstig nadeel niet langer buiten een geregistreerde accommodatie kan worden afgewend." met index: "0" op tab: "2"
    When Iframe fill in value: "Toelichting" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Opstellen Verzoekschrift #####
    When Fill in veld value: "09-12-2024" voor index: "2" op tab: "2"
    When Fill in textvak value: "Verzoekschrift" voor index: "2" op tab: "2"
    When Fill in veld value: "09-12-2024" voor index: "4" op tab: "2"
    When Fill in textvak value: "Verzoekschrift" voor index: "3" op tab: "2"
    Then Druk op type: "button" met naam: "Voltooien" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Informeren Rechtbank #####
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    ##### Informeren Aanvrager #####
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Postal" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Status geupdate naar: "Wacht op rechtbank" voor index: "0" op tab: "2"
    # Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Wachten op rechtbank #####
    Then Druk op local action "Vastleggen uitspraak" op tab "2"
    ##### Vastleggen uitspraak #####
    When Fill in veld value: "<datum_uitspraak>" voor index: "0" op tab: "2"
    Then Select option by value: "<uitspraak>" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Fully awarded" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Custody" met index: "0" op tab: "2"
    When Fill in veld value: "<startDatum>" voor index: "1" op tab: "2"
    When Fill in veld value: "<einddatum>" voor index: "2" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op local action "Correctie vastleggen uits..." op tab "2"
    When Select option by value: "<reden_correctiebesluit>" voor index: "0" op tab: "2"
    When Fill in block value: "Dit is een toelichting voor correctie vastleggen uitspraak" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op local action "Vernieuwen" op tab "2"
    When Gerelateerde Dossiers: "Alles weergeven" voor index: "0" op tab: "2"
    When Gerelateerde Dossiers: "WZD-TNOV" voor index: "0" op tab: "2"
    ###Gerelateerde dossiers#####
    ###WLZWZD-TNOV-Wachten op rechtbank####
    #### druk op ga button####
    #### ga verder met data van sheet####
    #When Druk op sidebar optie "Bijbehorende zaken" op tab "2"
    #When Druk op zaak: "WLZWZD-OM" link voor: "<Scenario>" op tab: "2"
    #Then Initieer nieuwe pagina op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    When Fill in veld value: "<correctie_datum_uitspraak>" voor index: "1" op tab: "2"
    Then Select option by value: "<uitspraak_correctie>" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Fully awarded" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Custody" met index: "0" op tab: "2"
    When Fill in veld value: "<correctie_startdatum>" voor index: "2" op tab: "2"
    When Fill in veld value: "<correctie_einddatum>" voor index: "3" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    ##### Controle op eindstatus - End2End flow #####
    Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "2"
    Then Sla zaak met naam "WZD-TNOV" voor: "<Scenario>" in filenaam: "Correctie_uitspraak_scenarios-36479_Local_action_Correctie_vastleggen_uitspraak-TNOV" op tab: "2"

    Examples:
      | Scenario                                                                       | env | bsn       | Aanvraagwijze | Aanvraagdatum | Aanvraagsoort | wettelijkeRelatie | reden_correctiebesluit | aanvraagdatum | uitspraak           | datum_uitspraak | einddatum | startDatum | correctie_datum_uitspraak | uitspraak_correctie | correctie_startdatum | correctie_einddatum |
      | ZSD_26447_Subtask_ZSD-36479_Local_action_Correctie_vastleggen_uitspraak-TNOV-1 | WLZ | 022010828 | Written       |    25-12-2023 | WzdTNOV       | Curator           | IncorrectDate          |      1-2-2025 | Legal status issued |       10-2-2025 |  7-7-2025 |  11-3-2025 |                  6-2-2025 | Legal status issued |             6-2-2025 |            6-6-2025 |
      | ZSD_26447_Subtask_ZSD-36479_Local_action_Correctie_vastleggen_uitspraak-TNOV-2 | WLZ | 010515756 | Written       |    25-12-2023 | WzdTNOV       | Curator           | RecoveryOrder          |      1-2-2025 | Legal status issued |       10-2-2025 |  7-7-2025 |  11-3-2025 |                  6-2-2025 | Legal status issued |             6-2-2025 |            6-6-2025 |
      | ZSD_26447_Subtask_ZSD-36479_Local_action_Correctie_vastleggen_uitspraak-TNOV-3 | WLZ | 492712980 | Written       |    25-12-2023 | WzdTNOV       | Curator           | Other                  |      1-2-2025 | Legal status issued |       10-2-2025 |  7-7-2025 |  11-3-2025 |                  6-2-2025 | Legal status issued |             6-2-2025 |            6-6-2025 |
  #Juridische status afgegeven met correctie-2

  @Correctie_uitspraak_scenarios-36479_Local_action_Correctie_vastleggen_uitspraak-RM
  Scenario Outline:
    Given We testen scenario: "<Scenario>"
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "26-01-2022" voor index: "2" op tab: "1"
    When Fill in veld value: "roepnaam-baby-Test" voor index: "3" op tab: "1"
    When Fill in veld value: "baby-Test" voor index: "4" op tab: "1"
    When Fill in veld value: "van den" voor index: "5" op tab: "1"
    When Fill in veld value: "Baby test" voor index: "6" op tab: "1"
    When Fill in veld value: "BT" voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "<wettelijkeRelatie>" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "<aanvraagdatum>" voor index: "1" op tab: "1"
    When Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    Then Druk op type: "radio" met naam: "No" met index: "5" op tab: "1"
    Then Druk op type: "radio" met naam: "No" met index: "6" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Aanvrager onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgaanbieder onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgverantwoordelijke onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Wzd-functionaris onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Tweede belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    When Druk op zaak: "WZD-RM" link voor: "<Scenario>" op tab: "1"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    ##### Controleren Administratieve volledigheid #######
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "5" op tab: "2"
    Then Fill in veld value: "7-1-2025" voor index: "1" op tab: "2"
    Then Select option by value: "6 months" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "7" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "8" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    #######Vastleggen medische verklaring#######
    When Druk op type: "radio" met naam: "Yes" met index: "9" op tab: "2"
    When Fill in veld value: "7-1-2025" voor index: "2" op tab: "2"
    When Select option by value: "Living at home" voor index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "No" met index: "10" op tab: "2"
    #######Vaststellen grondslag medische verklaring#########
    Then Druk op type: "radio" met naam: "Groundwork" met index: "0" op tab: "2"
    When Select option by value: "PhysicalHandicap" voor index: "2" op tab: "2"
    ##### Vooronderzoek - schermonderdeel Checklist medische verklaring #####
    Then Druk op type: "radio" met naam: "Sir" met index: "0" op tab: "2"
    When Fill in veld value: "Ik ben de dokter" voor index: "4" op tab: "2"
    When Fill in veld value: "12345678" voor index: "5" op tab: "2"
    When Select option by value: "SO" voor index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "11" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "12" op tab: "2"
    Then Fill in textvak value: "Waaruit blijkt dit" voor index: "5" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "7" op tab: "2"
    Then Fill in textvak value: "Diagnose" voor index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "13" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "14" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "15" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "16" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "17" op tab: "2"
    Then Fill in block value: "Waaruit bestaat ernstig nadeel" voor index: "7" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "18" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "19" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "20" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "21" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "22" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "8" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "23" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "24" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "25" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "26" op tab: "2"
    Then Fill in block value: "Toelichting" voor index: "8" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziektebiografie #####
    Then Druk op type: "button" met naam: "Datum toevoegen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziekte/Aandoening #####
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Wzd beoordeling - schermonderdeel Diagnose, ernstig nadeel en reikweidte #####
    Then Druk op type: "radio" met naam: "Groundwork" met index: "0" op tab: "2"
    When Select option by value: "PhysicalHandicap" voor index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "true" met index: "5" op tab: "2"
    When Iframe fill in value: "Toelichting bij Ander gevaar" voor index: "0" op tab: "2"
    When Iframe fill in value: "Beschrijf de diagnose en het gedrag die leiden tot ernstig nadeel. Vermeldt ook de DSM-classificatie als die relevant is" voor index: "1" op tab: "2"
    When Iframe fill in value: "Beschrijf de houding ten aanzien van opname en verblijf in een accommodatie" voor index: "2" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    When Iframe fill in value: "Toelichting Subsidiariteit, proportionaliteit en doelmatigheid" voor index: "3" op tab: "2"
    Then Select option by value: "FormalRequirements" voor index: "5" op tab: "2"
    When Iframe fill in value: "Onderbouwing geen verzoekschrift" voor index: "4" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    When Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    When Zoeken en invullen value: "Niet noodzakelijk" voor index: "1" indexpijl: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Postal" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "false" met index: "10" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    When Zoeken en invullen value: "Niet noodzakelijk" voor index: "1" indexpijl: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Postal" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "false" met index: "10" op tab: "2"
    Then Druk op type: "button" met naam: "Voltooien" met index: "0" op tab: "2"
    Then Status geupdate naar: "Wacht op rechtbank" voor index: "0" op tab: "2"
    ##### Wachten op rechtbank #####
    Then Druk op local action "Vastleggen uitspraak" op tab "2"
    ##### Vastleggen uitspraak #####
    When Fill in veld value: "<datum_uitspraak>" voor index: "0" op tab: "2"
    Then Select option by value: "<uitspraak>" voor index: "0" op tab: "2"
    # Then Druk op type: "radio" met naam: "Fully awarded" met index: "0" op tab: "2"
    # Then Druk op type: "radio" met naam: "Custody" met index: "0" op tab: "2"
    # When Fill in veld value: "<startDatum>" voor index: "1" op tab: "2"
    When Fill in veld value: "<beeindigd>" voor index: "3" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op local action "Correctie vastleggen uits..." op tab "2"
    When Select option by value: "<reden_correctiebesluit>" voor index: "0" op tab: "2"
    When Fill in block value: "Dit is een toelichting voor correctie vastleggen uitspraak" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op local action "Vernieuwen" op tab "2"
    When Gerelateerde Dossiers: "Alles weergeven" voor index: "0" op tab: "2"
    When Gerelateerde Dossiers: "WZD-RM" voor index: "0" op tab: "2"
    ###Gerelateerde dossiers#####
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    When Fill in veld value: "<correctie_datum_uitspraak>" voor index: "1" op tab: "2"
    Then Select option by value: "<uitspraak_correctie>" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Fully awarded" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Custody" met index: "0" op tab: "2"
    When Fill in veld value: "<correctie_startdatum>" voor index: "2" op tab: "2"
    When Fill in veld value: "<correctie_einddatum>" voor index: "3" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "2"
    Then Sla zaak met naam "WZD-RM" voor: "<Scenario>" in filenaam: "Correctie_uitspraak_scenarios-36479_Local_action_Correctie_vastleggen_uitspraak-TNOV" op tab: "2"

    Examples:
      | Scenario                                                                           | env | bsn       | Aanvraagwijze | Aanvraagsoort | wettelijkeRelatie | reden_correctiebesluit | aanvraagdatum | uitspraak                                                  | datum_uitspraak | beeindigd | startDatum | correctie_datum_uitspraak | uitspraak_correctie | correctie_startdatum | correctie_einddatum |
      | Correctie_uitspraak_scenarios-36479_Local_action_Correctie_vastleggen_uitspraak-RM | WLZ | 270105864 | Written       | WzdRM         | Curator           | IncorrectDate          |      1-2-2025 | No legal status issued and current legal status terminated |       10-2-2025 |  7-7-2025 |  11-3-2025 |                  6-2-2025 | Legal status issued |             6-2-2025 |            6-6-2025 |
      #| Correctie_uitspraak_scenarios-36479_Local_action_Correctie_vastleggen_uitspraak-RM | WLZ | 660395757 | Written       | WzdRM         | Curator           | RecoveryOrder          |      1-2-2025 | No legal status issued and current legal status terminated |       10-2-2025 |  7-7-2025 |  11-3-2025 |                  6-2-2025 | Legal status issued |             6-2-2025 |            6-6-2025 |
      #| Correctie_uitspraak_scenarios-36479_Local_action_Correctie_vastleggen_uitspraak-RM | WLZ | 520925580 | Written       | WzdRM         | Curator           | Other                  |      1-2-2025 | No legal status issued and current legal status terminated |       10-2-2025 |  7-7-2025 |  11-3-2025 |                  6-2-2025 | Legal status issued |             6-2-2025 |            6-6-2025 |

  @Correctie_uitspraak_scenarios-36479_Local_action_Correctie_vastleggen_uitspraak-VWM
  Scenario Outline:
    Given We testen scenario: "<Scenario>"
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "26-01-2022" voor index: "2" op tab: "1"
    When Fill in veld value: "roepnaam-baby-Test" voor index: "3" op tab: "1"
    When Fill in veld value: "baby-Test" voor index: "4" op tab: "1"
    When Fill in veld value: "van den" voor index: "5" op tab: "1"
    When Fill in veld value: "Baby test" voor index: "6" op tab: "1"
    When Fill in veld value: "BT" voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "<wettelijkeRelatie>" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "<aanvraagdatum>" voor index: "1" op tab: "1"
    When Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    # Then Druk op type: "radio" met naam: "No" met index: "5" op tab: "1"
    # Then Druk op type: "radio" met naam: "No" met index: "6" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Aanvrager onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgaanbieder onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgverantwoordelijke onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Wzd-functionaris onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Tweede belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    When Druk op zaak: "WZD-VWM" link voor: "<Scenario>" op tab: "1"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    ##### Controleren Administratieve volledigheid #######
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "5" op tab: "2"
    Then Fill in veld value: "7-1-2025" voor index: "1" op tab: "2"
    Then Select option by value: "6 months" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "7" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "8" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    #######Vastleggen medische verklaring#######
    When Druk op type: "radio" met naam: "Yes" met index: "9" op tab: "2"
    When Fill in veld value: "7-1-2025" voor index: "2" op tab: "2"
    When Select option by value: "Living at home" voor index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "No" met index: "10" op tab: "2"
    #######Vaststellen grondslag medische verklaring#########
    Then Druk op type: "radio" met naam: "Groundwork" met index: "0" op tab: "2"
    When Select option by value: "PhysicalHandicap" voor index: "2" op tab: "2"
    ##### Vooronderzoek - schermonderdeel Checklist medische verklaring #####
    Then Druk op type: "radio" met naam: "Sir" met index: "0" op tab: "2"
    When Fill in veld value: "Ik ben de dokter" voor index: "4" op tab: "2"
    When Fill in veld value: "12345678" voor index: "5" op tab: "2"
    When Select option by value: "SO" voor index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "11" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "12" op tab: "2"
    Then Fill in textvak value: "Waaruit blijkt dit" voor index: "5" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "7" op tab: "2"
    Then Fill in textvak value: "Diagnose" voor index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "13" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "14" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "15" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "16" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "17" op tab: "2"
    Then Fill in block value: "Waaruit bestaat ernstig nadeel" voor index: "7" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "18" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "19" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "20" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "21" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "22" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "8" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "23" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "24" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "25" op tab: "2"
    # Then Druk op type: "radio" met naam: "Yes" met index: "26" op tab: "2"
    Then Fill in block value: "Toelichting" voor index: "8" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziektebiografie #####
    Then Druk op type: "button" met naam: "Datum toevoegen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziekte/Aandoening #####
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ###WMC####
    When Druk op local action "Verzoek WMC" op tab "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op local action "Vernieuwen" op tab "2"
    Then Druk op type: "button" met naam: "Ga" met index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    # When Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    When Select option by value: "Intended conclusion remains" voor index: "0" op tab: "2"
    When Select option by value: "An adjustment is required in the client file" voor index: "1" op tab: "2"
    Then Fill in block value: "Dit is een voorbeeld voor de test" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Gerelateerde Dossiers: "Alles weergeven" voor index: "0" op tab: "2"
    When Gerelateerde Dossiers: "WZD-VWM" voor index: "0" op tab: "2"
    Then Druk op local action "Verniewen" op tab "2"
    # Then Druk op type: "button" met naam: "Ga" met index: "1" op tab: "2"
    # Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ######eindeWmc
    ##### Wzd beoordeling - schermonderdeel Diagnose, ernstig nadeel en reikweidte #####
    Then Druk op type: "radio" met naam: "Groundwork" met index: "0" op tab: "2"
    When Select option by value: "PhysicalHandicap" voor index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "true" met index: "5" op tab: "2"
    When Iframe fill in value: "Toelichting bij Ander gevaar" voor index: "0" op tab: "2"
    When Iframe fill in value: "Beschrijf de diagnose en het gedrag die leiden tot ernstig nadeel. Vermeldt ook de DSM-classificatie als die relevant is" voor index: "1" op tab: "2"
    When Iframe fill in value: "Beschrijf de houding ten aanzien van opname en verblijf in een accommodatie" voor index: "2" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    When Druk op type: "radio" met naam: "No" met index: "3" op tab: "2"
    When Iframe fill in value: "Toelichting Subsidiariteit, proportionaliteit en doelmatigheid" voor index: "3" op tab: "2"
    Then Select option by value: "FormalRequirements" voor index: "5" op tab: "2"
    # When Iframe fill in value: "Onderbouwing geen verzoekschrift" voor index: "4" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    When Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    When Zoeken en invullen value: "Onvoldoende informatie" voor index: "1" indexpijl: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Postal" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "false" met index: "10" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    When Zoeken en invullen value: "Onvoldoende informatie" voor index: "1" indexpijl: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Postal" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "false" met index: "10" op tab: "2"
    Then Druk op type: "button" met naam: "Voltooien" met index: "0" op tab: "2"
    Then Status geupdate naar: "Wacht op rechtbank" voor index: "0" op tab: "2"
    ##### Wachten op rechtbank #####
    Then Druk op local action "Vastleggen uitspraak" op tab "2"
    ##### Vastleggen uitspraak #####
    When Fill in veld value: "<datum_uitspraak>" voor index: "0" op tab: "2"
    Then Select option by value: "<uitspraak>" voor index: "0" op tab: "2"
    # Then Druk op type: "radio" met naam: "Fully awarded" met index: "0" op tab: "2"
    # Then Druk op type: "radio" met naam: "Custody" met index: "0" op tab: "2"
    # When Fill in veld value: "<startDatum>" voor index: "1" op tab: "2"
    When Fill in veld value: "<beeindigd>" voor index: "3" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op local action "Correctie vastleggen uits..." op tab "2"
    When Select option by value: "<reden_correctiebesluit>" voor index: "0" op tab: "2"
    When Fill in block value: "Dit is een toelichting voor correctie vastleggen uitspraak" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op local action "Vernieuwen" op tab "2"
    When Gerelateerde Dossiers: "Alles weergeven" voor index: "0" op tab: "2"
    When Gerelateerde Dossiers: "WZD-VWM" voor index: "0" op tab: "2"
    ###Gerelateerde dossiers#####
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    When Fill in veld value: "<correctie_datum_uitspraak>" voor index: "1" op tab: "2"
    Then Select option by value: "<uitspraak_correctie>" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Fully awarded" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Custody" met index: "0" op tab: "2"
    When Fill in veld value: "<correctie_startdatum>" voor index: "2" op tab: "2"
    When Fill in veld value: "<correctie_einddatum>" voor index: "3" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "2"
    Then Sla zaak met naam "WZD-VWM" voor: "<Scenario>" in filenaam: "Correctie_uitspraak_scenarios-36479_Local_action_Correctie_vastleggen_uitspraak-VWM" op tab: "2"

    Examples:
      | Scenario                                                                            | env | bsn       | Aanvraagwijze | Aanvraagsoort | wettelijkeRelatie | reden_correctiebesluit | aanvraagdatum | uitspraak                                                  | datum_uitspraak | beeindigd | startDatum | correctie_datum_uitspraak | uitspraak_correctie | correctie_startdatum | correctie_einddatum |
      | Correctie_uitspraak_scenarios-36479_Local_action_Correctie_vastleggen_uitspraak-VWM | WLZ | 270105864 | Written       | WzdVWM        | Curator           | IncorrectDate          |      1-2-2025 | No legal status issued and current legal status terminated |       10-2-2025 |  7-7-2025 |  11-3-2025 |                  6-2-2025 | Legal status issued |             6-2-2025 |            6-6-2025 |
      #| Correctie_uitspraak_scenarios-36479_Local_action_Correctie_vastleggen_uitspraak-VWM | WLZ | 660395757 | Written       | WzdVWM         | Curator           | RecoveryOrder          |      1-2-2025 | No legal status issued and current legal status terminated |       10-2-2025 |  7-7-2025 |  11-3-2025 |                  6-2-2025 | Legal status issued |             6-2-2025 |            6-6-2025 |
      #| Correctie_uitspraak_scenarios-36479_Local_action_Correctie_vastleggen_uitspraak-VWM | WLZ | 520925580 | Written       | WzdVWM         | Curator           | Other                  |      1-2-2025 | No legal status issued and current legal status terminated |       10-2-2025 |  7-7-2025 |  11-3-2025 |                  6-2-2025 | Legal status issued |             6-2-2025 |            6-6-2025 |

  @Correctie_uitspraak_scenarios-36479_Local_action_Correctie_vastleggen_uitspraak-IBS
  Scenario Outline:
    Given We testen scenario: "<Scenario>"
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "12-01-2022" voor index: "2" op tab: "1"
    When Fill in veld value: "roepnaam-baby-Test" voor index: "3" op tab: "1"
    When Fill in veld value: "baby-Test" voor index: "4" op tab: "1"
    When Fill in veld value: "van den" voor index: "5" op tab: "1"
    When Fill in veld value: "Baby test" voor index: "6" op tab: "1"
    When Fill in veld value: "BT" voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "<wettelijkeRelatie>" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "<aanvraagdatum>" voor index: "1" op tab: "1"
    Then Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Aanvrager onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgaanbieder onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgverantwoordelijke onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Wzd-functionaris onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Tweede belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    When Druk op zaak: "WZD-IBS" link voor: "<Scenario>" op tab: "1"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Vooronderzoek ######
    When Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Fill in veld value: "2-10-2025" voor index: "1" op tab: "2"
    When Select option by value: "Hospital" voor index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "Sir" met index: "0" op tab: "2"
    When Fill in veld value: "TestNaam" voor index: "2" op tab: "2"
    When Fill in veld value: "TestNaamBIG" voor index: "3" op tab: "2"
    When Select option by value: "SO" voor index: "1" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    ##### Ziektebiografie#####
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Datum toevoegen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziekte/Aandoening #####
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Wzd beoordeling #####
    Then Druk op type: "radio" met naam: "Groundwork" met index: "0" op tab: "2"
    When Select option by value: "PhysicalHandicap" voor index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "No" met index: "2" op tab: "2"
    When Druk op type: "radio" met naam: "true" met index: "5" op tab: "2"
    When Iframe fill in value: "Toelichting bij Ander gevaar" voor index: "0" op tab: "2"
    When Iframe fill in value: "Beschrijf de houding ten aanzien van opname en verblijf in een accommodatie" voor index: "2" op tab: "2"
    #When Iframe fill in value: "Beschrijf de houding ten aanzien van opname en verblijf in een accommodatie" voor index: "2" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    When Druk op type: "radio" met naam: "No" met index: "5" op tab: "2"
    When Iframe fill in value: "Toelichting Subsidiariteit, proportionaliteit en doelmatigheid" voor index: "3" op tab: "2"
    When Druk op type: "radio" met naam: "No" met index: "6" op tab: "2"
    Then Select option by value: "FormalRequirements" voor index: "5" op tab: "2"
    When Iframe fill in value: "Onderbouwing geen verzoekschrift" voor index: "4" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    ##### Informeren zorgaanbieder######
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    When Zoeken en invullen value: "Onvoldoende informatie" voor index: "1" indexpijl: "0" op tab: "2"
    Then Fill in veld value: "Rotterdam" voor index: "2" op tab: "2"
    Then Fill in veld value: "17-3-2025" voor index: "3" op tab: "2"
    Then Druk op type: "radio" met naam: "Postal" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "false" met index: "10" op tab: "2"
    Then Druk op type: "button" met naam: "Voltooien" met index: "0" op tab: "2"
    ######Wachten op rechtbank######
    Then Status geupdate naar: "Wacht op rechtbank" voor index: "0" op tab: "2"
    ##### Vastleggen uitspraak #####
    Then Druk op local action "Vastleggen uitspraak" op tab "2"
    When Fill in veld value: "<datum_uitspraak>" voor index: "0" op tab: "2"
    Then Select option by value: "<uitspraak>" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op local action "Correctie vastleggen uits..." op tab "2"
    When Select option by value: "<reden_correctiebesluit>" voor index: "0" op tab: "2"
    When Fill in block value: "Dit is een toelichting voor correctie vastleggen uitspraak" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op local action "Vernieuwen" op tab "2"
    When Gerelateerde Dossiers: "Alles weergeven" voor index: "0" op tab: "2"
    When Gerelateerde Dossiers: "WZD-IBS" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Wacht op deze pagina voor "3000" miliseconden op tab: "2"
    When Fill in veld value: "<correctie_datum_uitspraak>" voor index: "1" op tab: "2"
    Then Select option by value: "<uitspraak_correctie>" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Fully awarded" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Custody" met index: "0" op tab: "2"
    When Fill in veld value: "<correctie_startdatum>" voor index: "2" op tab: "2"
    When Fill in veld value: "<correctie_einddatum>" voor index: "3" op tab: "2"
    Given We testen scenario: "<Scenario>"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    ##### Controle op eindstatus - End2End flow #####
    Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "2"
    Then Sla zaak met naam "WZD-IBS" voor: "<Scenario>" in filenaam: "Correctie_uitspraak_scenarios-36479_Local_action_Correctie_vastleggen_uitspraak-IBS" op tab: "2"

    Examples:
      | Scenario                                                                              | env | bsn       | Aanvraagwijze | Aanvraagdatum | Aanvraagsoort | wettelijkeRelatie | reden_correctiebesluit | aanvraagdatum | uitspraak      | datum_uitspraak | einddatum | startDatum | correctie_datum_uitspraak | uitspraak_correctie | correctie_startdatum | correctie_einddatum |
      | Correctie_uitspraak_scenarios-36479_Local_action_Correctie_vastleggen_uitspraak-IBS-1 | WLZ | 060297761 | Written       |    25-12-2023 | WzdIBS        | Curator           | IncorrectDate          |      1-2-2025 | Not admissible |       10-2-2025 |  7-7-2025 |  11-3-2025 |                  6-2-2025 | Legal status issued |             6-2-2025 |            6-6-2025 |
      #| Correctie_uitspraak_scenarios-36479_Local_action_Correctie_vastleggen_uitspraak-IBS-2 | WLZ | 418403855 | Written       |    25-12-2023 | WzdIBS        | Curator           | RecoveryOrder          |      1-2-2025 | Legal status issued |       10-2-2025 |  7-7-2025 |  11-3-2025 |                  6-2-2025 | Legal status issued |             6-2-2025 |            6-6-2025 |
      #| Correctie_uitspraak_scenarios-36479_Local_action_Correctie_vastleggen_uitspraak-IBS-3 | WLZ | 266013363 | Written       |    25-12-2023 | WzdIBS        | Curator           | Other                  |      1-2-2025 | Legal status issued |       10-2-2025 |  7-7-2025 |  11-3-2025 |                  6-2-2025 | Legal status issued |             6-2-2025 |            6-6-2025 |

  @Correctie_uitspraak_scenarios-36479_Local_action_Correctie_vastleggen_uitspraak-WFZ
  Scenario Outline:
    Given We testen scenario: "<Scenario>"
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "26-01-2022" voor index: "2" op tab: "1"
    When Fill in veld value: "roepnaam-baby-Test" voor index: "3" op tab: "1"
    When Fill in veld value: "baby-Test" voor index: "4" op tab: "1"
    When Fill in veld value: "van den" voor index: "5" op tab: "1"
    When Fill in veld value: "Baby test" voor index: "6" op tab: "1"
    When Fill in veld value: "BT" voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "<wettelijkeRelatie>" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "<aanvraagdatum>" voor index: "1" op tab: "1"
    When Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    When Select option by value: "6 weeks" voor index: "2" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Aanvrager onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgaanbieder onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgverantwoordelijke onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Wzd-functionaris onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Tweede belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    When Druk op zaak: "WZD-WFZ" link voor: "<Scenario>" op tab: "1"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    ##### Vooronderzoek ######
    When Fill in veld value: "Kenmerk OM" voor index: "1" op tab: "2"
    When Fill in veld value: "21-3-2025" voor index: "2" op tab: "2"
    When Fill in veld value: "28-3-2025" voor index: "3" op tab: "2"
    When Fill in veld value: "Parket" voor index: "4" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Fill in veld value: "28-3-2025" voor index: "7" op tab: "2"
    When Select option by value: "Living at home" voor index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Sir" met index: "0" op tab: "2"
    Then Fill in veld value: "Dr vermaat" voor index: "8" op tab: "2"
    Then Fill in veld value: "BIG-123" voor index: "9" op tab: "2"
    Then Select option by value: "SO" voor index: "2" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    Then Fill in block value: "Toelichting" voor index: "1" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziektebiografie #####
    Then Druk op type: "button" met naam: "Datum toevoegen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziekte/Aandoening #####
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
     ##### WMC #####
    When Druk op local action "Verzoek WMC" op tab "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op local action "Vernieuwen" op tab "2"
    Then Druk op type: "button" met naam: "Ga" met index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "5" op tab: "2"
    When Select option by value: "Intended conclusion remains" voor index: "0" op tab: "2"
    When Select option by value: "An adjustment is required in the client file" voor index: "1" op tab: "2"
    Then Fill in block value: "Dit is een voorbeeld voor de test" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Gerelateerde Dossiers: "Alles weergeven" voor index: "0" op tab: "2"
    When Gerelateerde Dossiers: "WZD-WFZ" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    When Druk op type: "button" met naam: "Ga" met index: "1" op tab: "2"
    When Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Select option by value: "Rotterdam" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Voltooien" met index: "0" op tab: "2"
    When Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op local action "Vastleggen reactie OM" op tab "2"
    When Druk op type: "radio" met naam: "No" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op local action "Correctie vastleggen uits..." op tab "2"
    When Select option by value: "<reden_correctiebesluit>" voor index: "0" op tab: "2"
    When Fill in block value: "Dit is een toelichting voor correctie vastleggen uitspraak" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op local action "Vernieuwen" op tab "2"
    When Gerelateerde Dossiers: "Alles weergeven" voor index: "0" op tab: "2"
    When Gerelateerde Dossiers: "WZD-WFZ" voor index: "0" op tab: "2"
    When Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Wacht op deze pagina voor "3000" miliseconden op tab: "2"
    When Fill in veld value: "<datum_uitspraak>" voor index: "1" op tab: "2"
    Then Select option by value: "<uitspraak>" voor index: "0" op tab: "2"
    When Fill in veld value: "<beeindigd>" voor index: "4" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "2"
    Then Sla zaak met naam "WZD-WFZ" voor: "<Scenario>" in filenaam: "Correctie_uitspraak_scenarios-36479_Local_action_Correctie_vastleggen_uitspraak-WFZ" op tab: "2"

    Examples:
      | Scenario                                                                            | env | bsn       | Aanvraagwijze | Aanvraagsoort | wettelijkeRelatie | reden_correctiebesluit | aanvraagdatum | uitspraak                                                  | datum_uitspraak | beeindigd | startDatum | correctie_datum_uitspraak | uitspraak_correctie | correctie_startdatum | correctie_einddatum |
      | Correctie_uitspraak_scenarios-36479_Local_action_Correctie_vastleggen_uitspraak-WFZ | WLZ | 270105864 | Written       | WzdWFZ        | Curator           | IncorrectDate          |      1-2-2025 | No legal status issued and current legal status terminated |       10-2-2025 |  7-7-2025 |  11-3-2025 |                  6-2-2025 | Legal status issued |             6-2-2025 |            6-6-2025 |
      #| Correctie_uitspraak_scenarios-36479_Local_action_Correctie_vastleggen_uitspraak-RM | WLZ | 660395757 | Written       | WzdWFZ        | Curator           | RecoveryOrder          |      1-2-2025 | No legal status issued and current legal status terminated |       10-2-2025 |  7-7-2025 |  11-3-2025 |                  6-2-2025 | Legal status issued |             6-2-2025 |            6-6-2025 |
      #| Correctie_uitspraak_scenarios-36479_Local_action_Correctie_vastleggen_uitspraak-RM | WLZ | 520925580 | Written       | WzdWFZ        | Curator           | Other                  |      1-2-2025 | No legal status issued and current legal status terminated |       10-2-2025 |  7-7-2025 |  11-3-2025 |                  6-2-2025 | Legal status issued |             6-2-2025 |            6-6-2025 |
