Feature: Klacht oppakken in BUK app

  @KlachtOppakkenInBuk_test1
  Scenario: Check if user is on the right page (klacht niet in behandeling nemen)
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automation@ciz.nl" en wachtwoord: "Welkom04!" op tab: "0"
    When Druk op type: "Button" met naam: "BUK" met index: "0" op tab: "0"
    When Log in op pagina, met user: "test.automation@ciz.nl" en wachtwoord: "Welkom04!" op tab: "1"
    When Druk op type: "Button" met naam: "Klachten" met index: "0" op tab: "0"
    # When In app "BukApp" op pagina "GebruikersportaalPage" zoeken naar zaak: "BUK-K-27084" en pas toe op tab "1"    
    Then Druk op type: "Button" met naam: "Ga" met index: "0" op tab: "1"
    Then Klacht in behandeling nemen "nee" op tab: "1"
    Then Klacht niet in behandeling nemen "nee" reden wordt getoond op tab: "1"
    Then Status geupdate naar: "Open - In behandeling" op tab: "1"
    When Vul een toelichting in "primair" op tab: "1"
    Then Druk op type: "Button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Status geupdate naar: "Opgelost - Afgerond" op tab: "1"
    When Druk op: "dossier" zaak link op tab: "1"
    # Then Log in op "BukApp" pagina, tab "2" met user: "test.automation@ciz.nl" en wachtwoord: "Welkom04!"
    When Druk op Button met naam: "Ga" tab: "1"
    When Druk op Button met naam: "CIZPrinter1" tab: "1"
    When Druk op Button met naam: "Indienen" tab: "1"
    Then Status geupdate naar: "Opgelost - Afgerond" op tab: "1"

  @KlachtOppakkenInBuk_test2
  Scenario: Check if user is on the right page (klacht wel in behandeling nemen Klacht wel naar tevredenheid afgehandeld)
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automation@ciz.nl" en wachtwoord: "Welkom04!" op tab: "0"
    When Druk op Button met naam: "BUK" tab: "0"
    When Log in op pagina, met user: "test.automation@ciz.nl" en wachtwoord: "Welkom04!" op tab: "1"
    When Druk op Button met naam: "Klachten" tab: "1"
    When Druk op Button met naam: "Ga" tab: "1"
    When Klacht in behandeling nemen "ja" op tab: "1"
    Then Klacht niet in behandeling nemen "ja" reden wordt getoond op tab: "1"
    Then Status geupdate naar: "Open - In behandeling" op tab: "1"
    When Vul een toelichting in "primair" op tab: "1"
    When Druk op Button met naam: "Indienen" tab: "1"
    When Verslaglegging contact met de klager "primair" op tab: "1"
    When Klacht naar tevredenheid afgehandeld? "ja" op tab: "1"
    When Leerpunt voor CIZ "primair" op tab: "1"
    When Druk op Button met naam: "Indienen" tab: "1"
    Then Status geupdate naar: "Opgelost - Afgerond" op tab: "1"
    When Druk op: "dossier" zaak link op tab: "1"
    When Druk op Button met naam: "Ga" tab: "1"
    When Druk op Button met naam: "CIZPrinter1" tab: "1"
    When Druk op Button met naam: "Indienen" tab: "1"
    # Then Log in op "BukApp" pagina, tab "2" met user: "test.automation@ciz.nl" en wachtwoord: "Welkom04!"
    Then Status geupdate naar: "Opgelost - Afgerond" op tab: "1"

  @KlachtOppakkenInBuk_test3
  Scenario: Check if user is on the right page (klacht wel in behandeling nemen Klacht niet naar tevredenheid afgehandeld)
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automation@ciz.nl" en wachtwoord: "Welkom04!" op tab: "0"
    When Druk op Button met naam: "BUK" tab: "0"
    When Log in op pagina, met user: "test.automation@ciz.nl" en wachtwoord: "Welkom04!" op tab: "0"
    When Druk op Button met naam: "Klachten" tab: "1"
    When Druk op Button met naam: "Ga" tab: "1"
    When Klacht in behandeling nemen "ja" op tab: "1"
    Then Klacht niet in behandeling nemen "ja" reden wordt getoond op tab: "1"
    Then Status geupdate naar: "Open - In behandeling" op tab: "1"
    When Vul een toelichting in "primair" op tab: "1"
    When Druk op Button met naam: "Indienen" tab: "1"
    When Verslaglegging contact met de klager "primair" op tab: "1"
    When Klacht naar tevredenheid afgehandeld? "nee" op tab: "1"
    When Leerpunt voor CIZ "primair" op tab: "1"
    When Druk op Button met naam: "Indienen" tab: "1"
    When Verslaglegging contact met de klager "primair2" op tab: "1"
    When Wijze van afhandelen "Telefonisch contact" op tab: "1"
    When Klacht naar tevredenheid afgehandeld? "nee geescaleerd" op tab: "1"
    When Leerpunt voor CIZ "geescaleerd" op tab: "1"
    When Vul een toelichting in "geescaleerd" op tab: "1"
    When Druk op Button met naam: "Indienen" tab: "1"
    # Then Wacht op pagina
    Then Status geupdate naar: "Opgelost - Afgerond" op tab: "1"
    When Druk op: "dossier" zaak link op tab: "1"
    When Druk op Button met naam: "Ga" tab: "1"
    When Druk op Button met naam: "CIZPrinter1" tab: "1"
    When Druk op Button met naam: "Indienen" tab: "1"
    Then Status geupdate naar: "Opgelost - Afgerond" op tab: "1"
    # Then In: "BukApp" op pagina: "Gebruikersportaal" op tab: "1" is status geupdate naar: "Opgelost - Afgerond"
    # When In "BukApp" op tab "1" druk op "dossier" file link
    # Then Log in op "BukApp" pagina, tab "2"
    # Then In: "BukApp" op pagina: "Gebruikersportaal" op tab: "2" is status geupdate naar: "Opgelost - Afgerond"
