Feature: Aanvraagsoort TNOV en Opstellen verzoekschrift = Ja
Dit is een feature voor het testen van de functionaliteit voor Informeren Zorgaanbieder

  Background: https://ciz.atlassian.net/browse/ZSD-32698
    # Bij het uitvoeren van WzD-beoordelen voor aanvraagsoort = TNOV geldt dat altijd het veld 'Opstellen Verzoekschrift' + keuzes Ja en Nee enabled moet worden getoond. De schermen Informeren Rechtbank en Informeren Aanvrager worden getoond   
    # Het scenario dat Opstellen verzoekschrift = Nee en Aanvraagsoort = WzdRM moet leiden tot tot schermen Informeren Aanvrager en Zorgaanbieder 
    # wordt getest in test @ZSD-32434_32634_VerzoekSchrift_Nee_Informeren_Zorgaanbieder_Wzd_RM

  @ZSD_26447_Subtask_ZSD-36479_Local_action_Correctie_vastleggen_uitspraak-TNOV
  Scenario Outline:
    Given We testen scenario: "<Scenario>"
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "26-01-2022" voor index: "2" op tab: "1"
    When Fill in veld value: "roepnaam-baby-Test" voor index: "3" op tab: "1"
    When Fill in veld value: "baby-Test" voor index: "4" op tab: "1"
    When Fill in veld value: "van den" voor index: "5" op tab: "1"
    When Fill in veld value: "Baby test" voor index: "6" op tab: "1"
    When Fill in veld value: "BT" voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "<wettelijkeRelatie>" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "7-1-2025" voor index: "1" op tab: "1"
    Then Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Aanvrager onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgaanbieder onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgverantwoordelijke onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Wzd-functionaris onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Tweede belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    When Druk op zaak: "WZD-TNOV" link voor: "<Scenario>" op tab: "1"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    ##### Controleren Administratieve volledigheid #######
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziektebiografie #####
    Then Druk op type: "button" met naam: "Datum toevoegen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziekte/Aandoening #####
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Wzd beoordeling - schermonderdeel Diagnose, ernstig nadeel en reikweidte #####
    When Zoeken en invullen value: "Afschrift van de beslissing tot opname van de zorgverantwoordelijke" voor index: "1" indexpijl: "0" op tab: "2"
    Then Druk op type: "checkbox" met naam: "Het ernstig nadeel niet langer buiten een geregistreerde accommodatie kan worden afgewend." met index: "0" op tab: "2"
    When Iframe fill in value: "Toelichting" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Opstellen Verzoekschrift #####
    When Fill in veld value: "09-12-2024" voor index: "2" op tab: "2"
    When Fill in textvak value: "Verzoekschrift" voor index: "2" op tab: "2"
    When Fill in veld value: "09-12-2024" voor index: "4" op tab: "2"
    When Fill in textvak value: "Verzoekschrift" voor index: "3" op tab: "2"
    Then Druk op type: "button" met naam: "Voltooien" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Informeren Rechtbank #####
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    ##### Informeren Aanvrager #####
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Postal" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Status geupdate naar: "Wacht op rechtbank" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Sla zaak met naam "WLZ-TNOV" voor: "<Scenario>" in filenaam: "ZSD_26447_Subtask_ZSD-36479_Local_action_Correctie_vastleggen_uitspraak-TNOV.json" op tab: "2"
    ##### Wachten op rechtbank #####
    Then Druk op local action "Vastleggen uitspraak" op tab "2"
    ##### Vastleggen uitspraak #####
    When Fill in veld value: "09-12-2024" voor index: "0" op tab: "2"
    Then Select option by value: "Not admissible" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op local action "Correctie vastleggen uits..." op tab "2"
    When Select option by value: "<reden_correctiebesluit>" voor index: "0" op tab: "2"
    When Fill in block value: "Dit is een toelichting voor correctie vastleggen uitspraak" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op sidebar optie "Bijbehorende zaken" op tab "2"
    When Druk op zaak: "WLZWZD-OM" link voor: "<Scenario>" op tab: "2"
    Then Initieer nieuwe pagina op tab: "3"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "3"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "3"
    ##### Controle op eindstatus - End2End flow #####
    Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "2"
    Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "3"

    Examples:
      | Scenario                                                                       | env | bsn       | Aanvraagwijze | Aanvraagdatum | Aanvraagsoort | wettelijkeRelatie | reden_correctiebesluit |
      | ZSD_26447_Subtask_ZSD-36479_Local_action_Correctie_vastleggen_uitspraak-TNOV-1 | WLZ | 359497603 | Written       |    25-12-2023 | WzdTNOV       | Curator           | IncorrectDate          |
      | ZSD_26447_Subtask_ZSD-36479_Local_action_Correctie_vastleggen_uitspraak-TNOV-2 | WLZ | 511892895 | Written       |    25-12-2023 | WzdTNOV       | Curator           | RecoveryOrder          |
      | ZSD_26447_Subtask_ZSD-36479_Local_action_Correctie_vastleggen_uitspraak-TNOV-3 | WLZ | 133205265 | Written       |    25-12-2023 | WzdTNOV       | Curator           | Other                  |

  @ZSD_26447_Subtask_ZSD-36479_Local_action_Correctie_vastleggen_uitspraak-RM
  Scenario Outline:
    Given We testen scenario: "<Scenario>"
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "26-01-2022" voor index: "2" op tab: "1"
    When Fill in veld value: "roepnaam-baby-Test" voor index: "3" op tab: "1"
    When Fill in veld value: "baby-Test" voor index: "4" op tab: "1"
    When Fill in veld value: "van den" voor index: "5" op tab: "1"
    When Fill in veld value: "Baby test" voor index: "6" op tab: "1"
    When Fill in veld value: "BT" voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "<wettelijkeRelatie>" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "7-1-2025" voor index: "1" op tab: "1"
    When Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    Then Druk op type: "radio" met naam: "No" met index: "5" op tab: "1"
    Then Druk op type: "radio" met naam: "No" met index: "6" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Aanvrager onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgaanbieder onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgverantwoordelijke onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Wzd-functionaris onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Tweede belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    When Druk op zaak: "WZD-RM" link voor: "<Scenario>" op tab: "1"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    ##### Controleren Administratieve volledigheid #######
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "5" op tab: "2"
    Then Fill in veld value: "7-1-2025" voor index: "1" op tab: "2"
    Then Select option by value: "6 months" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "7" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "8" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    #######Vastleggen medische verklaring#######
    When Druk op type: "radio" met naam: "Yes" met index: "9" op tab: "2"
    When Fill in veld value: "7-1-2025" voor index: "2" op tab: "2"
    When Select option by value: "Living at home" voor index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "No" met index: "10" op tab: "2"
    #######Vaststellen grondslag medische verklaring#########
    Then Druk op type: "radio" met naam: "Groundwork" met index: "0" op tab: "2"
    When Select option by value: "PhysicalHandicap" voor index: "2" op tab: "2"
    ##### Vooronderzoek - schermonderdeel Checklist medische verklaring #####
    Then Druk op type: "radio" met naam: "Sir" met index: "0" op tab: "2"
    When Fill in veld value: "Ik ben de dokter" voor index: "4" op tab: "2"
    When Fill in veld value: "12345678" voor index: "5" op tab: "2"
    When Select option by value: "SO" voor index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "11" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "12" op tab: "2"
    Then Fill in textvak value: "Waaruit blijkt dit" voor index: "5" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "7" op tab: "2"
    Then Fill in textvak value: "Diagnose" voor index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "13" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "14" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "15" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "16" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "17" op tab: "2"
    Then Fill in block value: "Waaruit bestaat ernstig nadeel" voor index: "7" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "18" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "19" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "20" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "21" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "22" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "8" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "23" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "24" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "25" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "26" op tab: "2"
    Then Fill in block value: "Toelichting" voor index: "8" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziektebiografie #####
    Then Druk op type: "button" met naam: "Datum toevoegen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziekte/Aandoening #####
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Wzd beoordeling - schermonderdeel Diagnose, ernstig nadeel en reikweidte #####
    Then Druk op type: "radio" met naam: "Groundwork" met index: "0" op tab: "2"
    When Select option by value: "PhysicalHandicap" voor index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "true" met index: "5" op tab: "2"
    When Iframe fill in value: "Toelichting bij Ander gevaar" voor index: "0" op tab: "2"
    When Iframe fill in value: "Beschrijf de diagnose en het gedrag die leiden tot ernstig nadeel. Vermeldt ook de DSM-classificatie als die relevant is" voor index: "1" op tab: "2"
    When Iframe fill in value: "Beschrijf de houding ten aanzien van opname en verblijf in een accommodatie" voor index: "2" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    When Iframe fill in value: "Toelichting Subsidiariteit, proportionaliteit en doelmatigheid" voor index: "3" op tab: "2"
    Then Select option by value: "FormalRequirements" voor index: "5" op tab: "2"
    When Iframe fill in value: "Onderbouwing geen verzoekschrift" voor index: "4" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    When Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    When Zoeken en invullen value: "Niet noodzakelijk" voor index: "1" indexpijl: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Postal" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "false" met index: "10" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    When Zoeken en invullen value: "Niet noodzakelijk" voor index: "1" indexpijl: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Postal" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "false" met index: "10" op tab: "2"
    Then Druk op type: "button" met naam: "Voltooien" met index: "0" op tab: "2"
    Then Status geupdate naar: "Wacht op rechtbank" voor index: "0" op tab: "2"
    Then Sla zaak met naam "WLZ-TNOV" voor: "<Scenario>" in filenaam: "ZSD_26447_Subtask_ZSD-36479_Local_action_Correctie_vastleggen_uitspraak-RM.json" op tab: "2"
    ##### Wachten op rechtbank #####
    Then Druk op local action "Vastleggen uitspraak" op tab "2"
    ##### Vastleggen uitspraak #####
    When Fill in veld value: "09-12-2024" voor index: "0" op tab: "2"
    Then Select option by value: "Not admissible" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op local action "Correctie vastleggen uits..." op tab "2"
    When Select option by value: "<reden_correctiebesluit>" voor index: "0" op tab: "2"
    When Fill in block value: "Dit is een toelichting voor correctie vastleggen uitspraak" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op sidebar optie "Bijbehorende zaken" op tab "2"
    When Druk op zaak: "WLZWZD-OM" link voor: "<Scenario>" op tab: "2"
    Then Initieer nieuwe pagina op tab: "3"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "3"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "3"
    ##### Controle op eindstatus - End2End flow #####
    Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "2"
    Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "3"

    Examples:
      | Scenario                                                                       | env | bsn       | Aanvraagwijze | Aanvraagdatum | Aanvraagsoort | wettelijkeRelatie | reden_correctiebesluit |
      | ZSD_26447_Subtask_ZSD-36479_Local_action_Correctie_vastleggen_uitspraak-TNOV-1 | WLZ | 317256002 | Written       |    25-12-2023 | WzdRM         | Curator           | IncorrectDate          |
      | ZSD_26447_Subtask_ZSD-36479_Local_action_Correctie_vastleggen_uitspraak-TNOV-2 | WLZ | 406318931 | Written       |    25-12-2023 | WzdRM         | Curator           | RecoveryOrder          |
      | ZSD_26447_Subtask_ZSD-36479_Local_action_Correctie_vastleggen_uitspraak-TNOV-3 | WLZ | 282816197 | Written       |    25-12-2023 | WzdRM         | Curator           | Other                  |

  @ZSD-26769_ZSD-26780_26781_33495_WzD-IBS_End2End_Status_Correctie_VastleggenUitspraak
  Scenario Outline:
    Given We testen scenario: "<Scenario>"
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "26-01-2022" voor index: "2" op tab: "1"
    When Fill in veld value: "roepnaam-baby-Test" voor index: "3" op tab: "1"
    When Fill in veld value: "baby-Test" voor index: "4" op tab: "1"
    When Fill in veld value: "van den" voor index: "5" op tab: "1"
    When Fill in veld value: "Baby test" voor index: "6" op tab: "1"
    When Fill in veld value: "BT" voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "Curator" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "7-1-2025" voor index: "1" op tab: "1"
    Then Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Aanvrager onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgaanbieder onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgverantwoordelijke onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Wzd-functionaris onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Tweede belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    When Druk op zaak: "WZD-IBS" link voor: "<Scenario>" op tab: "1"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    ##### Vooronderzoek - Vastleggen medische verklaring #######
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "1" op tab: "2"
    When Select option by value: "WVGGZ" voor index: "0" op tab: "2"
    ##### Vooronderzoek - schermonderdeel Checklist medische verklaring #####
    Then Druk op type: "radio" met naam: "Sir" met index: "0" op tab: "2"
    When Fill in veld value: "Ik ben de dokter" voor index: "2" op tab: "2"
    When Fill in veld value: "12345678" voor index: "3" op tab: "2"
    When Select option by value: "SO" voor index: "1" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziektebiografie #####
    Then Druk op type: "button" met naam: "Datum toevoegen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Reload pagina op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziekte/Aandoening #####
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Wzd beoordeling - schermonderdeel Diagnose, ernstig nadeel en reikweidte #####
    Then Select option by value: "PhysicalHandicap" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    When Druk op type: "checkbox" met naam: "Ander gevaar" met index: "0" op tab: "2"
    When Iframe fill in value: "Toelichting bij 'Ander gevaar'" voor index: "0" op tab: "2"
    When Iframe fill in value: "Beschrijf de diagnose en het gedrag die leiden tot ernstig nadeel" voor index: "1" op tab: "2"
    When Iframe fill in value: "Beschrijf de houding ten aanzien van opname en verblijf in een accommodatie" voor index: "2" op tab: "2"
    ##### Wzd beoordeling - schermonderdeel Noodzaak #####
    Then Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    Then Druk op type: "radio" met naam: "No" met index: "5" op tab: "2"
    When Iframe fill in value: "Toelichting Subsidiariteit, proportionaliteit en doelmatigheid" voor index: "3" op tab: "2"
    ##### Wzd beoordeling - schermonderdeel Conclusie, advies en ondertekening #####
    Then Druk op type: "radio" met naam: "No" met index: "6" op tab: "2"
    Then Select option by value: "FormalRequirements" voor index: "5" op tab: "2"
    When Iframe fill in value: "Toelichting Subsidiariteit, proportionaliteit en doelmatigheid" voor index: "4" op tab: "2"
    When Fill in veld value: "06-02-2025" voor index: "1" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Informeren Zorgaanbieder #####
    Then Zoeken en invullen value: "Onvoldoende informatie" voor index: "1" indexpijl: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Postal" met index: "0" op tab: "2"
    Then Fill in veld value: "Zuidplas" voor index: "2" op tab: "2"
    Then Fill in veld value: "05-12-2024" voor index: "3" op tab: "2"
    Then Druk op type: "button" met naam: "Voltooien" met index: "0" op tab: "2"
    Then Status geupdate naar: "Wacht op rechtbank" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Wachten op rechtbank #####
    Then Druk op local action "Vastleggen uitspraak" op tab "2"
    Then Druk op type: "checkbox" met naam: "<tijdelijkeUitspraak>" met index: "0" op tab: "2"
    When Fill in veld value: "<datumUitspraak>" voor index: "0" op tab: "2"
    Then Select option by value: "<Uitspraak>" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "<specificatieUitspraak>" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "<juridischeStatus>" met index: "0" op tab: "2"
    When Fill in veld value: "<startDatum>" voor index: "1" op tab: "2"
    When Fill in veld value: "<eindDatum>" voor index: "2" op tab: "2"
    When Fill in veld value: "<beindigdPer>" voor index: "3" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op local action "Correctie vastleggen uits..." op tab "2"
    When Select option by value: "<reden_correctiebesluit>" voor index: "0" op tab: "2"
    When Fill in block value: "Dit is een toelichting voor correctie vastleggen uitspraak" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op sidebar optie "Bijbehorende zaken" op tab "2"
    When Druk op zaak: "WLZWZD-OM" link voor: "<Scenario>" op tab: "2"
    Then Initieer nieuwe pagina op tab: "3"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "3"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "3"
    ##### Controle op eindstatus - End2End flow #####
    Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "2"
    Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "3"
    Then Sla zaak met naam "WZD-IBS" voor: "<Scenario>" in filenaam: "ZSD-26769_ZSD-26780_26781_33495_WzD-IBS_End2End_Status_Correctie_VastleggenUitspraak.json" op tab: "2"

    Examples:
      | Scenario | env | bsn       | Aanvraagwijze | Aanvraagdatum | Aanvraagsoort | tijdelijkeUitspraak | datumUitspraak | Uitspraak      | specificatieUitspraak | juridischeStatus | startDatum | eindDatum | beindigdPer | reden_correctiebesluit |
      |        1 | WLZ | 031495163 | Written       |    25-12-2023 | WzdIBS        | n.v.t.              |     09-12-2024 | Not admissible | n.v.t.                | n.v.t.           | n.v.t.     | n.v.t.    | n.v.t.      | IncorrectDate          |

  @ZSD_33517_WZD_WFZ_Correctie_VastleggenUitspraak
  Scenario Outline: Register and validate a new client in WLZ application
    Given We testen scenario: "<Scenario>"
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "03-09-2010" voor index: "2" op tab: "1"
    When Fill in veld value: "Testr" voor index: "3" op tab: "1"
    When Fill in veld value: "Testr" voor index: "4" op tab: "1"
    When Fill in veld value: "Testr" voor index: "5" op tab: "1"
    When Fill in veld value: "van de" voor index: "6" op tab: "1"
    When Fill in veld value: "Ter" voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "<wettelijkeRelatie>" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "7-1-2025" voor index: "1" op tab: "1"
    Then Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    Then Select option by value: "2 weeks" voor index: "2" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Aanvrager onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgaanbieder onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgverantwoordelijke onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Wzd-functionaris onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Tweede belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    When Druk op zaak: "WZD-WFZ" link voor: "<Scenario>" op tab: "1"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "2"
    #### vooronderzoek
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Fill in veld value: "7-1-2025" voor index: "2" op tab: "2"
    Then Fill in veld value: "7-9-2025" voor index: "3" op tab: "2"
    Then Fill in veld value: "Kenmerk" voor index: "1" op tab: "2"
    Then Fill in veld value: "Pakketje" voor index: "4" op tab: "2"
    Then Select option by value: "9" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Select option by value: "Living at home" voor index: "1" op tab: "2"
    Then Fill in veld value: "01-01-2025" voor index: "7" op tab: "2"
    Then Druk op type: "radio" met naam: "Sir" met index: "0" op tab: "2"
    Then Fill in veld value: "Benny" voor index: "8" op tab: "2"
    Then Fill in veld value: "6688" voor index: "9" op tab: "2"
    Then Select option by value: "SO" voor index: "2" op tab: "2"
    Then Druk op type: "radio" met naam: "No" met index: "1" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    ### WMC verzoek ###
    When Druk op local action "Verzoek WMC" op tab "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "5" op tab: "2"
    When Select option by value: "Intended conclusion remains" voor index: "0" op tab: "2"
    When Select option by value: "An adjustment is required in the client file" voor index: "1" op tab: "2"
    Then Fill in block value: "Dit is een voorbeeld voor de test" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Wacht op deze pagina voor "60000" miliseconden op tab: "2"
    When Druk op zaak: "WZD-WFZ" link voor: "<Scenario>" op tab: "1"
    # Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    # Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Public Prosecutor" met index: "0" op tab: "2"
    When Select option by value: "Amsterdam" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Voltooien" met index: "0" op tab: "2"
    Given Status geupdate naar: "Wacht op OM" voor index: "0" op tab: "2"
    #Then Sla zaak met naam "WZD-WFZ" voor: "<Scenario>" in filenaam: "ZSD_33517_WZD_WFZ_Correctie_VastleggenUitspraak.json" op tab: "2"
        ## zaak opzoek
    Then Navigeer naar "startpagina" omgeving op tab: "2"
    Then Selecteer werkwachtrij: "Wachten op OM" op tab: "2"
    Then Druk op type: "aria label" met naam: "ID Actions" met index: "1" op tab: "2"
    Then Druk op type: "Menu item" met naam: "Filter toepassen" met index: "0" op tab: "2"
    Then In werkbakken zoek zaak op index: "2" op tab: "2"
    # Then Druk op type: "button" met naam: "Ga" met index: "1" op tab: "2"
    # Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    When Druk op local action "Vastleggen reactie OM" op tab "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Fill in veld value: "7-9-2025" voor index: "0" op tab: "2"
    # When Select option by value: "13" voor index: "0" op tab: "2"
    # When Select option by value: "10" voor index: "1" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Status geupdate naar: "Wacht op rechtbank" voor index: "0" op tab: "2"
    #### vastleggen uitspraak
    Then Druk op local action "Vastleggen uitspraak" op tab "2"
    Then Druk op type: "checkbox" met naam: "<tijdelijkeUitspraak>" met index: "0" op tab: "2"
    When Fill in veld value: "<datumUitspraak>" voor index: "0" op tab: "2"
    Then Select option by value: "<Uitspraak>" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "<specificatieUitspraak>" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "<juridischeStatus>" met index: "0" op tab: "2"
    When Fill in veld value: "<startDatum>" voor index: "1" op tab: "2"
    When Fill in veld value: "<eindDatum>" voor index: "2" op tab: "2"
    When Fill in veld value: "<beindigdPer>" voor index: "3" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "2"
    Given We testen scenario: "<Scenario>"
    When Druk op local action "Correctie vastleggen uits..." op tab "2"
    When Select option by value: "<reden_correctiebesluit>" voor index: "0" op tab: "2"
    When Fill in block value: "Dit is een toelichting voor correctie vastleggen uitspraak" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op sidebar optie "Bijbehorende zaken" op tab "2"
    When Druk op zaak: "WLZWZD-OM" link voor: "<Scenario>" op tab: "2"
    Then Initieer nieuwe pagina op tab: "3"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "3"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "3"
    ##### Controle op eindstatus - End2End flow #####
    Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "2"
    Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "3"
    Then Sla zaak met naam "WZD-WFZ" voor: "<Scenario>" in filenaam: "ZSD_33517_WZD_WFZ_Correctie_VastleggenUitspraak.json" op tab: "2"

    Examples:
      | Scenario                       | env | bsn       | Aanvraagwijze | Aanvraagdatum | Aanvraagsoort | tijdelijkeUitspraak | datumUitspraak | Uitspraak      | specificatieUitspraak | juridischeStatus | startDatum | eindDatum | beindigdPer | reden_correctiebesluit |
      | 1request_WZD_New_Client_WFZ_OM | WLZ | 295254804 | Written       |    25-12-2023 | WzdWFZ        | n.v.t.              |     09-12-2024 | Not admissible | n.v.t.                | n.v.t.           | n.v.t.     | n.v.t.    | n.v.t.      | IncorrectDate          |
