Feature: Create client in WLZ application
  as a user
  I want to be able to create a new client in the WLZ application
  so i can complete the registration

  @request_WLZ_New_Client_test1_reguliereAanvraag
  Scenario Outline: Register and validate a new client in WLZ application
    Given Go to AppFactoryApp app page
    Given We testen scenario: "<Scenario>"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "03-09-2010" voor index: "2" op tab: "1"
    When Fill in veld value: "Tester" voor index: "3" op tab: "1"
    When Fill in veld value: "Tester" voor index: "4" op tab: "1"
    When Fill in veld value: "Tester" voor index: "5" op tab: "1"
    When Fill in veld value: "van de" voor index: "6" op tab: "1"
    When Fill in veld value: "Ter" voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "<wettelijkeRelatie>" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "7-1-2025" voor index: "1" op tab: "1"
    Then Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    When Druk op type: "radio" met naam: "No" met index: "8" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "1"
    When Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "1"
    When Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "1"
    When Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "1"
    When Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "1"
    Then Fill in veld value: "2803PK" voor index: "4" op tab: "1"
    Then Fill in veld value: "30" voor index: "5" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    When Druk op zaak: "WLZ" link voor: "<Scenario>" op tab: "1"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Research" met index: "0" op tab: "2"
    # Then Druk op type: "radio" met naam: "<voegProjectOfMaatregelToe>" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "label" met naam: "Plannen via Zorro" met index: "0" op tab: "2"
    Then Select option by value: "<afspraakSoort>" voor index: "0" op tab: "2"
    When Fill in veld value: "James.Cheung@ciz.nl" voor index: "1" op tab: "2"
    When Select option by value: "HomeAddress" voor index: "1" op tab: "2"
    When Fill in veld value: "21-04-2025 11:00" voor index: "4" op tab: "2"
    When Fill in veld value: "21-04-2025 12:00" voor index: "5" op tab: "2"
    When Select option by value: "HomeAddress" voor index: "1" op tab: "2"
    Then Fill in block value: "toelichting" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "<isIDVastgesteld>" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "No" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "EU citizen without a Dutch identification document" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Nvt / Niet beoordeeld" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Nvt / Niet beoordeeld" met index: "1" op tab: "2"
    Then Druk op type: "button" met naam: "Nvt / Niet beoordeeld" met index: "2" op tab: "2"
    Then Druk op type: "button" met naam: "Nvt / Niet beoordeeld" met index: "3" op tab: "2"
    Then Druk op type: "button" met naam: "Nvt / Niet beoordeeld" met index: "4" op tab: "2"
    Then Druk op type: "button" met naam: "Nvt / Niet beoordeeld" met index: "5" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Geen beperking / Gecompenseerd" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Nvt / Niet beoordeeld" met index: "1" op tab: "2"
    Then Druk op type: "button" met naam: "Nvt / Niet beoordeeld" met index: "2" op tab: "2"
    Then Druk op type: "button" met naam: "Nvt / Niet beoordeeld" met index: "3" op tab: "2"
    Then Druk op type: "button" met naam: "Geen beperking / Gecompenseerd" met index: "4" op tab: "2"
    Then Druk op type: "button" met naam: "Nvt / Niet beoordeeld" met index: "5" op tab: "2"
    Then Druk op type: "button" met naam: "Nvt / Niet beoordeeld" met index: "6" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Groundwork" met index: "0" op tab: "2"
    When Select option by value: "PhysicalHandicap" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "<permanentToezicht>" met index: "0" op tab: "2"
    When Zoeken en invullen value: "De cliënt richt zich maatschappelijk te gronde of dreigt dat te doen" voor index: "1" indexpijl: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "<toegangWLZ>" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "AccessToWLZCriteria" met index: "0" op tab: "2"
    When Fill in block value: "toelichting" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "<opstarten>" met index: "2" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    When Zoeken en invullen value: "<zorgProfielReeks>" voor index: "1" indexpijl: "0" op tab: "2"
    Then Select option by value: "<zorgProfiel>" voor index: "0" op tab: "2"
    Then Select option by value: "OPN" voor index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Fill in veld value: "07-01-2025" voor index: "2" op tab: "2"
    # When Fill in veld value: "07-01-2026" voor index: "3" op tab: "2"
    Then Druk op type: "checkbox" met naam: "Leeftijdsgrens van 18 jaar negeren" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    When Select option by value: "<Besluitbrief>" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Voeg basismotivering toe" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "true" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Voltooien" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Sla zaak met naam "WLZ-IND" voor: "<Scenario>" in filenaam: "request_WLZ_New_Client_test1_reguliereAanvraag.json" op tab: "2"

    Examples:
      | Scenario                          | env | bsn       | klant  | geheimPersoon | speciaalOnderzoek | geboortedatum | naamgebruik | burgerlijkeStaat       | leefSituatie | juridischeMaatregelen | verblijfStatus | geheimNummer | geheimNummer2 | taal  | telefonischeCommunicatie | bijzondereCommunicatieVorm | relatie                     | wettelijkeRelatie | partnerGeboorteDatum | woontOpZelfdeAdres | Aanvraagsoort  | Aanvraagdatum | Aanvraagwijze | huisArtsClient | verzekering     | nieuwOfBestaandZorg   | zorgVraag1 | zorgVraag2 | zorgVraag3 | WZDversneld | checkboxes | stroom | voegProjectOfMaatregelToe | afspraakSoort     | isIDVastgesteld                    | orientatieStoornis  | psychischFunctioneren | motorischFunctioneren | psychoSociaalWelzijn | probleemGedrag      | verslavingsProblemen | socialeRaadZaamheid | mobiliteit          | persoonlijkeZorg    | huishoudelijkLeven  | socialeRelatiesEnMaatschappelijk | deelnameOnderwijs   | deelnameWerk        | grondslag | eersteGrondslag      | permanentToezicht | toegangWLZ | negatiefBesluit | opstarten | zorgProfielReeks | zorgProfiel | Besluitbrief | aanvragenReview |
      | request_WLZ_New_Client_regulier_1 | WLZ | 680664397 | nieuwe | no            | no                |            10 | Barbera     | NeverMarriedNorPartner | AtParents    | None                  | Permanent      | no           | no            | Dutch | yes                      | None                       | WettelijkeVertegenwoordiger | Curator           | None                 | None               | RegularRequest |    12-10-2023 | Written       | search data    | Dutch insurance | Applying for new care | nee        | nee        | nee        | n.v.t       | nee        | Assess | None                      | HospitalHomeVisit | Yes, Face to Face contact with CIZ | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld   | Nvt/Niet beoordeeld   | Nvt/Niet beoordeeld  | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld  | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld              | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | ja        | Lichamelijk handicap | Yes               | Yes        | nee             | No        | GGZB             | LG02        | ZB05         | nee             |

  @request_WLZ_New_Client_test1_WZDA21
  Scenario Outline: Register and validate a new client in WLZ application
    Given We testen scenario: "<Scenario>"
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "03-09-2018" voor index: "2" op tab: "1"
    When Fill in veld value: "Test" voor index: "3" op tab: "1"
    When Fill in veld value: "Test" voor index: "4" op tab: "1"
    When Fill in veld value: "van de" voor index: "5" op tab: "1"
    When Fill in veld value: "Test" voor index: "6" op tab: "1"
    When Fill in veld value: "B." voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "<wettelijkeRelatie>" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "7-1-2025" voor index: "1" op tab: "1"
    Then Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    Then Druk op type: "n.v.t." met naam: "WZD- versneld" met index: "0" op tab: "1"
    Then Druk op type: "n.v.t" met naam: "project" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Aanvrager onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgaanbieder onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgverantwoordelijke onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Wzd-functionaris onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Tweede belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    When Druk op zaak: "WZD-A21" link voor: "<Scenario>" op tab: "1"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Research" met index: "0" op tab: "2"
    # Then Druk op type: "radio" met naam: "<voegProjectOfMaatregelToe>" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "label" met naam: "Plannen via Zorro" met index: "0" op tab: "2"
    Then Select option by value: "<afspraakSoort>" voor index: "0" op tab: "2"
    When Fill in veld value: "James.Cheung@ciz.nl" voor index: "1" op tab: "2"
    When Select option by value: "HomeAddress" voor index: "1" op tab: "2"
    When Fill in veld value: "21-04-2025 10:00" voor index: "4" op tab: "2"
    When Fill in veld value: "21-04-2025 11:00" voor index: "5" op tab: "2"
    When Select option by value: "HomeAddress" voor index: "1" op tab: "2"
    Then Fill in block value: "toelichting" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    When Druk op local action "Identiteitscontrole" op tab "2"
    Then Druk op type: "radio" met naam: "<isIDVastgesteld>" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "No" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "EU citizen without a Dutch identification document" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    When Druk op local action "Verzoek WMC" op tab "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "5" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "7" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "8" op tab: "2"
    Then Select option by value: "Intended conclusion remains" voor index: "0" op tab: "2"
    Then Select option by value: "No adjustment is required in the client file" voor index: "1" op tab: "2"
    When Fill in block value: "toelichting" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Wacht op deze pagina voor "60000" miliseconden op tab: "1"
    When Druk op zaak: "WZD-A21" link voor: "<Scenario>" op tab: "1"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    When Fill in block value: "toelichting" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "No" met index: "0" op tab: "2"
    Then Select option by value: "No vg, pg, equivalent condition or psy" voor index: "0" op tab: "2"
    Then Select option by value: "Inclusion on the basis of Article 21 is in order" voor index: "1" op tab: "2"
    When Fill in block value: "toelichting" voor index: "3" op tab: "2"
    When Fill in block value: "toelichting" voor index: "4" op tab: "2"
    When Fill in veld value: "07-01-2026" voor index: "3" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    # Then Druk op type: "radio" met naam: "OverwritesExistingStatus" met index: "0" op tab: "2"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Groundwork" met index: "0" op tab: "2"
    When Select option by value: "PhysicalHandicap" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Select option by value: "WZDB04" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Voeg basismotivering toe" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "true" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "label" met naam: "Besluit ook aan cliënt meedelen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Voltooien" met index: "0" op tab: "2"
    Given Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "2"
    Then Sla zaak met naam "WZD-A21" voor: "<Scenario>" in filenaam: "request_WLZ_New_Client_test1_WZDA21.json" op tab: "2"
    When Druk op local action "Maak AH-zaak aan" op tab "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Rechterlijke uitspraak" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Gerelateerde Dossiers: "WZD-A21" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "<isIDVastgesteld>" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "No" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "EU citizen without a Dutch identification document" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    When Druk op local action "Verzoek WMC" op tab "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "5" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "7" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "8" op tab: "2"
    Then Select option by value: "Intended conclusion remains" voor index: "0" op tab: "2"
    Then Select option by value: "No adjustment is required in the client file" voor index: "1" op tab: "2"
    When Fill in block value: "toelichting" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Wacht op deze pagina voor "60000" miliseconden op tab: "1"
    When Druk op zaak: "WZD-A21" link voor: "<Scenario>" op tab: "1"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    When Fill in block value: "toelichting" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "No" met index: "0" op tab: "2"
    Then Select option by value: "No vg, pg, equivalent condition or psy" voor index: "0" op tab: "2"
    Then Select option by value: "Inclusion on the basis of Article 21 is in order" voor index: "1" op tab: "2"
    When Fill in block value: "toelichting" voor index: "3" op tab: "2"
    When Fill in block value: "toelichting" voor index: "4" op tab: "2"
    When Fill in veld value: "07-01-2026" voor index: "3" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "OverwritesExistingStatus" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Groundwork" met index: "0" op tab: "2"
    When Select option by value: "PhysicalHandicap" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Select option by value: "WZDB04" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Voeg basismotivering toe" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "true" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "label" met naam: "Besluit ook aan cliënt meedelen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Voltooien" met index: "0" op tab: "2"
    Given Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "2"

    Examples:
      | Scenario                              | env | bsn       | klant  | geheimPersoon | speciaalOnderzoek | geboortedatum | naamgebruik | burgerlijkeStaat       | leefSituatie | juridischeMaatregelen | verblijfStatus | geheimNummer | geheimNummer2 | taal  | telefonischeCommunicatie | bijzondereCommunicatieVorm | relatie                     | wettelijkeRelatie | partnerGeboorteDatum | woontOpZelfdeAdres | Aanvraagsoort | Aanvraagdatum | Aanvraagwijze | huisArtsClient | verzekering     | nieuwOfBestaandZorg | zorgVraag1 | zorgVraag2 | zorgVraag3 | WZDversneld | checkboxes | stroom    | afspraakSoort     | isIDVastgesteld                    | aardEnNoodzaak | informatieVoorziening | Besluitbrief | aanvragenReview |
      | request_WLZ_New_Client_test1_WZDA21-2 | WLZ | 052736714 | nieuwe | no            | no                |             8 | BirthName   | NeverMarriedNorPartner | AtParents    | None                  | Permanent      | no           | no            | Dutch | yes                      | None                       | WettelijkeVertegenwoordiger | Curator           | None                 | None               | WLZWZDA21     |    12-10-2023 | Written       | search data    | Dutch insurance | n.v.t               | n.v.t      | n.v.t      | n.v.t      | n.v.t       | ja         | Onderzoek | HospitalHomeVisit | Yes, Face to Face contact with CIZ | ja             | ja                    |              | nee             |

  @request_WLZ_New_Client_test1_WZD_RM
  Scenario Outline: Register and validate a new client in WLZ application
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "26-01-2022" voor index: "2" op tab: "1"
    When Fill in veld value: "roepnaam-baby-Test" voor index: "3" op tab: "1"
    When Fill in veld value: "baby-Test" voor index: "4" op tab: "1"
    When Fill in veld value: "van den" voor index: "5" op tab: "1"
    When Fill in veld value: "Baby test" voor index: "6" op tab: "1"
    When Fill in veld value: "BT" voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "<wettelijkeRelatie>" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "7-1-2025" voor index: "1" op tab: "1"
    Then Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    Then Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "1"
    Then Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "1"
    Then Fill in veld value: "22-10-2023" voor index: "2" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Aanvrager onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgaanbieder onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgverantwoordelijke onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Wzd-functionaris onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Tweede belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    When Druk op zaak: "WZD-RM" link voor: "<Scenario>" op tab: "1"
    Then Sla zaak met naam "WZD-RM" voor: "<Scenario>" in filenaam: "request_WLZ_New_Client_test1_WZD_RM.json" op tab: "2"

    Examples:
      | Scenario | env | bsn       | klant  | geboortedatum | Aanvraagwijze | Aanvraagdatum | Aanvraagsoort | naamgebruik | burgerlijkeStaat       | leefSituatie | juridischeMaatregelen | verblijfStatus | geheimNummer | geheimNummer2 | taal  | telefonischeCommunicatie | bijzondereCommunicatieVorm | relatie                     | wettelijkeRelatie | partnerGeboorteDatum | woontOpZelfdeAdres | huisArtsClient | verzekering     | nieuwOfBestaandZorg           | zorgVraag1 | zorgVraag2 | zorgVraag3 | WZDversneld | checkboxes | stroom     | isIDVastgesteld  | orientatieStoornis  | psychischFunctioneren | motorischFunctioneren | psychoSociaalWelzijn | probleemGedrag      | verslavingsProblemen | socialeRaadZaamheid | mobiliteit          | persoonlijkeZorg    | huishoudelijkLeven  | socialeRelatiesEnMaatschappelijk | deelnameOnderwijs   | deelnameWerk        | grondslag | eersteGrondslag      | permanentToezicht | toegangWLZ | negatiefBesluit | opstarten | zorgProfielReeks | zorgProfiel | Besluitbrief | aanvragenReview | checkboxes |
      |        1 | WLZ | 695870117 | nieuwe |            10 | Written       |    25-12-2023 | WzdRM         | BirthName   | NeverMarriedNorPartner | AtParents    | None                  | Permanent      | no           | no            | Dutch | yes                      | None                       | WettelijkeVertegenwoordiger | Curator           | None                 | None               | search data    | Dutch insurance | Bestaande Wlz-zorg stopzetten | nee        | nee        | nee        | n.v.t       | nee        | Beoordelen | Ja, face to face | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld   | Nvt/Niet beoordeeld   | Nvt/Niet beoordeeld  | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld  | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld              | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | ja        | Lichamelijk handicap | ja                | ja         | nee             | nee       | GGZB             | GGZ01B      | ZB05         | nee             | ja         |
      |        2 | WLZ | 695870117 | nieuwe |            10 | Written       |    25-12-2023 | WzdRM         | BirthName   | NeverMarriedNorPartner | AtParents    | None                  | Permanent      | no           | no            | Dutch | yes                      | None                       | WettelijkeVertegenwoordiger | Curator           | None                 | None               | search data    | Dutch insurance | Bestaande Wlz-zorg stopzetten | nee        | nee        | nee        | n.v.t       | nee        | Beoordelen | Ja, face to face | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld   | Nvt/Niet beoordeeld   | Nvt/Niet beoordeeld  | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld  | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld              | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | ja        | Lichamelijk handicap | ja                | ja         | nee             | nee       | GGZB             | GGZ01B      | ZB05         | nee             | ja         |

  @request_WLZ_New_Client_test1_IBS
  Scenario Outline: Register and validate a new client in WLZ application
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "26-01-2022" voor index: "2" op tab: "1"
    When Fill in veld value: "roepnaam-baby-Test" voor index: "3" op tab: "1"
    When Fill in veld value: "baby-Test" voor index: "4" op tab: "1"
    When Fill in veld value: "van den" voor index: "5" op tab: "1"
    When Fill in veld value: "Baby test" voor index: "6" op tab: "1"
    When Fill in veld value: "BT" voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "<wettelijkeRelatie>" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "7-1-2025" voor index: "1" op tab: "1"
    Then Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    # Then Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "1"
    # Then Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "1"
    # Then Fill in veld value: "22-10-2023" voor index: "2" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Aanvrager onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgaanbieder onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgverantwoordelijke onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Wzd-functionaris onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Tweede belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    When Druk op zaak: "WZD-IBS" link voor: "<Scenario>" op tab: "1"
    Then Sla zaak met naam "WZD-IBS" voor: "<Scenario>" in filenaam: "request_WLZ_New_Client_test1_WZD_IBS.json" op tab: "2"

    Examples:
      | Scenario  | env | bsn       | klant  | geboortedatum | Aanvraagwijze | Aanvraagdatum | Aanvraagsoort | naamgebruik | burgerlijkeStaat       | leefSituatie | juridischeMaatregelen | verblijfStatus | geheimNummer | geheimNummer2 | taal  | telefonischeCommunicatie | bijzondereCommunicatieVorm | relatie                     | wettelijkeRelatie | partnerGeboorteDatum | woontOpZelfdeAdres | huisArtsClient | verzekering     | nieuwOfBestaandZorg           | zorgVraag1 | zorgVraag2 | zorgVraag3 | WZDversneld | checkboxes | stroom     | isIDVastgesteld  | orientatieStoornis  | psychischFunctioneren | motorischFunctioneren | psychoSociaalWelzijn | probleemGedrag      | verslavingsProblemen | socialeRaadZaamheid | mobiliteit          | persoonlijkeZorg    | huishoudelijkLeven  | socialeRelatiesEnMaatschappelijk | deelnameOnderwijs   | deelnameWerk        | grondslag | eersteGrondslag      | permanentToezicht | toegangWLZ | negatiefBesluit | opstarten | zorgProfielReeks | zorgProfiel | Besluitbrief | aanvragenReview | checkboxes |
      | 2-WZD-IBS | WLZ | 695870117 | nieuwe |            10 | Written       |    25-12-2023 | WzdIBS        | BirthName   | NeverMarriedNorPartner | AtParents    | None                  | Permanent      | no           | no            | Dutch | yes                      | None                       | WettelijkeVertegenwoordiger | Curator           | None                 | None               | search data    | Dutch insurance | Bestaande Wlz-zorg stopzetten | nee        | nee        | nee        | n.v.t       | nee        | Beoordelen | Ja, face to face | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld   | Nvt/Niet beoordeeld   | Nvt/Niet beoordeeld  | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld  | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld              | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | ja        | Lichamelijk handicap | ja                | ja         | nee             | nee       | GGZB             | GGZ01B      | ZB05         | nee             | ja         |
