Feature: This feature file is the same test as in request_BUK_New_Client.feature
The only difference is that in this test we include the checktext function(s).

  @request_BUK_New_Client_CheckText
  Scenario Outline: Register and validate a new client in BUK application
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automation@ciz.nl" en wachtwoord: "Welkom04!" op tab: "0"
    When Druk op type: "Button" met naam: "Aanvraag" met index: "0" op tab: "0"
    When Log in op pagina, met user: "test.automation@ciz.nl" en wachtwoord: "Welkom04!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    Then Status geupdate naar: "Nieuw" op tab: "1"
    Then Druk op type: "Button" met naam: "Stage progress" met index: "0" op tab: "1"
    Then Check Text naam: "Stel velden in nadat de case is gemaakt" op tab: "1"
    Then Check Text naam: "Aanmaken log zaak" op tab: "1"
    Then Check Text naam: "Aanmaken zaakfolder in CMIS" op tab: "1"
    Then Check Text naam: "Bijwerken SVB berichten" op tab: "1"
    Then Check Text naam: "Registratie" op tab: "1"
    Then Check Text naam: "Afronden Migratie" op tab: "1"
    Then Check Text naam: "Valideren cliënt" op tab: "1"
    Then Check Text naam: "In behandeling" op tab: "1"
    Then Check Text naam: "Selecteren cliënt titel" op tab: "1"
    Then Check Text naam: "Zoeken cliënt" op tab: "1"
    Then Check Text naam: "Gevonden cliënten" op tab: "1"
    Then Check Text naam: "Wissen zoekcriteria knop" op tab: "1"
    Then Check Text naam: "Zoek cliënt knop" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Doorgaan knop" op tab: "1"
    Then Check Text naam: "Burgerservicenummer (BSN)" op tab: "1"
    Then Check Text naam: "Cliëntnummer" op tab: "1"
    # Then Check Text naam: "Geboortenaam" op tab: "1"
    Then Check Text naam: "Geboortedatum" op tab: "1"
    Then Check Text naam: "Land" op tab: "1"
    Then Check Text naam: "Postcode" op tab: "1"
    Then Check Text naam: "Huisnummer" op tab: "1"
    Then Check Text naam: "Geslacht Selecteren cliënt" op tab: "1"
    Then Check Text naam: "Naam en voorletters resultaat" op tab: "1"
    Then Check Text naam: "Geboortedatum resultaat" op tab: "1"
    Then Check Text naam: "Geslacht resultaat" op tab: "1"
    Then Check Text naam: "Burgerservicenummer (BSN) resultaat" op tab: "1"
    Then Check Text naam: "Cliëntnummer resultaat" op tab: "1"
    Then Check Text naam: "Postcode en huisnummer resultaat" op tab: "1"
    Then Check Text naam: "Plaats" op tab: "1"
    Then Check Text naam: "Geen bestaande cliënten gevonden, pas de zoekcriteria aan of start aanvraag voor nieuwe cliënt." op tab: "1"
    Then Check Text naam: "Aanvraag creëren met een nieuwe cliënt" op tab: "1"
    When Vul bsn "<bsn>" voor een "<klant>" klant op tab: "1"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Registreren aanvraaggegevens Aanvraagwijze: "<Aanvraagwijze>" Aanvraagdatum: "<Aanvraagdatum>" Aanvraagsoort: "<Aanvraagsoort>" op tab: "1"
    When Vul BUK informatie in met: "<Aanvraagsoort>" ouder toestemming: "<ouderToestemming>" op tab: "1"
    Then Check Text naam: "Registreren aanvraaggegevens titel" op tab: "1"
    Then Check Text naam: "Aanvraagsoort sectie" op tab: "1"
    Then Check Text naam: "Zorgvraag sectie" op tab: "1"
    # Then Check Text naam: "Geboortedatum cliënt" op tab: "1"
    # Then Check Text naam: "Leeftijd" op tab: "1"
    Then Check Text naam: "Aanvraagwijze" op tab: "1"
    Then Check Text naam: "Aanvraagdatum" op tab: "1"
    Then Check Text naam: "Aanvraagsoort" op tab: "1"
    Then Check Text naam: "Registratienummer SVB" op tab: "1"
    Then Check Text naam: "Geeft de aanvragende ouder toestemming om indien aanwezig het cliëntendossier in te zien?" op tab: "1"
    Then Check Text naam: "Toesteming Antwoord Ja" op tab: "1"
    Then Check Text naam: "Toesteming Antwoord Nee" op tab: "1"
    Then Check Text naam: "Zorgvraag" op tab: "1"
    Then Check Text naam: "Tekstsbox max. karakter" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Doorgaan knop" op tab: "1"
    Then Check Text naam: "Terug knop" op tab: "1"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Check Text naam: "Persoonlijk titel" op tab: "1"
    Then Check Text naam: "Geheim persoon" op tab: "1"
    Then Check Text naam: "Speciaal onderzoek" op tab: "1"
    Then Check Text naam: "onderzoek antwoord Ja" op tab: "1"
    Then Check Text naam: "Onderzoek antwoord Nee" op tab: "1"
    Then Check Text naam: "Burgerservicenummer (BSN) persoonlijk" op tab: "1"
    Then Check Text naam: "Geboortedatum persoonlijk" op tab: "1"
    Then Check Text naam: "Roepnaam" op tab: "1"
    Then Check Text naam: "Geboortenaam persoonlijk" op tab: "1"
    Then Check Text naam: "Voorvoegsel" op tab: "1"
    Then Check Text naam: "Voornamen" op tab: "1"
    Then Check Text naam: "Voorletter(s)" op tab: "1"
    Then Check Text naam: "Geslacht Persoonlijk" op tab: "1"
    Then Check Text naam: "Overlijdensdatum" op tab: "1"
    Then Check Text naam: "Naamgebruik" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Doorgaan knop" op tab: "1"
    Then Check Text naam: "Terug knop" op tab: "1"
    When Vul in Persoonlijke informatie:leeftijd "<geboortedatum>" geheim persoon: "<geheimPersoon>" speciaal onderzoek: "<speciaalOnderzoek>" geboortedatum: "<geboortedatum>" naamgebruik: "<naamgebruik>" op tab: "1"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Check Text naam: "Aanvullend Persoonlijk titel" op tab: "1"
    Then Check Text naam: "Burgerlijke staat" op tab: "1"
    Then Check Text naam: "Leefsituatie" op tab: "1"
    Then Check Text naam: "Juridische maatregelen" op tab: "1"
    Then Check Text naam: "Verblijfsstatus (alleen invullen als de cliënt niet de Nederlandse nationaliteit heeft)" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Doorgaan knop" op tab: "1"
    Then Check Text naam: "Terug knop" op tab: "1"
    When Aanvullend persoonlijk gegevens: burgerlijke staat "<burgerlijkeStaat>" leefsituatie: "<leefSituatie>" juridische maatregelen "<juridischeMaatregelen>" verblijfstatus "<verblijfStatus>" op tab: "1"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When vul in contact gegevens Geheim nummer: "<geheimNummer>" Geheim nummer2: "<geheimNummer2>" taal: "<taal>" telefonische communicatie: "<telefonischeCommunicatie>" bijzondere communicatievorm: "<bijzondereCommunicatieVorm>" op tab: "1"
    Then Check Text naam: "Contact titel" op tab: "1"
    Then Check Text naam: "1e Telefoonnummer vraag" op tab: "1"
    Then Check Text naam: "1e Landnummer" op tab: "1"
    Then Check Text naam: "1e Telefoonnummer" op tab: "1"
    Then Check Text naam: "1e Geheim nummer" op tab: "1"
    Then Check Text naam: "2e Telefoonnummer vraag" op tab: "1"
    Then Check Text naam: "2e Landnummer" op tab: "1"
    Then Check Text naam: "2e Telefoonnummer" op tab: "1"
    Then Check Text naam: "2e Geheim nummer" op tab: "1"
    Then Check Text naam: "E-mailadres" op tab: "1"
    Then Check Text naam: "Taal" op tab: "1"
    Then Check Text naam: "Is de cliënt in staat tot telefonische communicatie" op tab: "1"
    Then Check Text naam: "communicatie antwoord Ja" op tab: "1"
    Then Check Text naam: "communicatie andtwoord Nee" op tab: "1"
    Then Check Text naam: "Bijzondere communicatievorm" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Doorgaan knop" op tab: "1"
    Then Check Text naam: "Terug knop" op tab: "1"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Check Text naam: "Relatie titel knop" op tab: "1"
    Then Check Text naam: "Relatie toevoegen knop" op tab: "1"
    Then Check Text naam: "Relatie wijzigen knop" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Doorgaan knop" op tab: "1"
    Then Check Text naam: "Terug knop" op tab: "1"
    Then Druk op type: "Button" met naam: "Relatie toevoegen" met index: "0" op tab: "1"
    Then Check Text naam: "Relatie toevoegen popup titel" op tab: "1"
    Then Check Text naam: "Type relatie" op tab: "1"
    Then Check Text naam: "Wettelijke relatie" op tab: "1"
    Then Check Text naam: "Curator" op tab: "1"
    Then Check Text naam: "Mentor" op tab: "1"
    Then Check Text naam: "Ouder met gezag" op tab: "1"
    Then Check Text naam: "(notarieel) Gemachtigde" op tab: "1"
    Then Check Text naam: "Geboortenaam" op tab: "1"
    Then Check Text naam: "Voorvoegsel" op tab: "1"
    Then Check Text naam: "Voorletter(s)" op tab: "1"
    Then Check Text naam: "1e Landnummer" op tab: "1"
    Then Check Text naam: "1e Telefoonnummer" op tab: "1"
    Then Check Text naam: "2e Landnummer" op tab: "1"
    Then Check Text naam: "2e Telefoonnummer" op tab: "1"
    Then Check Text naam: "E-mailadres relatie" op tab: "1"
    Then Check Text naam: "Indienen knop" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    When vul in relaties: leeftijd "<geboortedatum>" type relatie:"<relatie>" wettelijke relatie: "<wettelijkeRelatie>" partner geboortedatum: "<partnerGeboorteDatum>" woont op zelfde adres: "<woontOpZelfdeAdres>" op tab: "1"
    Then Druk op type: "Button" met naam: "Indienen" met index: "0" op tab: "1"
    # Then Check Text naam: "Type relatie" op tab: "1"
    Then Check Text naam: "Wettelijke relatie" op tab: "1"
    Then Check Text naam: "Geboortenaam" op tab: "1"
    Then Check Text naam: "Voorvoegsel" op tab: "1"
    Then Check Text naam: "Voorletter(s)" op tab: "1"
    Then Check Text naam: "1e Landnummer" op tab: "1"
    Then Check Text naam: "1e Telefoonnummer" op tab: "1"
    Then Check Text naam: "2e Landnummer" op tab: "1"
    Then Check Text naam: "2e Telefoonnummer" op tab: "1"
    Then Check Text naam: "E-mailadres relatie" op tab: "1"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Check Text naam: "Adressen titel" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres header" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres checkbox" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres header" op tab: "1"
    Then Check Text naam: "Afwijkend tijdelijke Verblijfadres checkbox" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - land" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Postcode" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Huisnummer" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Huisletter" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Toevoeging huisnummer" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Huisnummeraanduiding" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Zoek knop" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Straat" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Plaats" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Kamer" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Opmerking" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Doorgaan knop" op tab: "1"
    Then Check Text naam: "Terug knop" op tab: "1"
    When Vul in Adressen: relatie: "<relatie>" op tab: "1"
    When Vul in correspondentie adressen "<geboortedatum>" op tab "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Relatie tot cliënt" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Toelichting" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - land" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Postcode" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Huisnummer" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Huisletter" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Toevoeging huisnummer" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Huisnummeraanduiding" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Zoek knop" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Straat" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Plaats" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Kamer" op tab: "1"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Check Text naam: "Indienen titel" op tab: "1"
    Then Check Text naam: "Geboortedatum cliënt" op tab: "1"
    Then Check Text naam: "Leeftijd" op tab: "1"
    Then Check Text naam: "Aanvraagwijze" op tab: "1"
    Then Check Text naam: "Aanvraagdatum" op tab: "1"
    Then Check Text naam: "Aanvraagsoort" op tab: "1"
    Then Check Text naam: "Registratienummer SVB" op tab: "1"
    Then Check Text naam: "Geeft de aanvragende ouder toestemming om indien aanwezig het cliëntendossier in te zien?" op tab: "1"
    Then Check Text naam: "Zorgvraag" op tab: "1"
    Then Check Text naam: "Geheim persoon" op tab: "1"
    Then Check Text naam: "Speciaal onderzoek" op tab: "1"
    Then Check Text naam: "Burgerservicenummer (BSN) persoonlijk" op tab: "1"
    Then Check Text naam: "Geboortedatum persoonlijk" op tab: "1"
    Then Check Text naam: "Roepnaam" op tab: "1"
    Then Check Text naam: "Geboortenaam" op tab: "1"
    Then Check Text naam: "Voorvoegsel" op tab: "1"
    Then Check Text naam: "Voornamen" op tab: "1"
    Then Check Text naam: "Voorletter(s)" op tab: "1"
    Then Check Text naam: "Geslacht Persoonlijk" op tab: "1"
    Then Check Text naam: "Overlijdensdatum" op tab: "1"
    Then Check Text naam: "Naamgebruik" op tab: "1"
    Then Check Text naam: "Burgerlijke staat" op tab: "1"
    Then Check Text naam: "Leefsituatie" op tab: "1"
    Then Check Text naam: "Juridische maatregelen" op tab: "1"
    Then Check Text naam: "Verblijfsstatus (alleen invullen als de cliënt niet de Nederlandse nationaliteit heeft)" op tab: "1"
    Then Check Text naam: "1e Landnummer" op tab: "1"
    Then Check Text naam: "1e Telefoonnummer" op tab: "1"
    Then Check Text naam: "1e Geheim nummer" op tab: "1"
    Then Check Text naam: "2e Landnummer" op tab: "1"
    Then Check Text naam: "2e Telefoonnummer" op tab: "1"
    Then Check Text naam: "2e Geheim nummer" op tab: "1"
    Then Check Text naam: "E-mailadres" op tab: "1"
    Then Check Text naam: "Taal" op tab: "1"
    Then Check Text naam: "Is de cliënt in staat tot telefonische communicatie" op tab: "1"
    Then Check Text naam: "Bijzondere communicatievorm" op tab: "1"
    # Then Check Text naam: "Type relatie" op tab: "1"
    Then Check Text naam: "Wettelijke relatie" op tab: "1"
    Then Check Text naam: "Geboortenaam" op tab: "1"
    Then Check Text naam: "Voorvoegsel" op tab: "1"
    Then Check Text naam: "Voorletter(s)" op tab: "1"
    Then Check Text naam: "1e Landnummer" op tab: "1"
    Then Check Text naam: "1e Telefoonnummer" op tab: "1"
    Then Check Text naam: "2e Landnummer" op tab: "1"
    Then Check Text naam: "2e Telefoonnummer" op tab: "1"
    Then Check Text naam: "E-mailadres relatie" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - land" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Postcode" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Huisnummer" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Huisletter" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Toevoeging huisnummer" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Huisnummeraanduiding" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Straat" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Plaats" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Kamer" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Opmerking" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Relatie tot cliënt" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - land" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Postcode" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Huisnummer" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Huisletter" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Toevoeging huisnummer" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Huisnummeraanduiding" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Straat" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Plaats" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Kamer" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Aanmaken knop" op tab: "1"
    Then Check Text naam: "Terug knop" op tab: "1"
    Then Druk op type: "Button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op: "BA" zaak link op tab: "1"
    When Log in op pagina, met user: "test.automation@ciz.nl" en wachtwoord: "Welkom04!" op tab: "2"
    # Then Status geupdate naar: "Open - Validatie" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Urgentie" op tab: "2"
    # Then Check Text naam: "Samenvatting Paneel - Status" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Wettelijke uiterste beslisdatum - Datum" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Wettelijke uiterste beslisdatum - WRD" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Wettelijke uiterste beslisdatum - Kalenderdagen" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Interne uiterste beslisdatum - Datum" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Interne uiterste beslisdatum - GRD" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Interne uiterste beslisdatum - Kalenderdagen" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Naam" op tab: "2"
    # Then Check Text naam: "Samenvatting Paneel - Geboortedatum" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - BSN" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Cliëntnummer" op tab: "2"
    # Then Check Text naam: "Samenvatting Paneel - Wettelijk vertegenw." op tab: "2"
    # Then Check Text naam: "Samenvatting Paneel - Tel." op tab: "2"    Na sanity weer checken
    # Then Check Text naam: "Samenvatting Paneel - Email" op tab: "2"
    # Then Check Text naam: "Samenvatting Paneel - Huidig kwartaal" op tab: "2"
    # Then Check Text naam: "Samenvatting Paneel - Volgend kwartaal" op tab: "2"
    # Then Check Text naam: "Samenvatting Paneel - Bekend binnen Wlz" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Zaakgegevens" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Ingediende aanvraag" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Bijbehorende zaken" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Notities" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Documenten" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Medische historie" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Contactmomenten" op tab: "2"
    Then Druk op type: "Button" met naam: "Ga" met index: "0" op tab: "2"
    When Informatie is binnengekomen na opvragen en rappel "<infoRappel>", tab "2"
    Then Check Text naam: "Triage uitvoeren titel" op tab: "2"
    Then Check Text naam: "Geldig Wlz besluit" op tab: "2"
    Then Check Text naam: "Geldig Wlz besluit - Ja" op tab: "2"
    Then Check Text naam: "Geldig Wlz besluit - Nee" op tab: "2"
    Then Check Text naam: "Geldig Wlz besluit - Geen toestemming" op tab: "2"
    Then Check Text naam: "Geldig BUK advies" op tab: "2"
    Then Check Text naam: "Geldig BUK advies - Ja" op tab: "2"
    Then Check Text naam: "Geldig BUK advies - Nee" op tab: "2"
    Then Check Text naam: "Lopende BUK aanvraag" op tab: "2"
    Then Check Text naam: "Lopende BUK aanvraag - Ja" op tab: "2"
    Then Check Text naam: "Lopende BUK aanvraag - Nee" op tab: "2"
    # Then Check Text naam: "Overzicht BUK aanvragen" op tab: "2"
    Then Check Text naam: "Overzicht BUK aanvragen - Zaak" op tab: "2"
    Then Check Text naam: "Overzicht BUK aanvragen - Aanvraagdatum" op tab: "2"
    Then Check Text naam: "Overzicht BUK aanvragen - Status" op tab: "2"
    Then Check Text naam: "Ook huisgenoten" op tab: "2"
    Then Check Text naam: "Uitkomst" op tab: "2"
    Then Check Text naam: "Afwijken" op tab: "2"
    # Then Check Text naam: "Annuleren knop" op tab: "2"
    Then Check Text naam: "Indienen knop" op tab: "2"
    Then Check Text naam: "Opslaan knop" op tab: "2"
    Then Druk op type: "Button" met naam: "Indienen" met index: "0" op tab: "2"

    Examples:
      | Scenario | env | bsn       | klant  | Aanvraagwijze | Aanvraagdatum | Aanvraagsoort | nieuwAdvies | ouderToestemming | geheimPersoon | speciaalOnderzoek | geboortedatum | partnerGeboorteDatum | naamgebruik | burgerlijkeStaat       | leefSituatie | juridischeMaatregelen | verblijfStatus | geheimNummer | geheimNummer2 | taal     | telefonischeCommunicatie | bijzondereCommunicatieVorm | relatie                     | wettelijkeRelatie       | woontOpZelfdeAdres | infoRappel |
      |        1 | BUK | 654442484 | nieuwe | E-Mail        |    12-10-2023 | Advice        | None        | ja               | no            | yes               |             4 | none                 | BirthName   | NeverMarriedNorPartner | CareInstance | RMProvisional         | Gedoogd        | no           | yes           | Moroccan | no                       | DeafInterpreter            | WettelijkeVertegenwoordiger | (notarieel) Gemachtigde | None               | nee        |
