Feature: CheckText van Klachten: werklijsten + werkbakken + routing

  @request_Klacht_CheckText
  Scenario Outline: Klacht zaak wordt gerouteerd naar de juiste medewerker(klacht WEL in behandeling nemen en geescaleerd)test3
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automation@ciz.nl" en wachtwoord: "Welkom04!" op tab: "0"
    When Druk op type: "Button" met naam: "Aanvraag" met index: "0" op tab: "0"
    When Log in op pagina, met user: "test.automation@ciz.nl" en wachtwoord: "Welkom04!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    Then Status geupdate naar: "Nieuw" op tab: "1"
    Then Check Text naam: "Indienen klacht titel" op tab: "1"
    # Then Check Text naam: "Standaard informatie" op tab: "1"
    Then Check Text naam: "Cliënt" op tab: "1"
    Then Check Text naam: "Zaak" op tab: "1"
    Then Check Text naam: "Ontvangstdatum" op tab: "1"
    Then Check Text naam: "Wijze van binnenkomst" op tab: "1"
    # Then Check Text naam: "Gegevens klager" op tab: "1"
    Then Check Text naam: "Dient de cliënt de klacht in?" op tab: "1"
    Then Check Text naam: "Dient de cliënt de klacht in? - Ja" op tab: "1"
    Then Check Text naam: "Dient de cliënt de klacht in? - Nee" op tab: "1"
    # Then Check Text naam: "E-mailadres" op tab: "1"
    # Then Check Text naam: "1e Telefoonnummer vraag" op tab: "1"
    # Then Check Text naam: "1e Landnummer" op tab: "1"
    Then Check Text naam: "Bereikbaarheid" op tab: "1"
    # Then Check Text naam: "Gegevens klacht" op tab: "1"
    Then Check Text naam: "Klacht gericht op:" op tab: "1"
    Then Check Text naam: "Soort klacht" op tab: "1"
    Then Check Text naam: "Omschrijving van de klacht en gewenste oplossing" op tab: "1"
    Then Check Text naam: "Stel" op tab: "1"
    # Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Indienen knop" op tab: "1"
    Then Check Text naam: "Opslaan knop" op tab: "1"
    When Selecteer klant "CP-GC-51002" en zaak "REQ-BUK-129004" op tab: "1"
    When Vul ontvangsdatum in op tab: "1"
    When Selecteer wijze van binnenkomst "<wijzeVanBinnenkomst>" op tab: "1"
    When Dient de cliënt de klacht in "<dientDeKlantDeKlachtIn>" op tab: "1"
    Then klant dient klacht in "<dientDeKlantDeKlachtIn>" adres mag niet leeg zijn op tab: "1"
    When Klacht gericht op "<klachtGerichtOp>" op tab: "1"
    Then klacht op "<klachtGerichtOp>" veld naam medewerker "<naamMedewerker>" op tab: "1"
    When Soort klacht "<soortKlacht>" op tab: "1"
    When Omschrijving van de klacht en gewenste oplossing op tab: "1"
    Then Druk op type: "Button" met naam: "Indienen" met index: "0" op tab: "1"
    # Then Status geupdate naar: "Open - In behandeling" op tab: "1"
    When Druk op: "<Zaak>" zaak link op tab: "1"
    When Log in op pagina, met user: "test.automation@ciz.nl" en wachtwoord: "Welkom04!" op tab: "2"
    Then Druk op type: "Button" met naam: "Ga" met index: "0" op tab: "2"
    Then Check Text naam: "In behandeling nemen titel" op tab: "2"
    Then Check Text naam: "Klacht in behandeling nemen?" op tab: "2"
    Then Check Text naam: "Klacht in behandeling nemen? - Ja" op tab: "2"
    Then Check Text naam: "Klacht in behandeling nemen? - Nee" op tab: "2"
    # Then Check Text naam: "Toelichting" op tab: "2"  >>>>>>>>>>>>>>>>>>>>>>>> Different data-test-id
    # Then Check Text naam: "Annuleren knop" op tab: "2"
    Then Check Text naam: "Indienen knop" op tab: "2"
    Then Check Text naam: "Opslaan knop" op tab: "2"
    When Klacht in behandeling nemen "<klachtInBehandelingNemen>" op tab: "2"
    Then Klacht niet in behandeling nemen "<klachtInBehandelingNemen>" reden wordt getoond op tab: "2"
    Then Status geupdate naar: "Open - In behandeling" op tab: "2"
    When Vul een toelichting in "primair" op tab: "2"
    Then Druk op type: "Button" met naam: "Indienen" met index: "0" op tab: "2"
    When Verslaglegging contact met de klager "primair" op tab: "2"
    When Klacht naar tevredenheid afgehandeld? "<klachtNaarTevredenheidAfgehandeld_primair>" op tab: "2"
    When Leerpunt voor CIZ "primair" op tab: "2"
    Then Check Text naam: "Afhandelen stap 1: het informele gesprek titel" op tab: "2"
    Then Check Text naam: "Datum toevoegen" op tab: "2"
    Then Check Text naam: "Verslaglegging contact met de klager" op tab: "2"
    Then Check Text naam: "Klacht naar tevredenheid afgehandeld?" op tab: "2"
    Then Check Text naam: "Klacht naar tevredenheid afgehandeld? - Ja" op tab: "2"
    Then Check Text naam: "Klacht naar tevredenheid afgehandeld? - Nee" op tab: "2"
    Then Check Text naam: "Leerpunt voor CIZ" op tab: "2"
    Then Check Text naam: "Versturen via" op tab: "2"
    Then Check Text naam: "Versturen via - Email" op tab: "2"
    Then Check Text naam: "Versturen via - Post" op tab: "2"
    # Then Check Text naam: "Annuleren knop" op tab: "2"
    Then Check Text naam: "Indienen knop" op tab: "2"
    Then Check Text naam: "Opslaan knop" op tab: "2"
    Then Druk op type: "Button" met naam: "Indienen" met index: "0" op tab: "2"
    When Verslaglegging contact met de klager "geescaleerd" op tab: "2"
    When Wijze van afhandelen "Telefonisch contact" op tab: "2"
    When Klacht naar tevredenheid afgehandeld? "<klachtNaarTevredenheidAfgehandeld_geescaleerd>" op tab: "2"
    When Leerpunt voor CIZ "geescaleerd" op tab: "2"
    When Klager heeft aangegeven zich tot de nationale ombudsman te wenden "<nationaleOmbudsman>" op tab: "2"
    Then Status geupdate naar: "Open - In behandeling" op tab: "2"
    Then Druk op: "dossier" zaak link op tab: "2"
    Then Status geupdate naar: "Open - In behandeling" op tab: "3"

    Examples:
      | Scenario | env    | wijzeVanBinnenkomst | dientDeKlantDeKlachtIn | klachtGerichtOp | naamMedewerker   | soortKlacht | Zaak  | klachtInBehandelingNemen | klachtNaarTevredenheidAfgehandeld_primair | klachtNaarTevredenheidAfgehandeld_geescaleerd | nationaleOmbudsman |
      |        1 | klacht | Website             | ja                     | CIZ             | niet beschikbaar | Datalek     | BUK-K | ja                       | nee                                       | nee geescaleerd                               | ja                 |
