Feature: This feature file is the same test as in request_BUK_Existing_Client.feature
The only difference is that in this test we include the checktext function(s).

  @Buk_existingClient_CheckText_1
  Scenario Outline: Register and validate a existing client in BUK application and checktext
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automation@ciz.nl" en wachtwoord: "Welkom04!" op tab: "0"
    When Druk op type: "Button" met naam: "Aanvraag" met index: "0" op tab: "0"
    When Log in op pagina, met user: "test.automation@ciz.nl" en wachtwoord: "Welkom04!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    Then Druk op type: "Button" met naam: "Stage progress" met index: "0" op tab: "1"
    Then Check Text naam: "Stel velden in nadat de case is gemaakt" op tab: "1"
    Then Check Text naam: "Aanmaken log zaak" op tab: "1"
    Then Check Text naam: "Aanmaken zaakfolder in CMIS" op tab: "1"
    Then Check Text naam: "Bijwerken SVB berichten" op tab: "1"
    Then Check Text naam: "Registratie" op tab: "1"
    Then Check Text naam: "Afronden Migratie" op tab: "1"
    Then Check Text naam: "Valideren cliënt" op tab: "1"
    Then Check Text naam: "In behandeling" op tab: "1"
    Then Check Text naam: "Selecteren cliënt titel" op tab: "1"
    Then Check Text naam: "Zoeken cliënt" op tab: "1"
    Then Check Text naam: "Gevonden cliënten" op tab: "1"
    Then Check Text naam: "Wis zoekcriteria knop" op tab: "1"
    Then Check Text naam: "Zoek cliënt knop" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Doorgaan knop" op tab: "1"
    Then Check Text naam: "Burgerservicenummer (BSN)" op tab: "1"
    Then Check Text naam: "Cliëntnummer" op tab: "1"
    Then Check Text naam: "Geboortenaam" op tab: "1"
    Then Check Text naam: "Geboortedatum" op tab: "1"
    Then Check Text naam: "Land" op tab: "1"
    Then Check Text naam: "Postcode" op tab: "1"
    Then Check Text naam: "Huisnummer" op tab: "1"
    Then Check Text naam: "Geslacht Selecteren cliënt" op tab: "1"
    Then Check Text naam: "Naam en voorletters resultaat" op tab: "1"
    Then Check Text naam: "Geboortedatum resultaat" op tab: "1"
    Then Check Text naam: "Geslacht resultaat" op tab: "1"
    Then Check Text naam: "Burgerservicenummer (BSN) resultaat" op tab: "1"
    Then Check Text naam: "Cliëntnummer resultaat" op tab: "1"
    Then Check Text naam: "Postcode en huisnummer resultaat" op tab: "1"
    Then Check Text naam: "Plaats" op tab: "1"
    Then Check Text naam: "Geen bestaande cliënten gevonden, pas de zoekcriteria aan of start aanvraag voor nieuwe cliënt." op tab: "1"
    Then Check Text naam: "Aanvraag creëren met een nieuwe cliënt" op tab: "1"
    When Vul bsn "<bsn>" voor een "<klant>" klant op tab: "1"
    When Klik op selecteren klant op tab: "1"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Registreren aanvraaggegevens Aanvraagwijze: "<Aanvraagwijze>" Aanvraagdatum: "<Aanvraagdatum>" Aanvraagsoort: "<Aanvraagsoort>" op tab: "1"
    When Vul BUK informatie in met: "<Aanvraagsoort>" ouder toestemming: "<ouderToestemming>" op tab: "1"
    When Druk op zaak: "<zaak>" link voor: "<Scenario>" sla op met filenaam: "Buk_existingClient_Test_1.json" op tab: "1"
    Then Check Text naam: "Registreren aanvraaggegevens titel" op tab: "1"
    Then Check Text naam: "Aanvraagsoort sectie" op tab: "1"
    Then Check Text naam: "Zorgvraag sectie" op tab: "1"
    # Then Check Text naam: "Geboortedatum cliënt" op tab: "1"
    # Then Check Text naam: "Leeftijd" op tab: "1"
    Then Check Text naam: "Aanvraagwijze" op tab: "1"
    Then Check Text naam: "Aanvraagdatum" op tab: "1"
    Then Check Text naam: "Aanvraagsoort" op tab: "1"
    Then Check Text naam: "Registratienummer SVB" op tab: "1"
    Then Check Text naam: "Geeft de aanvragende ouder toestemming om indien aanwezig het cliëntendossier in te zien?" op tab: "1"
    Then Check Text naam: "Toesteming Antwoord Ja" op tab: "1"
    Then Check Text naam: "Toesteming Antwoord Nee" op tab: "1"
    Then Check Text naam: "Advies waartegen bezwaar wordt gemaakt" op tab: "1"
    Then Check Text naam: "Zorgvraag" op tab: "1"
    Then Check Text naam: "Tekstsbox max. karakter" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Doorgaan knop" op tab: "1"
    Then Check Text naam: "Terug knop" op tab: "1"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Check Text naam: "Persoonlijk titel" op tab: "1"
    Then Check Text naam: "Geheim persoon" op tab: "1"
    Then Check Text naam: "Speciaal onderzoek" op tab: "1"
    Then Check Text naam: "onderzoek antwoord Ja" op tab: "1"
    Then Check Text naam: "Onderzoek antwoord Nee" op tab: "1"
    Then Check Text naam: "Burgerservicenummer (BSN) persoonlijk" op tab: "1"
    Then Check Text naam: "Geboortedatum persoonlijk" op tab: "1"
    Then Check Text naam: "Roepnaam" op tab: "1"
    Then Check Text naam: "Geboortenaam persoonlijk" op tab: "1"
    Then Check Text naam: "Voorvoegsel" op tab: "1"
    Then Check Text naam: "Voornamen" op tab: "1"
    Then Check Text naam: "Voorletter(s)" op tab: "1"
    Then Check Text naam: "Geslacht Persoonlijk" op tab: "1"
    Then Check Text naam: "Overlijdensdatum" op tab: "1"
    Then Check Text naam: "Naamgebruik" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Doorgaan knop" op tab: "1"
    Then Check Text naam: "Terug knop" op tab: "1"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Check Text naam: "Aanvullend Persoonlijk titel" op tab: "1"
    Then Check Text naam: "Burgerlijke staat" op tab: "1"
    Then Check Text naam: "Leefsituatie" op tab: "1"
    Then Check Text naam: "Juridische maatregelen" op tab: "1"
    Then Check Text naam: "Verblijfsstatus (alleen invullen als de cliënt niet de Nederlandse nationaliteit heeft)" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Doorgaan knop" op tab: "1"
    Then Check Text naam: "Terug knop" op tab: "1"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Check Text naam: "Contact titel" op tab: "1"
    Then Check Text naam: "1e Telefoonnummer vraag" op tab: "1"
    Then Check Text naam: "1e Landnummer" op tab: "1"
    Then Check Text naam: "1e Telefoonnummer" op tab: "1"
    Then Check Text naam: "1e Geheim nummer" op tab: "1"
    Then Check Text naam: "2e Telefoonnummer vraag" op tab: "1"
    Then Check Text naam: "2e Landnummer" op tab: "1"
    Then Check Text naam: "2e Telefoonnummer" op tab: "1"
    Then Check Text naam: "2e Geheim nummer" op tab: "1"
    Then Check Text naam: "E-mailadres" op tab: "1"
    Then Check Text naam: "Taal" op tab: "1"
    Then Check Text naam: "Is de cliënt in staat tot telefonische communicatie" op tab: "1"
    Then Check Text naam: "communicatie antwoord Ja" op tab: "1"
    Then Check Text naam: "communicatie andtwoord Nee" op tab: "1"
    Then Check Text naam: "Bijzondere communicatievorm" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Doorgaan knop" op tab: "1"
    Then Check Text naam: "Terug knop" op tab: "1"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Check Text naam: "Type relatie" op tab: "1"
    Then Check Text naam: "Wettelijke relatie" op tab: "1"
    Then Check Text naam: "Geboortenaam" op tab: "1"
    Then Check Text naam: "Voorvoegsel" op tab: "1"
    Then Check Text naam: "Voorletter(s)" op tab: "1"
    Then Check Text naam: "1e Landnummer" op tab: "1"
    Then Check Text naam: "1e Telefoonnummer" op tab: "1"
    Then Check Text naam: "2e Landnummer" op tab: "1"
    Then Check Text naam: "2e Telefoonnummer" op tab: "1"
    Then Check Text naam: "E-mailadres relatie" op tab: "1"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Check Text naam: "Adressen titel" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres header" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres checkbox" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres header" op tab: "1"
    Then Check Text naam: "Afwijkend tijdelijke Verblijfadres checkbox" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - land" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Postcode" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Huisnummer" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Huisletter" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Huisnummeraanduiding" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Zoek knop" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Straat" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Plaats" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Kamer" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Opmerking" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Doorgaan knop" op tab: "1"
    Then Check Text naam: "Terug knop" op tab: "1"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Check Text naam: "Indienen titel" op tab: "1"
    Then Check Text naam: "Geboortedatum cliënt" op tab: "1"
    Then Check Text naam: "Leeftijd" op tab: "1"
    Then Check Text naam: "Aanvraagwijze" op tab: "1"
    Then Check Text naam: "Aanvraagdatum" op tab: "1"
    Then Check Text naam: "Aanvraagsoort" op tab: "1"
    Then Check Text naam: "Registratienummer SVB" op tab: "1"
    Then Check Text naam: "Geeft de aanvragende ouder toestemming om indien aanwezig het cliëntendossier in te zien?" op tab: "1"
    Then Check Text naam: "Zorgvraag" op tab: "1"
    Then Check Text naam: "Geheim persoon" op tab: "1"
    Then Check Text naam: "Speciaal onderzoek" op tab: "1"
    Then Check Text naam: "Burgerservicenummer (BSN) persoonlijk" op tab: "1"
    Then Check Text naam: "Geboortedatum persoonlijk" op tab: "1"
    Then Check Text naam: "Roepnaam" op tab: "1"
    Then Check Text naam: "Geboortenaam" op tab: "1"
    Then Check Text naam: "Voorvoegsel" op tab: "1"
    Then Check Text naam: "Voornamen" op tab: "1"
    Then Check Text naam: "Voorletter(s)" op tab: "1"
    Then Check Text naam: "Geslacht Persoonlijk" op tab: "1"
    Then Check Text naam: "Overlijdensdatum" op tab: "1"
    Then Check Text naam: "Naamgebruik" op tab: "1"
    Then Check Text naam: "Burgerlijke staat" op tab: "1"
    Then Check Text naam: "Leefsituatie" op tab: "1"
    Then Check Text naam: "Juridische maatregelen" op tab: "1"
    Then Check Text naam: "Verblijfsstatus (alleen invullen als de cliënt niet de Nederlandse nationaliteit heeft)" op tab: "1"
    Then Check Text naam: "1e Landnummer" op tab: "1"
    Then Check Text naam: "1e Telefoonnummer" op tab: "1"
    Then Check Text naam: "1e Geheim nummer" op tab: "1"
    Then Check Text naam: "2e Landnummer" op tab: "1"
    Then Check Text naam: "2e Telefoonnummer" op tab: "1"
    Then Check Text naam: "2e Geheim nummer" op tab: "1"
    Then Check Text naam: "E-mailadres" op tab: "1"
    Then Check Text naam: "Taal" op tab: "1"
    Then Check Text naam: "Is de cliënt in staat tot telefonische communicatie" op tab: "1"
    Then Check Text naam: "Bijzondere communicatievorm" op tab: "1"
    # Then Check Text naam: "Type relatie" op tab: "1"
    Then Check Text naam: "Wettelijke relatie" op tab: "1"
    Then Check Text naam: "Geboortenaam" op tab: "1"
    Then Check Text naam: "Voorvoegsel" op tab: "1"
    Then Check Text naam: "Voorletter(s)" op tab: "1"
    Then Check Text naam: "1e Landnummer" op tab: "1"
    Then Check Text naam: "1e Telefoonnummer" op tab: "1"
    Then Check Text naam: "2e Landnummer" op tab: "1"
    Then Check Text naam: "2e Telefoonnummer" op tab: "1"
    Then Check Text naam: "E-mailadres relatie" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - land" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Postcode" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Huisnummer" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Huisletter" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Huisnummeraanduiding" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Straat" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Plaats" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Kamer" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Opmerking" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Relatie tot cliënt" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - land" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Postcode" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Huisnummer" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Huisletter" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Toevoeging huisnummer" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Huisnummeraanduiding" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Straat" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Plaats" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Kamer" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Aanmaken knop" op tab: "1"
    Then Check Text naam: "Terug knop" op tab: "1"
    Then Druk op type: "Button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op: "<Zaak>" zaak link op tab: "1"
    When Log in op pagina, met user: "test.automation@ciz.nl" en wachtwoord: "Welkom04!" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Urgentie" op tab: "2"
    # Then Check Text naam: "Samenvatting Paneel - Status" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Wettelijke uiterste beslisdatum - Datum" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Wettelijke uiterste beslisdatum - WRD" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Wettelijke uiterste beslisdatum - Kalenderdagen" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Interne uiterste beslisdatum - Datum" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Interne uiterste beslisdatum - GRD" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Interne uiterste beslisdatum - Kalenderdagen" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Naam" op tab: "2"
    # Then Check Text naam: "Samenvatting Paneel - Geboortedatum" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - BSN" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Cliëntnummer" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Zaakgegevens" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Ingediende aanvraag" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Bijbehorende zaken" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Notities" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Documenten" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Medische historie" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Contactmomenten" op tab: "2"
    Then Druk op type: "Button" met naam: "Ga" met index: "0" op tab: "2"
    When Is de aanvraag administratief volledig?: "<admincompleet>" op tab: "2"
    Then Check Text naam: "Is de aanvraag administratief volledig?" op tab: "2"
    Then Check Text naam: "Is de aanvraag administratief volledig? - Ja" op tab: "2"
    Then Check Text naam: "Is de aanvraag administratief volledig? - Nee" op tab: "2"
    # Then Check Text naam: "Toelichting" op tab: "2"  >>>>>>>>>>>>>>>>>>>>>>>> Different data-test-id
    Then Check Text naam: "Opslaan knop" op tab: "2"
    # Then Check Text naam: "Annuleren knop" op tab: "2"  >>>>>>>>>>>>>>>>>>>>>>>> Different data-test-id
    Then Check Text naam: "Indienen" op tab: "2"
    Then Druk op type: "Button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "Button" met naam: "Ga" met index: "0" op tab: "2"
    When Moet er nieuw advies worden gegeven klik op "<nieuwAdvies>", aanvraagsoort:"<Aanvraagsoort>"
    Then Check Text naam: "Onderzoeksgegevens overnemen" op tab: "2"
    Then Check Text naam: "Algemeen" op tab: "2"
    Then Check Text naam: "Toestemming voor inzage" op tab: "2"
    Then Check Text naam: "Ziekte/Stoornis" op tab: "2"
    Then Check Text naam: "Is er sprake van een ziekte of stoornis?" op tab: "2"
    Then Check Text naam: "Verzorging" op tab: "2"
    Then Check Text naam: "Lichaamshygiëne" op tab: "2"
    Then Check Text naam: "Zindelijkheid" op tab: "2"
    Then Check Text naam: "Eten en drinken" op tab: "2"
    Then Check Text naam: "Mobiliteit" op tab: "2"
    Then Check Text naam: "Medische verzorging" op tab: "2"
    Then Check Text naam: "Oppassing" op tab: "2"
    Then Check Text naam: "Gedrag" op tab: "2"
    Then Check Text naam: "Communicatie" op tab: "2"
    Then Check Text naam: "Alleen thuis zijn" op tab: "2"
    Then Check Text naam: "Begeleiding buitenshuis" op tab: "2"
    Then Check Text naam: "Bezig houden, handreikingen" op tab: "2"
    # Then Check Text naam: "Opslaan knop" op tab: "2"    >>>>>>> Andere data-test-id
    # Then Check Text naam: "Annuleren knop" op tab: "2"  >>>>>>>>>>>>>>>>>>>>>>>> Different data-test-id
    Then Check Text naam: "Doorgaan" op tab: "2"
    Then Wil je de onderzoeksgegevens ophalen op tab "3"? gegevensOphalen :"<gegevensOphalen>", nieuwAdvies:"<nieuwAdvies>"
    Then Is er sprake van een ziekte of stoornis? gegevensOphalen:"<gegevensOphalen>", stoornis:"<stoornis>", klant:"<klant>"
    Then Wanneer stoornis is "<stoornis>" en gegevens ophalen is "<gegevensOphalen>", dan is aard van ziekte of stoornis "<aardVanDeZiekteOfStoornis>"
    Then Wanneer stoornis is "<stoornis>" dan worden de scores ingevuld "<uitkomstScore>"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Check Text naam: "Vastleggen advies titel" op tab: "2"
   # Then Check Text naam: "Advies waartegen bezwaar wordt gemaakt" op tab: "2"   >>>>>>> Andere data-test-id
    Then Check Text naam: "Leeftijd tijdens primair advies" op tab: "2"
    Then Check Text naam: "Voorgesteld advies" op tab: "2"
    Then Check Text naam: "Score" op tab: "2"
    Then Check Text naam: "Basis voor advies" op tab: "2"
    Then Check Text naam: "Afwijken van voorgesteld advies" op tab: "2"
    Then Check Text naam: "Komt er een (hoor)zitting?" op tab: "2"
    Then Check Text naam: "Komt er een (hoor)zitting? - Ja" op tab: "2"
    Then Check Text naam: "Komt er een (hoor)zitting? - Nee" op tab: "2"
    Then Check Text naam: "Duur" op tab: "2"
    Then Check Text naam: "Einddatum advies" op tab: "2"
    Then Check Text naam: "Uitgevoerd onderzoek" op tab: "2"
    Then Check Text naam: "Medisch advies meesturen?" op tab: "2"
    Then Check Text naam: "Medisch advies meesturen? - Ja" op tab: "2"
    Then Check Text naam: "Medisch advies meesturen? - Nee" op tab: "2"
    # Then Check Text naam: "Opslaan knop" op tab: "2"
    Then Check Text naam: "Terug knop" op tab: "2"
    Then Check Text naam: "Voltooien" op tab: "2"
    When Wijzig voorgesteld Advies "<afwijkendAdvies>", tab "2"
    When Komt er een hoorzitting?: "<hoorzitting>" op tab "2"
    Then Druk op type: "Button" met naam: "Voltooien" met index: "0" op tab: "2"
#Test omgeving

    Examples:
      | Scenario | env | bsn       | klant | Aanvraagwijze | Aanvraagdatum | Aanvraagsoort | Zaaknummer | Zaak    | ouderToestemming | geheimPersoon | burgerlijkeStaat | leefSituatie | juridischeMaatregelen | verblijfStatus | admincompleet | nieuwAdvies | stoornis | aardVanDeZiekteOfStoornis | uitkomstScore | gegevensOphalen | afwijkendAdvies                   | hoorzitting |
      |        1 | BUK | 146339563 | oude  | Written       |    10-10-2023 | Objection     | BA-141005  | BUK-BZW | nee              | no            | Married          | Partner      | None                  | Permanent      | ja            | ja          | ja       | Lichamelijke aandoening   | Positief      | nee             | Wijzig naar Negatief voor bezwaar | nee         |
#Acc omgeving
    # Examples:
    #   | Scenario | env | bsn       | klant | Aanvraagwijze | Aanvraagdatum | Aanvraagsoort | Zaaknummer   | Zaak     |ouderToestemming | geheimPersoon | burgerlijkeStaat       | leefSituatie | juridischeMaatregelen | verblijfStatus | admincompleet| nieuwAdvies | stoornis | aardVanDeZiekteOfStoornis | uitkomstScore | gegevensOphalen | afwijkendAdvies                   |hoorzitting|
    #   |        1 | BUK | 146339563 | oude  | Written       |    10-10-2023 | Objection     | BA-87007    | BUK-BZW  |nee              | no            | Married                | Partner      | None                  | Permanent      |ja            |ja           | ja       | Lichamelijke aandoening   | Positief      | nee             | Wijzig naar Negatief voor bezwaar | nee       |

  @Buk_existingClient_CheckText_2
  Scenario Outline: Register and validate a existing client in BUK application
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automation@ciz.nl" en wachtwoord: "Welkom04!" op tab: "0"
    When Druk op type: "Button" met naam: "Aanvraag" met index: "0" op tab: "0"
    When Log in op pagina, met user: "test.automation@ciz.nl" en wachtwoord: "Welkom04!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    Then Druk op type: "Button" met naam: "Stage progress" met index: "0" op tab: "1"
    Then Check Text naam: "Stel velden in nadat de case is gemaakt" op tab: "1"
    Then Check Text naam: "Aanmaken log zaak" op tab: "1"
    Then Check Text naam: "Aanmaken zaakfolder in CMIS" op tab: "1"
    Then Check Text naam: "Bijwerken SVB berichten" op tab: "1"
    Then Check Text naam: "Registratie" op tab: "1"
    Then Check Text naam: "Afronden Migratie" op tab: "1"
    Then Check Text naam: "Valideren cliënt" op tab: "1"
    Then Check Text naam: "In behandeling" op tab: "1"
    Then Check Text naam: "Selecteren cliënt titel" op tab: "1"
    Then Check Text naam: "Zoeken cliënt" op tab: "1"
    Then Check Text naam: "Gevonden cliënten" op tab: "1"
    Then Check Text naam: "Wis zoekcriteria knop" op tab: "1"
    Then Check Text naam: "Zoek cliënt knop" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Doorgaan knop" op tab: "1"
    Then Check Text naam: "Burgerservicenummer (BSN)" op tab: "1"
    Then Check Text naam: "Cliëntnummer" op tab: "1"
    Then Check Text naam: "Geboortenaam" op tab: "1"
    Then Check Text naam: "Geboortedatum" op tab: "1"
    Then Check Text naam: "Land" op tab: "1"
    Then Check Text naam: "Postcode" op tab: "1"
    Then Check Text naam: "Huisnummer" op tab: "1"
    Then Check Text naam: "Geslacht Selecteren cliënt" op tab: "1"
    Then Check Text naam: "Naam en voorletters resultaat" op tab: "1"
    Then Check Text naam: "Geboortedatum resultaat" op tab: "1"
    Then Check Text naam: "Geslacht resultaat" op tab: "1"
    Then Check Text naam: "Burgerservicenummer (BSN) resultaat" op tab: "1"
    Then Check Text naam: "Cliëntnummer resultaat" op tab: "1"
    Then Check Text naam: "Postcode en huisnummer resultaat" op tab: "1"
    Then Check Text naam: "Plaats" op tab: "1"
    Then Check Text naam: "Geen bestaande cliënten gevonden, pas de zoekcriteria aan of start aanvraag voor nieuwe cliënt." op tab: "1"
    Then Check Text naam: "Aanvraag creëren met een nieuwe cliënt" op tab: "1"
    When Vul bsn "<bsn>" voor een "<klant>" klant op tab: "1"
    When Klik op selecteren klant op tab: "1"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Registreren aanvraaggegevens Aanvraagwijze: "<Aanvraagwijze>" Aanvraagdatum: "<Aanvraagdatum>" Aanvraagsoort: "<Aanvraagsoort>" op tab: "1"
    When Vul BUK informatie in met: "<Aanvraagsoort>" ouder toestemming: "<ouderToestemming>" op tab: "1"
    When Selecteer resolved-completed zaak "<Zaaknummer>" op tab: "1"
    Then Check Text naam: "Registreren aanvraaggegevens titel" op tab: "1"
    Then Check Text naam: "Aanvraagsoort sectie" op tab: "1"
    Then Check Text naam: "Zorgvraag sectie" op tab: "1"
    # Then Check Text naam: "Geboortedatum cliënt" op tab: "1"
    # Then Check Text naam: "Leeftijd" op tab: "1"
    Then Check Text naam: "Aanvraagwijze" op tab: "1"
    Then Check Text naam: "Aanvraagdatum" op tab: "1"
    Then Check Text naam: "Aanvraagsoort" op tab: "1"
    Then Check Text naam: "Registratienummer SVB" op tab: "1"
    Then Check Text naam: "Geeft de aanvragende ouder toestemming om indien aanwezig het cliëntendossier in te zien?" op tab: "1"
    Then Check Text naam: "Toesteming Antwoord Ja" op tab: "1"
    Then Check Text naam: "Toesteming Antwoord Nee" op tab: "1"
    Then Check Text naam: "Advies waartegen bezwaar wordt gemaakt" op tab: "1"
    Then Check Text naam: "Zorgvraag" op tab: "1"
    Then Check Text naam: "Tekstsbox max. karakter" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Doorgaan knop" op tab: "1"
    Then Check Text naam: "Terug knop" op tab: "1"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Check Text naam: "Persoonlijk titel" op tab: "1"
    Then Check Text naam: "Geheim persoon" op tab: "1"
    Then Check Text naam: "Speciaal onderzoek" op tab: "1"
    Then Check Text naam: "onderzoek antwoord Ja" op tab: "1"
    Then Check Text naam: "Onderzoek antwoord Nee" op tab: "1"
    Then Check Text naam: "Burgerservicenummer (BSN) persoonlijk" op tab: "1"
    Then Check Text naam: "Geboortedatum persoonlijk" op tab: "1"
    Then Check Text naam: "Roepnaam" op tab: "1"
    Then Check Text naam: "Geboortenaam persoonlijk" op tab: "1"
    Then Check Text naam: "Voorvoegsel" op tab: "1"
    Then Check Text naam: "Voornamen" op tab: "1"
    Then Check Text naam: "Voorletter(s)" op tab: "1"
    Then Check Text naam: "Geslacht Persoonlijk" op tab: "1"
    Then Check Text naam: "Overlijdensdatum" op tab: "1"
    Then Check Text naam: "Naamgebruik" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Doorgaan knop" op tab: "1"
    Then Check Text naam: "Terug knop" op tab: "1"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Check Text naam: "Aanvullend Persoonlijk titel" op tab: "1"
    Then Check Text naam: "Burgerlijke staat" op tab: "1"
    Then Check Text naam: "Leefsituatie" op tab: "1"
    Then Check Text naam: "Juridische maatregelen" op tab: "1"
    Then Check Text naam: "Verblijfsstatus (alleen invullen als de cliënt niet de Nederlandse nationaliteit heeft)" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Doorgaan knop" op tab: "1"
    Then Check Text naam: "Terug knop" op tab: "1"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Check Text naam: "1e Telefoonnummer vraag" op tab: "1"
    Then Check Text naam: "1e Landnummer" op tab: "1"
    Then Check Text naam: "1e Telefoonnummer" op tab: "1"
    Then Check Text naam: "1e Geheim nummer" op tab: "1"
    Then Check Text naam: "2e Telefoonnummer vraag" op tab: "1"
    Then Check Text naam: "2e Landnummer" op tab: "1"
    Then Check Text naam: "2e Telefoonnummer" op tab: "1"
    Then Check Text naam: "2e Geheim nummer" op tab: "1"
    Then Check Text naam: "E-mailadres" op tab: "1"
    Then Check Text naam: "Taal" op tab: "1"
    Then Check Text naam: "Is de cliënt in staat tot telefonische communicatie" op tab: "1"
    Then Check Text naam: "communicatie antwoord Ja" op tab: "1"
    Then Check Text naam: "communicatie andtwoord Nee" op tab: "1"
    Then Check Text naam: "Bijzondere communicatievorm" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Doorgaan knop" op tab: "1"
    Then Check Text naam: "Terug knop" op tab: "1"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Check Text naam: "Type relatie" op tab: "1"
    Then Check Text naam: "Wettelijke relatie" op tab: "1"
    Then Check Text naam: "Geboortenaam" op tab: "1"
    Then Check Text naam: "Voorvoegsel" op tab: "1"
    Then Check Text naam: "Voorletter(s)" op tab: "1"
    Then Check Text naam: "1e Landnummer" op tab: "1"
    Then Check Text naam: "1e Telefoonnummer" op tab: "1"
    Then Check Text naam: "2e Landnummer" op tab: "1"
    Then Check Text naam: "2e Telefoonnummer" op tab: "1"
    Then Check Text naam: "E-mailadres relatie" op tab: "1"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Check Text naam: "Adressen titel" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres header" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres checkbox" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres header" op tab: "1"
    Then Check Text naam: "Afwijkend tijdelijke Verblijfadres checkbox" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - land" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Postcode" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Huisnummer" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Huisletter" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Huisnummeraanduiding" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Zoek knop" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Straat" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Plaats" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Kamer" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Opmerking" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Doorgaan knop" op tab: "1"
    Then Check Text naam: "Terug knop" op tab: "1"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Check Text naam: "Indienen titel" op tab: "1"
    Then Check Text naam: "Geboortedatum cliënt" op tab: "1"
    Then Check Text naam: "Leeftijd" op tab: "1"
    Then Check Text naam: "Aanvraagwijze" op tab: "1"
    Then Check Text naam: "Aanvraagdatum" op tab: "1"
    Then Check Text naam: "Aanvraagsoort" op tab: "1"
    Then Check Text naam: "Registratienummer SVB" op tab: "1"
    Then Check Text naam: "Geeft de aanvragende ouder toestemming om indien aanwezig het cliëntendossier in te zien?" op tab: "1"
    Then Check Text naam: "Zorgvraag" op tab: "1"
    Then Check Text naam: "Geheim persoon" op tab: "1"
    Then Check Text naam: "Speciaal onderzoek" op tab: "1"
    Then Check Text naam: "Burgerservicenummer (BSN) persoonlijk" op tab: "1"
    Then Check Text naam: "Geboortedatum persoonlijk" op tab: "1"
    Then Check Text naam: "Roepnaam" op tab: "1"
    Then Check Text naam: "Geboortenaam" op tab: "1"
    Then Check Text naam: "Voorvoegsel" op tab: "1"
    Then Check Text naam: "Voornamen" op tab: "1"
    Then Check Text naam: "Voorletter(s)" op tab: "1"
    Then Check Text naam: "Geslacht Persoonlijk" op tab: "1"
    Then Check Text naam: "Overlijdensdatum" op tab: "1"
    Then Check Text naam: "Naamgebruik" op tab: "1"
    Then Check Text naam: "Burgerlijke staat" op tab: "1"
    Then Check Text naam: "Leefsituatie" op tab: "1"
    Then Check Text naam: "Juridische maatregelen" op tab: "1"
    Then Check Text naam: "Verblijfsstatus (alleen invullen als de cliënt niet de Nederlandse nationaliteit heeft)" op tab: "1"
    Then Check Text naam: "1e Landnummer" op tab: "1"
    Then Check Text naam: "1e Telefoonnummer" op tab: "1"
    Then Check Text naam: "1e Geheim nummer" op tab: "1"
    Then Check Text naam: "2e Landnummer" op tab: "1"
    Then Check Text naam: "2e Telefoonnummer" op tab: "1"
    Then Check Text naam: "2e Geheim nummer" op tab: "1"
    Then Check Text naam: "E-mailadres" op tab: "1"
    Then Check Text naam: "Taal" op tab: "1"
    Then Check Text naam: "Is de cliënt in staat tot telefonische communicatie" op tab: "1"
    Then Check Text naam: "Bijzondere communicatievorm" op tab: "1"
    # Then Check Text naam: "Type relatie" op tab: "1"
    Then Check Text naam: "Wettelijke relatie" op tab: "1"
    Then Check Text naam: "Geboortenaam" op tab: "1"
    Then Check Text naam: "Voorvoegsel" op tab: "1"
    Then Check Text naam: "Voorletter(s)" op tab: "1"
    Then Check Text naam: "1e Landnummer" op tab: "1"
    Then Check Text naam: "1e Telefoonnummer" op tab: "1"
    Then Check Text naam: "2e Landnummer" op tab: "1"
    Then Check Text naam: "2e Telefoonnummer" op tab: "1"
    Then Check Text naam: "E-mailadres relatie" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - land" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Postcode" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Huisnummer" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Huisletter" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Huisnummeraanduiding" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Straat" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Plaats" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Kamer" op tab: "1"
    Then Check Text naam: "Feitelijke woonadres - Opmerking" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Relatie tot cliënt" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - land" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Postcode" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Huisnummer" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Huisletter" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Toevoeging huisnummer" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Huisnummeraanduiding" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Straat" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Plaats" op tab: "1"
    Then Check Text naam: "Afwijkend correspondentieadres - Kamer" op tab: "1"
    Then Check Text naam: "Annuleren knop" op tab: "1"
    Then Check Text naam: "Aanmaken knop" op tab: "1"
    Then Check Text naam: "Terug knop" op tab: "1"
    Then Druk op type: "Button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op: "<Zaak>" zaak link op tab: "1"
    When Log in op pagina, met user: "test.automation@ciz.nl" en wachtwoord: "Welkom04!" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Urgentie" op tab: "2"
    # Then Check Text naam: "Samenvatting Paneel - Status" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Wettelijke uiterste beslisdatum - Datum" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Wettelijke uiterste beslisdatum - WRD" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Wettelijke uiterste beslisdatum - Kalenderdagen" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Interne uiterste beslisdatum - Datum" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Interne uiterste beslisdatum - GRD" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Interne uiterste beslisdatum - Kalenderdagen" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Naam" op tab: "2"
    # Then Check Text naam: "Samenvatting Paneel - Geboortedatum" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - BSN" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Cliëntnummer" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Zaakgegevens" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Ingediende aanvraag" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Bijbehorende zaken" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Notities" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Documenten" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Medische historie" op tab: "2"
    Then Check Text naam: "Samenvatting Paneel - Contactmomenten" op tab: "2"
    Then Druk op type: "Button" met naam: "Ga" met index: "0" op tab: "2"
    When Is de aanvraag administratief volledig?: "<admincompleet>" op tab: "2"
    Then Check Text naam: "Is de aanvraag administratief volledig?" op tab: "2"
    Then Check Text naam: "Is de aanvraag administratief volledig? - Ja" op tab: "2"
    Then Check Text naam: "Is de aanvraag administratief volledig? - Nee" op tab: "2"
    # Then Check Text naam: "Toelichting" op tab: "2"  >>>>>>>>>>>>>>>>>>>>>>>> Different data-test-id
    Then Check Text naam: "Opslaan knop" op tab: "2"
    # Then Check Text naam: "Annuleren knop" op tab: "2"  >>>>>>>>>>>>>>>>>>>>>>>> Different data-test-id
    Then Check Text naam: "Indienen" op tab: "2"
    Then Druk op type: "Button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "Button" met naam: "Ga" met index: "0" op tab: "2"
    When Moet er nieuw advies worden gegeven klik op "<nieuwAdvies>", aanvraagsoort:"<Aanvraagsoort>"
    Then Check Text naam: "Onderzoeksgegevens overnemen" op tab: "2"
    Then Check Text naam: "Algemeen" op tab: "2"
    Then Check Text naam: "Toestemming voor inzage" op tab: "2"
    Then Check Text naam: "Ziekte/Stoornis" op tab: "2"
    Then Check Text naam: "Is er sprake van een ziekte of stoornis?" op tab: "2"
    Then Check Text naam: "Verzorging" op tab: "2"
    Then Check Text naam: "Lichaamshygiëne" op tab: "2"
    Then Check Text naam: "Zindelijkheid" op tab: "2"
    Then Check Text naam: "Eten en drinken" op tab: "2"
    Then Check Text naam: "Mobiliteit" op tab: "2"
    Then Check Text naam: "Medische verzorging" op tab: "2"
    Then Check Text naam: "Oppassing" op tab: "2"
    Then Check Text naam: "Gedrag" op tab: "2"
    Then Check Text naam: "Communicatie" op tab: "2"
    Then Check Text naam: "Alleen thuis zijn" op tab: "2"
    Then Check Text naam: "Begeleiding buitenshuis" op tab: "2"
    Then Check Text naam: "Bezig houden, handreikingen" op tab: "2"
    # Then Check Text naam: "Opslaan knop" op tab: "2"    >>>>>>> Andere data-test-id
    # Then Check Text naam: "Annuleren knop" op tab: "2"  >>>>>>>>>>>>>>>>>>>>>>>> Different data-test-id
    Then Check Text naam: "Doorgaan" op tab: "2"
    Then Wil je de onderzoeksgegevens ophalen op tab "2"? gegevensOphalen :"<gegevensOphalen>", nieuwAdvies:"<nieuwAdvies>"
    Then Is er sprake van een ziekte of stoornis? gegevensOphalen:"<gegevensOphalen>", stoornis:"<stoornis>", klant:"<klant>"
    Then Wanneer stoornis is "<stoornis>" en gegevens ophalen is "<gegevensOphalen>", dan is aard van ziekte of stoornis "<aardVanDeZiekteOfStoornis>"
    Then Wanneer stoornis is "<stoornis>" dan worden de scores ingevuld "<uitkomstScore>"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Check Text naam: "Vastleggen advies titel" op tab: "2"
   # Then Check Text naam: "Advies waartegen bezwaar wordt gemaakt" op tab: "2"   >>>>>>> Andere data-test-id
    Then Check Text naam: "Leeftijd tijdens primair advies" op tab: "2"
    Then Check Text naam: "Voorgesteld advies" op tab: "2"
    Then Check Text naam: "Score" op tab: "2"
    Then Check Text naam: "Basis voor advies" op tab: "2"
    Then Check Text naam: "Afwijken van voorgesteld advies" op tab: "2"
    Then Check Text naam: "Advies" op tab: "2"
    Then Check Text naam: "Komt er een (hoor)zitting?" op tab: "2"
    Then Check Text naam: "Komt er een (hoor)zitting? - Ja" op tab: "2"
    Then Check Text naam: "Komt er een (hoor)zitting? - Nee" op tab: "2"
    Then Check Text naam: "Reden geen advies" op tab: "2"
    # Then Check Text naam: "Toelichting" op tab: "2"  >>>>>>>>>>>>>>>>>>>>>>>> Different data-test-id
    Then Check Text naam: "Uitgevoerd onderzoek" op tab: "2"
    Then Check Text naam: "Medisch advies meesturen?" op tab: "2"
    Then Check Text naam: "Medisch advies meesturen? - Ja" op tab: "2"
    Then Check Text naam: "Medisch advies meesturen? - Nee" op tab: "2"
    Then Check Text naam: "Preview brief knop" op tab: "2"
    # Then Check Text naam: "Opslaan knop" op tab: "2"
    Then Check Text naam: "Terug knop" op tab: "2"
    Then Check Text naam: "Voltooien" op tab: "2"
    When Wijzig voorgesteld Advies "<afwijkendAdvies>", tab "2"
    When Komt er een hoorzitting?: "<hoorzitting>" op tab "2"
    Then Check Text naam: "Beschikbaarheid voor (hoor)zitting" op tab: "2"
    Then Druk op type: "Button" met naam: "Voltooien" met index: "0" op tab: "2"
    Then Druk op type: "Button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "2"
  # Then Check Text naam: "Advies waartegen bezwaar wordt gemaakt" op tab: "2"   >>>>>>> Andere data-test-id
    Then Check Text naam: "Leeftijd tijdens primair advies" op tab: "2"
    Then Check Text naam: "Voorgesteld advies" op tab: "2"
    Then Check Text naam: "Score" op tab: "2"
    Then Check Text naam: "Basis voor advies" op tab: "2"
    Then Check Text naam: "Afwijken van voorgesteld advies" op tab: "2"
    Then Check Text naam: "Advies" op tab: "2"
    Then Check Text naam: "Komt er een (hoor)zitting?" op tab: "2"
    Then Check Text naam: "Komt er een (hoor)zitting? - Ja" op tab: "2"
    Then Check Text naam: "Komt er een (hoor)zitting? - Nee" op tab: "2"
    # Then Check Text naam: "Toelichting" op tab: "2"  >>>>>>>>>>>>>>>>>>>>>>>> Different data-test-id
    Then Check Text naam: "Uitgevoerd onderzoek" op tab: "2"
    Then Check Text naam: "Medisch advies meesturen?" op tab: "2"
    Then Check Text naam: "Medisch advies meesturen? - Ja" op tab: "2"
    Then Check Text naam: "Medisch advies meesturen? - Nee" op tab: "2"
    Then Check Text naam: "Preview brief knop" op tab: "2"
    Then Check Text naam: "Versturen via" op tab: "2"
    Then Check Text naam: "Versturen via - Email" op tab: "2"
    Then Check Text naam: "Versturen via - Post" op tab: "2"
    Then Check Text naam: "Aangetekend versturen" op tab: "2"
    Then Check Text naam: "Aangetekend versturen - Ja" op tab: "2"
    Then Check Text naam: "Aangetekend versturen - Nee" op tab: "2"
    # Then Check Text naam: "Opslaan knop" op tab: "2"
    Then Check Text naam: "Terug knop" op tab: "2"
    Then Check Text naam: "Voltooien" op tab: "2"
    When Wijzig voorgesteld Advies "<afwijkendAdvies>", tab "2"
    When Komt er een hoorzitting?: "<hoorzitting>" op tab "2"
    When Druk op type: "Button" met naam: "post" met index: "0" op tab: "2"
    When Druk op type: "Button" met naam: "Ja" met index: "0" op tab: "2"
    When Druk op type: "Button" met naam: "Voltooien" met index: "0" op tab: "2"
    Then Druk op type: "Button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "Button" met naam: "Doorgaan" met index: "0" op tab: "2"
    # Then Check Text naam: "Advies waartegen bezwaar wordt gemaakt" op tab: "2"   >>>>>>> Andere data-test-id
    Then Check Text naam: "Leeftijd tijdens primair advies" op tab: "2"
    Then Check Text naam: "Voorgesteld advies" op tab: "2"
    Then Check Text naam: "Score" op tab: "2"
    Then Check Text naam: "Basis voor advies" op tab: "2"
    Then Check Text naam: "Afwijken van voorgesteld advies" op tab: "2"
    Then Check Text naam: "Advies" op tab: "2"
    # Then Check Text naam: "Toelichting" op tab: "2"  >>>>>>>>>>>>>>>>>>>>>>>> Different data-test-id
    Then Check Text naam: "Uitgevoerd onderzoek" op tab: "2"
    Then Check Text naam: "Medisch advies meesturen?" op tab: "2"
    Then Check Text naam: "Medisch advies meesturen? - Ja" op tab: "2"
    Then Check Text naam: "Medisch advies meesturen? - Nee" op tab: "2"
    Then Check Text naam: "Preview brief knop" op tab: "2"
    Then Check Text naam: "Versturen via" op tab: "2"
    Then Check Text naam: "Versturen via - Email" op tab: "2"
    Then Check Text naam: "Versturen via - Post" op tab: "2"
    # Then Check Text naam: "E-mailadres" op tab: "1" >>>>>>>>>>>>>>>>>>>>>>>> Different data-test-id
    Then Check Text naam: "Ontvangerscontrole" op tab: "2"
    Then Check Text naam: "Ontvangerscontrole - Toegangscode" op tab: "2"
    Then Check Text naam: "Ontvangerscontrole - SMS" op tab: "2"
    # Then Check Text naam: "Opslaan knop" op tab: "2"
    Then Check Text naam: "Terug knop" op tab: "2"
    Then Check Text naam: "Voltooien" op tab: "2"
    When Advies na zitting: "<adviesNaZitting>" op tab "2"
    When Vul in emailadres: "test.automation@ciz.nl" op tab: "2"
    Then Druk op type: "Button" met naam: "Toegangscode" met index: "0" op tab: "2"
    Then Check Text naam: "Toegangscode" op tab: "2"
    Then Druk op type: "Button" met naam: "Voltooien" met index: "0" op tab: "2"
# test omgeving

    Examples:
      | Scenario | env | bsn       | klant | Aanvraagwijze | Aanvraagdatum | Aanvraagsoort | Zaaknummer | Zaak    | ouderToestemming | geheimPersoon | juridischeMaatregelen | admincompleet | nieuwAdvies | stoornis | aardVanDeZiekteOfStoornis | uitkomstScore | gegevensOphalen | hoorzitting | afwijkendAdvies                   | adviesNaZitting |
      |        1 | BUK | 184089359 | oude  | Fax           |     15-9-2023 | Objection     | BA-144073  | BUK-BZW | nee              | no            | None                  | ja            | ja          | geen     | geen                      |               | ja              | ja          | Wijzig naar Negatief voor bezwaar | Blijft negatief |
# Acc omgeving
    # Examples:
    #   | Scenario | env | bsn       | klant | Aanvraagwijze | Aanvraagdatum | Aanvraagsoort | Zaaknummer   | Zaak      |ouderToestemming | geheimPersoon | juridischeMaatregelen | admincompleet| nieuwAdvies | stoornis | aardVanDeZiekteOfStoornis | uitkomstScore | gegevensOphalen | hoorzitting  | afwijkendAdvies                   | adviesNaZitting  |
    #   |        1 | BUK | 184089359 | oude  | Fax           |     15-9-2023 | Objection     | BA-85022    | BUK-BZW   |nee              | no            | None                  | ja           | ja          | geen     | geen                      |               | ja              | ja           | Wijzig naar Negatief voor bezwaar | Blijft negatief  |
