Feature: Automation - VWM - Local action: Registreren opname

  Background: https://ciz.atlassian.net/browse/ZSD-36468
# A‍lgemene informatie: 
# Mededeling opname wordt verstrekt door de zorgaanbieder zodra er opname plaatsvindt of wordt voortgezet op basis van een beschikking inzake de rechterlijke machtiging tot opname en verblijf,
# de voorwaardelijke machtiging, en machtigingen tot voortzetting van de inbewaringstelling (art 42 Wzd). Het CIZ heeft de taak de opnamemelding te registreren.
#
#
#
#
# Acceptance Criteria:
# Gegeven een gesloten VWM zaak , wanneer ik als gebruiker in het actie menu kijk, dan zie ik de local action 'Registreren opname' -------> Done!!
#
# Gegeven een open VWM zaak , wanneer ik als gebruiker in het actie menu kijk, dan zie ik de local action 'Registreren opname' niet  -------> Done!!
#
# Gegeven een gesloten VWM zaak, wanneer ik de local action Registreren opname aanroep, dan zie ik het scherm zoals beschreven in de story hierboven    -------> Done!!
#
# Gegeven de local action Registreren opname, wanneer de einddatum van de VWM-beschikking korter is dan zes maanden, dan adviseert het systeem de einddatum dat geregistreerd is als einddatum op https://ciz.atlassian.net/browse/ZSD-18534 
#
# Gegeven de local action Registreren opname, wanneer de einddatum van de VWM-beschikking langer is dan zes maanden, dan adviseert het systeem een einddatum van zes maanden vanaf de ingangsdatum
#
# Gegeven de local action Registreren opname, wanneer ik een einddatum invoer die vóór de ingangsdatum ligt, dan krijg ik de melding dat dit niet kan, zoals beschreven in deze story
#
# Gegeven de local action Registreren opname, wanneer de gebruiker de geadviseerde einddatum wil wijzigen, dan wordt de gebruiker niet beperkt door het systeem
#
# Gegeven de local action Registreren opname, wanneer ik de local action meerdere keren wil aanroepen, dan word ik daar niet in beperkt
#
# Gegeven de juridische status na de local action Registreren opname, wanneer ik kijk naar de actuele juridische status op 360 graden klantbeeld dan zie ik de status rechterlijke machtiging met als startdatum en als einddatum de datum die gekozen is in de local action bij ingangsdatum en einddatum
#
#
#
#
#
#

  @ZSD-36468_ZSD-36495_VWM_Local_action_Registreren_opname
  Scenario Outline: Gegeven een gesloten VWM zaak , wanneer ik als gebruiker in het actie menu kijk, dan zie ik de local action 'Registreren opname'
  Gegeven een open VWM zaak , wanneer ik als gebruiker in het actie menu kijk, dan zie ik de local action 'Registreren opname' niet

    Given We testen scenario: "<Scenario>"
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "26-01-2022" voor index: "2" op tab: "1"
    When Fill in veld value: "roepnaam-baby-Test" voor index: "3" op tab: "1"
    When Fill in veld value: "baby-Test" voor index: "4" op tab: "1"
    When Fill in veld value: "van den" voor index: "5" op tab: "1"
    When Fill in veld value: "Baby test" voor index: "6" op tab: "1"
    When Fill in veld value: "BT" voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "<wettelijkeRelatie>" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "7-1-2025" voor index: "1" op tab: "1"
    Then Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    Then Fill in veld value: "11-02-2025" voor index: "2" op tab: "1"
    Then Fill in veld value: "11-02-2025" voor index: "3" op tab: "1"
    When Fill in block value: "Toelichting bij zorgvraag: U kunt hier vertellen waarom u zorg nodig heeft. Wat voor ziekte, aandoening of klacht heeft u? Als u een langere tekst heeft, bijvoorbeeld uit een behandelplan, dan kunt u na het indienen van dit formulier een document toevoegen. " voor index: "0" op tab: "1"
    When Select option by value: "6 Months" voor index: "2" op tab: "1"
    When Fill in block value: "Onderbouwing gewenste geldigheidsduur" voor index: "1" op tab: "1"
    When Druk op type: "radio" met naam: "Yes" met index: "5" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "mama-test" voor index: "2" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "4" op tab: "1"
    When Fill in veld value: "9" voor index: "5" op tab: "1"
    When Fill in veld value: "Actifaid B.V." voor index: "12" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "16" op tab: "1"
    When Fill in veld value: "9" voor index: "17" op tab: "1"
    When Fill in veld value: "Zorgverantwoordelijke" voor index: "22" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "24" op tab: "1"
    When Fill in veld value: "9" voor index: "25" op tab: "1"
    When Druk op type: "radio" met naam: "true" met index: "6" op tab: "1"
    When Druk op type: "radio" met naam: "true" met index: "8" op tab: "1"
    When Druk op type: "radio" met naam: "true" met index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    When Druk op zaak: "WZD-VWM" link voor: "<Scenario>" op tab: "1"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "5" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "1" op tab: "2"
    When Select option by value: "6 months" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "7" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "8" op tab: "2"
    Then Fill in textvak value: "Dit is een test" voor index: "1" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "9" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "2" op tab: "2"
    When Select option by value: "Hospital" voor index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "10" op tab: "2"
    ##### Vooronderzoek - schermonderdeel Vaststellen grondslag medische verklaring #####  
    Then Druk op type: "radio" met naam: "Groundwork" met index: "0" op tab: "2"
    When Select option by value: "PhysicalHandicap" voor index: "2" op tab: "2"
    ##### Vooronderzoek - schermonderdeel Checklist medische verklaring #####
    Then Druk op type: "radio" met naam: "Sir" met index: "0" op tab: "2"
    When Fill in veld value: "Ik ben de dokter" voor index: "4" op tab: "2"
    When Fill in veld value: "12345678" voor index: "5" op tab: "2"
    When Select option by value: "SO" voor index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "11" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "12" op tab: "2"
    Then Fill in textvak value: "Waaruit blijkt dit" voor index: "5" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "7" op tab: "2"
    Then Fill in textvak value: "Diagnose" voor index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "13" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "14" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "15" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "16" op tab: "2"
    Then Fill in block value: "Waaruit bestaat ernstig nadeel" voor index: "7" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "17" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "18" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "19" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "20" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "21" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "22" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "8" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "23" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "24" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "25" op tab: "2"
    # Then Druk op type: "radio" met naam: "Yes" met index: "26" op tab: "2"
    Then Fill in block value: "Toelichting" voor index: "8" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Datum toevoegen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Reload pagina op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    When Druk op local action "Verzoek WMC" op tab "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op local action "Vernieuwen" op tab "2"
    Then Druk op type: "button" met naam: "Ga" met index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    # When Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    When Select option by value: "Intended conclusion remains" voor index: "0" op tab: "2"
    When Select option by value: "An adjustment is required in the client file" voor index: "1" op tab: "2"
    Then Fill in block value: "Dit is een voorbeeld voor de test" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op zaak: "WZD-VWM" link voor: "<Scenario>" op tab: "1"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Select option by value: "PhysicalHandicap" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Druk op type: "checkbox" met naam: "Ander gevaar" met index: "0" op tab: "2"
    When Iframe fill in value: "Toelichting bij 'Ander gevaar'" voor index: "0" op tab: "2"
    When Iframe fill in value: "Beschrijf de diagnose en het gedrag die leiden tot ernstig nadeel" voor index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    # Then Druk op type: "radio" met naam: "No" met index: "1" op tab: "2"
    # Then Druk op type: "radio" met naam: "No" met index: "2" op tab: "2"
    When Iframe fill in value: "Beschrijf de houding ten aanzien van opname en verblijf in een accommodatie" voor index: "2" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    Then Select option by value: "6 months" voor index: "5" op tab: "2"
    When Iframe fill in value: "Toelichting Subsidiariteit, proportionaliteit en doelmatigheid" voor index: "3" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    When Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Opstellen verzoekschrift #####
    When Select option by value: "18" voor index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Select option by value: "Authorization for continued detention" voor index: "1" op tab: "2"
    When Fill in block value: "Bijzonderheden zijn voor de test" voor index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "First VWM" met index: "0" op tab: "2"
    When Fill in block value: "Aanleiding toelichting" voor index: "2" op tab: "2"
    When Zoeken en invullen value: "Aanvraag eerste VWM" voor index: "1" indexpijl: "0" op tab: "2"
    When Fill in block value: "Oordeel toelichting" voor index: "4" op tab: "2"
    When Zoeken en invullen value: "Eerste VWM" voor index: "3" indexpijl: "1" op tab: "2"
    When Iframe fill in value: "Beschrijf de houding ten aanzien van opname en verblijf in een accommodatie" voor index: "1" op tab: "2"
    Then Druk op type: "button" met naam: "Voltooien" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    When Zoeken en invullen value: "Overgeplaatst" voor index: "1" indexpijl: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "Postal" met index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "false" met index: "10" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    # Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Status geupdate naar: "Wacht op rechtbank" voor index: "0" op tab: "2"
    #### add test voor registrerenopnamen in local action should be no ####
    Then Local action menu item: "Registreren opname" is: "niet_beschikbaar" op tab: "2"
    Then Druk op local action "Vastleggen uitspraak" op tab "2"
    ##### Vastleggen uitspraak #####
    When Fill in veld value: "9-12-2024" voor index: "0" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "1" op tab: "2"
    When Fill in veld value: "9-12-2025" voor index: "2" op tab: "2"
    Then Select option by value: "Not admissible" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op local action "Registreren opname" op tab "2"
##### registreren opname hier#####
    Then Sla zaak met naam "WZD-VWM" voor: "<Scenario>" in filenaam: "ZSD-36468_ZSD-36495_VWM_Local action_Registreren_opname.json" op tab: "2"

    Examples:
      | Scenario                                                | env | bsn       | Aanvraagwijze | Aanvraagsoort | bijzondereCommunicatieVorm | relatie                     | wettelijkeRelatie |
      | ZSD-36468_ZSD-36495_VWM_Local_action_Registreren_opname | WLZ | 477097327 | Written       | WzdVWM        | None                       | WettelijkeVertegenwoordiger | Curator           |

  @ZSD-36468_ZSD-36495_VWM_Local_action_Registreren_opname_pagina
  Scenario Outline: Gegeven een gesloten VWM zaak, wanneer ik de local action Registreren opname aanroep, dan zie ik het scherm zoals beschreven in de story hierboven
    Given We testen scenario: "<Scenario>"
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "26-01-2022" voor index: "2" op tab: "1"
    When Fill in veld value: "roepnaam-baby-Test" voor index: "3" op tab: "1"
    When Fill in veld value: "baby-Test" voor index: "4" op tab: "1"
    When Fill in veld value: "van den" voor index: "5" op tab: "1"
    When Fill in veld value: "Baby test" voor index: "6" op tab: "1"
    When Fill in veld value: "BT" voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "<wettelijkeRelatie>" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "7-1-2025" voor index: "1" op tab: "1"
    Then Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    Then Fill in veld value: "11-02-2025" voor index: "2" op tab: "1"
    Then Fill in veld value: "11-02-2025" voor index: "3" op tab: "1"
    When Fill in block value: "Toelichting bij zorgvraag: U kunt hier vertellen waarom u zorg nodig heeft. Wat voor ziekte, aandoening of klacht heeft u? Als u een langere tekst heeft, bijvoorbeeld uit een behandelplan, dan kunt u na het indienen van dit formulier een document toevoegen. " voor index: "0" op tab: "1"
    When Select option by value: "6 Months" voor index: "2" op tab: "1"
    When Fill in block value: "Onderbouwing gewenste geldigheidsduur" voor index: "1" op tab: "1"
    When Druk op type: "radio" met naam: "Yes" met index: "5" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "mama-test" voor index: "2" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "4" op tab: "1"
    When Fill in veld value: "9" voor index: "5" op tab: "1"
    When Fill in veld value: "Actifaid B.V." voor index: "12" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "16" op tab: "1"
    When Fill in veld value: "9" voor index: "17" op tab: "1"
    When Fill in veld value: "Zorgverantwoordelijke" voor index: "22" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "24" op tab: "1"
    When Fill in veld value: "9" voor index: "25" op tab: "1"
    When Druk op type: "radio" met naam: "true" met index: "6" op tab: "1"
    When Druk op type: "radio" met naam: "true" met index: "8" op tab: "1"
    When Druk op type: "radio" met naam: "true" met index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    When Druk op zaak: "WZD-VWM" link voor: "<Scenario>" op tab: "1"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "5" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "1" op tab: "2"
    When Select option by value: "6 months" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "7" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "8" op tab: "2"
    Then Fill in textvak value: "Dit is een test" voor index: "1" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "9" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "2" op tab: "2"
    When Select option by value: "Hospital" voor index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "10" op tab: "2"
    ##### Vooronderzoek - schermonderdeel Vaststellen grondslag medische verklaring #####
    Then Druk op type: "radio" met naam: "Groundwork" met index: "0" op tab: "2"
    When Select option by value: "PhysicalHandicap" voor index: "2" op tab: "2"
    ##### Vooronderzoek - schermonderdeel Checklist medische verklaring #####
    Then Druk op type: "radio" met naam: "Sir" met index: "0" op tab: "2"
    When Fill in veld value: "Ik ben de dokter" voor index: "4" op tab: "2"
    When Fill in veld value: "12345678" voor index: "5" op tab: "2"
    When Select option by value: "SO" voor index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "11" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "12" op tab: "2"
    Then Fill in textvak value: "Waaruit blijkt dit" voor index: "5" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "7" op tab: "2"
    Then Fill in textvak value: "Diagnose" voor index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "13" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "14" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "15" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "16" op tab: "2"
    Then Fill in block value: "Waaruit bestaat ernstig nadeel" voor index: "7" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "17" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "18" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "19" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "20" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "21" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "22" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "8" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "23" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "24" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "25" op tab: "2"
    # Then Druk op type: "radio" met naam: "Yes" met index: "26" op tab: "2"
    Then Fill in block value: "Toelichting" voor index: "8" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Datum toevoegen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Reload pagina op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    When Druk op local action "Verzoek WMC" op tab "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op local action "Vernieuwen" op tab "2"
    Then Druk op type: "button" met naam: "Ga" met index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    # When Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    When Select option by value: "Intended conclusion remains" voor index: "0" op tab: "2"
    When Select option by value: "An adjustment is required in the client file" voor index: "1" op tab: "2"
    Then Fill in block value: "Dit is een voorbeeld voor de test" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op zaak: "WZD-VWM" link voor: "<Scenario>" op tab: "1"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Groundwork" met index: "0" op tab: "2"
    Then Select option by value: "PhysicalHandicap" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Druk op type: "checkbox" met naam: "Ander gevaar" met index: "0" op tab: "2"
    When Iframe fill in value: "Toelichting bij 'Ander gevaar'" voor index: "0" op tab: "2"
    When Iframe fill in value: "Beschrijf de diagnose en het gedrag die leiden tot ernstig nadeel" voor index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    # Then Druk op type: "radio" met naam: "No" met index: "1" op tab: "2"
    # Then Druk op type: "radio" met naam: "No" met index: "2" op tab: "2"
    When Iframe fill in value: "Beschrijf de houding ten aanzien van opname en verblijf in een accommodatie" voor index: "2" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    Then Select option by value: "6 months" voor index: "5" op tab: "2"
    When Iframe fill in value: "Toelichting Subsidiariteit, proportionaliteit en doelmatigheid" voor index: "3" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    When Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Opstellen verzoekschrift #####
    When Select option by value: "18" voor index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Select option by value: "Authorization for continued detention" voor index: "1" op tab: "2"
    When Fill in block value: "Bijzonderheden zijn voor de test" voor index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "First VWM" met index: "0" op tab: "2"
    When Fill in block value: "Aanleiding toelichting" voor index: "2" op tab: "2"
    When Zoeken en invullen value: "Aanvraag eerste VWM" voor index: "1" indexpijl: "0" op tab: "2"
    When Fill in block value: "Oordeel toelichting" voor index: "4" op tab: "2"
    When Zoeken en invullen value: "Eerste VWM" voor index: "3" indexpijl: "1" op tab: "2"
    When Iframe fill in value: "Beschrijf de houding ten aanzien van opname en verblijf in een accommodatie" voor index: "1" op tab: "2"
    Then Druk op type: "button" met naam: "Voltooien" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    When Zoeken en invullen value: "Overgeplaatst" voor index: "1" indexpijl: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "Postal" met index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "false" met index: "10" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    # Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Status geupdate naar: "Wacht op rechtbank" voor index: "0" op tab: "2"
    #### add test voor registrerenopnamen in local action should be no ####
    Then Local action menu item: "Registreren opname" is: "niet_beschikbaar" op tab: "2"
    Then Druk op local action "Vastleggen uitspraak" op tab "2"
    ##### Vastleggen uitspraak #####
    When Fill in veld value: "9-12-2024" voor index: "0" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "1" op tab: "2"
    When Fill in veld value: "9-12-2025" voor index: "2" op tab: "2"
    Then Select option by value: "Not admissible" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    #### add test voor registrerenopnamen in local action should be yes ####
    Then Local action menu item: "Registreren opname" is: "beschikbaar" op tab: "2"
    When Druk op local action "Registreren opname" op tab "2"
    When Wacht op deze pagina voor "3000" miliseconden op tab: "2"
    Then Fill in veld value: "9-12-2024" voor index: "0" op tab: "2"
    Then Fill in veld value: "9-12-2025" voor index: "1" op tab: "2"
    Then Type in veld value: "Botniahuis" voor index: "2" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "2"
    Then Local action menu item: "Registreren opname" is: "beschikbaar" op tab: "2"
    When Druk op local action "Registreren opname" op tab "2"
    When Wacht op deze pagina voor "3000" miliseconden op tab: "2"
    Then Fill in veld value: "9-12-2024" voor index: "0" op tab: "2"
    Then Fill in veld value: "9-12-2025" voor index: "1" op tab: "2"
    Then Type in veld value: "Botniahuis" voor index: "2" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "2"
    Then Sla zaak met naam "WZD-VWM" voor: "<Scenario>" in filenaam: "ZSD-36468_ZSD-36495_VWM_Local_action_Registreren_opname_pagina.json" op tab: "2"

    Examples:
      | Scenario                                                | env | bsn       | Aanvraagwijze | Aanvraagsoort | bijzondereCommunicatieVorm | relatie                     | wettelijkeRelatie |
      | ZSD-36468_ZSD-36495_VWM_Local_action_Registreren_opname | WLZ | 247117377 | Written       | WzdVWM        | None                       | WettelijkeVertegenwoordiger | Curator           |

  @ZSD-36468_ZSD-36495_VWM_Local_action_Registreren_opname_adviseert_het_systeem_de_einddatum
  Scenario Outline: Gegeven de local action Registreren opname, wanneer de einddatum van de VWM-beschikking korter is dan zes maanden, dan adviseert het systeem de einddatum dat geregistreerd is
    #Given We testen scenario: "<Scenario>"
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "26-01-2022" voor index: "2" op tab: "1"
    When Fill in veld value: "roepnaam-baby-Test" voor index: "3" op tab: "1"
    When Fill in veld value: "baby-Test" voor index: "4" op tab: "1"
    When Fill in veld value: "van den" voor index: "5" op tab: "1"
    When Fill in veld value: "Baby test" voor index: "6" op tab: "1"
    When Fill in veld value: "BT" voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "<wettelijkeRelatie>" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "7-1-2025" voor index: "1" op tab: "1"
    Then Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    Then Fill in veld value: "11-02-2025" voor index: "2" op tab: "1"
    Then Fill in veld value: "11-02-2025" voor index: "3" op tab: "1"
    When Fill in block value: "Toelichting bij zorgvraag: U kunt hier vertellen waarom u zorg nodig heeft. Wat voor ziekte, aandoening of klacht heeft u? Als u een langere tekst heeft, bijvoorbeeld uit een behandelplan, dan kunt u na het indienen van dit formulier een document toevoegen. " voor index: "0" op tab: "1"
    When Select option by value: "6 Months" voor index: "2" op tab: "1"
    When Fill in block value: "Onderbouwing gewenste geldigheidsduur" voor index: "1" op tab: "1"
    When Druk op type: "radio" met naam: "Yes" met index: "5" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "mama-test" voor index: "2" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "4" op tab: "1"
    When Fill in veld value: "9" voor index: "5" op tab: "1"
    When Fill in veld value: "Actifaid B.V." voor index: "12" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "16" op tab: "1"
    When Fill in veld value: "9" voor index: "17" op tab: "1"
    When Fill in veld value: "Zorgverantwoordelijke" voor index: "22" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "24" op tab: "1"
    When Fill in veld value: "9" voor index: "25" op tab: "1"
    When Druk op type: "radio" met naam: "true" met index: "6" op tab: "1"
    When Druk op type: "radio" met naam: "true" met index: "8" op tab: "1"
    When Druk op type: "radio" met naam: "true" met index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    When Druk op zaak: "WZD-VWM" link voor: "<Scenario>" op tab: "1"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "5" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "1" op tab: "2"
    When Select option by value: "6 months" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "7" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "8" op tab: "2"
    Then Fill in textvak value: "Dit is een test" voor index: "1" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Wacht op deze pagina voor "3000" miliseconden op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "9" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "2" op tab: "2"
    When Select option by value: "Hospital" voor index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "10" op tab: "2"
    ##### Vooronderzoek - schermonderdeel Vaststellen grondslag medische verklaring #####
    Then Druk op type: "radio" met naam: "Groundwork" met index: "0" op tab: "2"
    When Select option by value: "PhysicalHandicap" voor index: "2" op tab: "2"
    ##### Vooronderzoek - schermonderdeel Checklist medische verklaring #####
    Then Druk op type: "radio" met naam: "Sir" met index: "0" op tab: "2"
    When Fill in veld value: "Ik ben de dokter" voor index: "4" op tab: "2"
    When Fill in veld value: "12345678" voor index: "5" op tab: "2"
    When Select option by value: "SO" voor index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "11" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "12" op tab: "2"
    Then Fill in textvak value: "Waaruit blijkt dit" voor index: "5" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "7" op tab: "2"
    Then Fill in textvak value: "Diagnose" voor index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "13" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "14" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "15" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "16" op tab: "2"
    Then Fill in block value: "Waaruit bestaat ernstig nadeel" voor index: "7" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "17" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "18" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "19" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "20" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "21" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "22" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "8" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "23" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "24" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "25" op tab: "2"
    # Then Druk op type: "radio" met naam: "Yes" met index: "26" op tab: "2"
    Then Fill in block value: "Toelichting" voor index: "8" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Datum toevoegen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Reload pagina op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    When Druk op local action "Verzoek WMC" op tab "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op local action "Vernieuwen" op tab "2"
    Then Druk op type: "button" met naam: "Ga" met index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    # When Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    When Select option by value: "Intended conclusion remains" voor index: "0" op tab: "2"
    When Select option by value: "An adjustment is required in the client file" voor index: "1" op tab: "2"
    Then Fill in block value: "Dit is een voorbeeld voor de test" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op zaak: "WZD-VWM" link voor: "<Scenario>" op tab: "1"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Groundwork" met index: "0" op tab: "2"
    Then Select option by value: "PhysicalHandicap" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Druk op type: "checkbox" met naam: "Ander gevaar" met index: "0" op tab: "2"
    When Iframe fill in value: "Toelichting bij 'Ander gevaar'" voor index: "0" op tab: "2"
    When Iframe fill in value: "Beschrijf de diagnose en het gedrag die leiden tot ernstig nadeel" voor index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    # Then Druk op type: "radio" met naam: "No" met index: "1" op tab: "2"
    # Then Druk op type: "radio" met naam: "No" met index: "2" op tab: "2"
    When Iframe fill in value: "Beschrijf de houding ten aanzien van opname en verblijf in een accommodatie" voor index: "2" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    Then Select option by value: "6 months" voor index: "5" op tab: "2"
    When Iframe fill in value: "Toelichting Subsidiariteit, proportionaliteit en doelmatigheid" voor index: "3" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    When Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Opstellen verzoekschrift #####
    When Select option by value: "18" voor index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Select option by value: "Authorization for continued detention" voor index: "1" op tab: "2"
    When Fill in block value: "Bijzonderheden zijn voor de test" voor index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "First VWM" met index: "0" op tab: "2"
    When Fill in block value: "Aanleiding toelichting" voor index: "2" op tab: "2"
    When Zoeken en invullen value: "Aanvraag eerste VWM" voor index: "1" indexpijl: "0" op tab: "2"
    When Fill in block value: "Oordeel toelichting" voor index: "4" op tab: "2"
    When Zoeken en invullen value: "Eerste VWM" voor index: "3" indexpijl: "1" op tab: "2"
    When Iframe fill in value: "Beschrijf de houding ten aanzien van opname en verblijf in een accommodatie" voor index: "1" op tab: "2"
    Then Druk op type: "button" met naam: "Voltooien" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    When Zoeken en invullen value: "Overgeplaatst" voor index: "1" indexpijl: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "Postal" met index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "false" met index: "10" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    # Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Status geupdate naar: "Wacht op rechtbank" voor index: "0" op tab: "2"
    #### add test voor registrerenopnamen in local action should be no ####
    Then Local action menu item: "Registreren opname" is: "niet_beschikbaar" op tab: "2"
    Then Druk op local action "Vastleggen uitspraak" op tab "2"
    Given We testen scenario: "<Scenario>"
    ##### Vastleggen uitspraak #####
    When Fill in veld value: "9-12-2024" voor index: "0" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "1" op tab: "2"
    When Fill in veld value: "9-8-2024" voor index: "2" op tab: "2"
    Then Select option by value: "Not admissible" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    #### add test voor registrerenopnamen in local action should be yes ####
    Then Local action menu item: "Registreren opname" is: "beschikbaar" op tab: "2"
    When Druk op local action "Registreren opname" op tab "2"
    When Wacht op deze pagina voor "3000" miliseconden op tab: "2"
    Then Fill in veld value: "9-12-2024" voor index: "0" op tab: "2"
    Then Fill in veld value: "9-12-2025" voor index: "1" op tab: "2"
    Then Type in veld value: "Botniahuis" voor index: "2" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "2"
    Then Sla zaak met naam "WZD-VWM" voor: "<Scenario>" in filenaam: "ZSD-36468_ZSD-36495_VWM_Local_action_Registreren_opname_adviseert_het_systeem_de_einddatum.json" op tab: "2"

    Examples:
      | Scenario                                                                                   | env | bsn       | Aanvraagwijze | Aanvraagsoort | bijzondereCommunicatieVorm | relatie                     | wettelijkeRelatie |
      | ZSD-36468_ZSD-36495_VWM_Local_action_Registreren_opname_adviseert_het_systeem_de_einddatum | WLZ | 072018392 | Written       | WzdVWM        | None                       | WettelijkeVertegenwoordiger | Curator           |
