Feature: Verzoekschrift Nee en Informeren Zorgaanbieder
Dit is een feature voor het testen van de functionaliteit voor Informeren Zorgaanbieder

  Background: https://ciz.atlassian.net/browse/ZSD-32434
    # Bij het uitvoeren van WzD-beoordelen voor aanvraagsoort = WzdRM geldt dat indien Opstellen Verzoekschrift = Nee dan moeten de processen Informeren Aanvrager en Informeren Zorgaanbieder uitgevoerd kunnen worden  
    # Bij het uitvoeren van WzD-beoordelen voor aanvraagsoort = WzdIBS geldt dat indien Opstellen Verzoekschrift = Nee dan moet het proces Informeren Zorgaanbieder uitgevoerd kunnen worden inclusief velden IZ-5 en IZ-6

  @ZSD-32434_32634_VerzoekSchrift_Nee_Informeren_Zorgaanbieder_Wzd_RM
  Scenario Outline:
    Given We testen scenario: "<Scenario>"
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "26-01-2022" voor index: "2" op tab: "1"
    When Fill in veld value: "roepnaam-baby-Test" voor index: "3" op tab: "1"
    When Fill in veld value: "baby-Test" voor index: "4" op tab: "1"
    When Fill in veld value: "van den" voor index: "5" op tab: "1"
    When Fill in veld value: "Baby test" voor index: "6" op tab: "1"
    When Fill in veld value: "BT" voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "<wettelijkeRelatie>" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "7-1-2025" voor index: "1" op tab: "1"
    Then Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    Then Druk op type: "radio" met naam: "Yes" met index: "5" op tab: "1"
    Then Druk op type: "radio" met naam: "Yes" met index: "6" op tab: "1"
    Then Fill in veld value: "22-10-2023" voor index: "2" op tab: "1"
    Then Zoeken en invullen value: "Geen Art.21 traject" voor index: "5" indexpijl: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Aanvrager onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgaanbieder onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgverantwoordelijke onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Wzd-functionaris onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Tweede belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    # When Druk op zaak: "WZD-RM" link voor: "<Scenario>" sla op met filenaam: "ZSD-26769_ZSD-26780_ZSD-26781_ZSD_26792_ZSD_26803_Opstellen_Verzoekschrift.json" op tab: "1"
    When Druk op zaak: "WZD-RM" link voor: "<Scenario>" op tab: "1"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    ###### Controleren Administratieve volledigheid #######
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "5" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "1" op tab: "2"
    When Select option by value: "6 months" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "7" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "8" op tab: "2"
    Then Fill in textvak value: "Dit is een test" voor index: "1" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    ##### Vooronderzoek #####
    ##### Vooronderzoek - schermonderdeel Vastleggen medische verklaring #####
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "9" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "2" op tab: "2"
    When Select option by value: "WVGGZ" voor index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "10" op tab: "2"
    ##### Vooronderzoek - schermonderdeel Vaststellen grondslag medische verklaring #####
    Then Druk op type: "radio" met naam: "Groundwork" met index: "0" op tab: "2"
    When Select option by value: "PhysicalHandicap" voor index: "2" op tab: "2"
    ##### Vooronderzoek - schermonderdeel Checklist medische verklaring #####
    Then Druk op type: "radio" met naam: "Sir" met index: "0" op tab: "2"
    When Fill in veld value: "Ik ben de dokter" voor index: "4" op tab: "2"
    When Fill in veld value: "12345678" voor index: "5" op tab: "2"
    When Select option by value: "SO" voor index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "11" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "12" op tab: "2"
    Then Fill in textvak value: "Waaruit blijkt dit" voor index: "5" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "7" op tab: "2"
    Then Fill in textvak value: "Diagnose" voor index: "6" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "13" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "14" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "15" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "16" op tab: "2"
    Then Fill in block value: "Waaruit bestaat ernstig nadeel" voor index: "7" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "17" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "18" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "19" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "20" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "21" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "22" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "8" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "23" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "24" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "25" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "26" op tab: "2"
    Then Fill in block value: "Toelichting" voor index: "8" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Reload pagina op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziektebiografie #####
    Then Druk op type: "button" met naam: "Datum toevoegen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Reload pagina op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziekte/Aandoening #####
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    When Druk op local action "Verzoek WMC" op tab "2"
    #### Verzoek WMC ####
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op local action "Vernieuwen" op tab "2"
    Then Druk op type: "button" met naam: "Ga" met index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    When Select option by value: "Intended conclusion remains" voor index: "0" op tab: "2"
    When Select option by value: "An adjustment is required in the client file" voor index: "1" op tab: "2"
    Then Fill in block value: "Dit is een voorbeeld voor de test" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    # When Druk op zaak: "WZD-RM" link voor: "<Scenario>" sla op met filenaam: "ZSD-26769_ZSD-26780_ZSD-26781_ZSD_26792_ZSD_26803_Opstellen_Verzoekschrift_tab3.json" op tab: "1"
    When Druk op zaak: "WZD-RM" link voor: "<Scenario>" op tab: "1"
    #### WZD Beoordeling ####
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Groundwork" met index: "0" op tab: "2"
    Then Select option by value: "PhysicalHandicap" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "No" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "No" met index: "2" op tab: "2"
    When Druk op type: "checkbox" met naam: "Ander gevaar" met index: "0" op tab: "2"
    When Iframe fill in value: "Toelichting bij 'Ander gevaar'" voor index: "0" op tab: "2"
    When Iframe fill in value: "Beschrijf de diagnose en het gedrag die leiden tot ernstig nadeel" voor index: "1" op tab: "2"
    When Iframe fill in value: "Beschrijf de houding ten aanzien van opname en verblijf in een accommodatie" voor index: "2" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    Then Druk op type: "radio" met naam: "No" met index: "3" op tab: "2"
    When Iframe fill in value: "Toelichting Subsidiariteit, proportionaliteit en doelmatigheid" voor index: "3" op tab: "2"
    # When Iframe fill in value: "Toelichting Subsidiariteit, proportionaliteit en doelmatigheid" voor index: "4" op tab: "2"
    Then Druk op type: "radio" met naam: "No" met index: "4" op tab: "2"
    Then Select option by value: "FormalRequirements" voor index: "5" op tab: "2"
    When Iframe fill in value: "Toelichting Subsidiariteit, proportionaliteit en doelmatigheid" voor index: "4" op tab: "2"
    Then Select option by value: "FormalRequirements" voor index: "5" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    When Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    #### Scherm Informeren Aanvrager ####
    Then Zoeken en invullen value: "Onvoldoende informatie" voor index: "1" indexpijl: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Postal" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    #### Scherm Informeren Zorgaanbieder ####
    Then Zoeken en invullen value: "Onvoldoende informatie" voor index: "1" indexpijl: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Postal" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Voltooien" met index: "0" op tab: "2"
    Then Sla zaak met naam "WZD-RM" voor: "<Scenario>" in filenaam: "ZSD-26769_ZSD-26780_ZSD-26781_ZSD_26792_ZSD_26803_Opstellen_Verzoekschrift_tab3.json.json" op tab: "2"

    Examples:
      | Scenario | env | bsn       | klant  | geboortedatum | Aanvraagwijze | Aanvraagdatum | Aanvraagsoort | naamgebruik | burgerlijkeStaat       | leefSituatie | juridischeMaatregelen | verblijfStatus | geheimNummer | geheimNummer2 | taal  | telefonischeCommunicatie | bijzondereCommunicatieVorm | relatie                     | wettelijkeRelatie | partnerGeboorteDatum | woontOpZelfdeAdres | huisArtsClient | verzekering     | nieuwOfBestaandZorg           | zorgVraag1 | zorgVraag2 | zorgVraag3 | WZDversneld | checkboxes | stroom     | isIDVastgesteld  | orientatieStoornis  | psychischFunctioneren | motorischFunctioneren | psychoSociaalWelzijn | probleemGedrag      | verslavingsProblemen | socialeRaadZaamheid | mobiliteit          | persoonlijkeZorg    | huishoudelijkLeven  | socialeRelatiesEnMaatschappelijk | deelnameOnderwijs   | deelnameWerk        | grondslag | eersteGrondslag      | permanentToezicht | toegangWLZ | negatiefBesluit | opstarten | zorgProfielReeks | zorgProfiel | Besluitbrief | aanvragenReview | checkboxes |
      |        1 | WLZ | 695870117 | nieuwe |            10 | Written       |    25-12-2023 | WzdRM         | BirthName   | NeverMarriedNorPartner | AtParents    | None                  | Permanent      | no           | no            | Dutch | yes                      | None                       | WettelijkeVertegenwoordiger | Curator           | None                 | None               | search data    | Dutch insurance | Bestaande Wlz-zorg stopzetten | nee        | nee        | nee        | n.v.t       | nee        | Beoordelen | Ja, face to face | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld   | Nvt/Niet beoordeeld   | Nvt/Niet beoordeeld  | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld  | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld              | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | ja        | Lichamelijk handicap | ja                | ja         | nee             | nee       | GGZB             | GGZ01B      | ZB05         | nee             | ja         |

  @ZSD-32434_VerzoekSchrift_Nee_Informeren_Zorgaanbieder_Wzd_IBS
  Scenario Outline:
    Given We testen scenario: "<Scenario>"
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "26-01-2022" voor index: "2" op tab: "1"
    When Fill in veld value: "roepnaam-baby-Test" voor index: "3" op tab: "1"
    When Fill in veld value: "baby-Test" voor index: "4" op tab: "1"
    When Fill in veld value: "van den" voor index: "5" op tab: "1"
    When Fill in veld value: "Baby test" voor index: "6" op tab: "1"
    When Fill in veld value: "BT" voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "<wettelijkeRelatie>" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "7-1-2025" voor index: "1" op tab: "1"
    Then Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Aanvrager onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgaanbieder onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgverantwoordelijke onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Wzd-functionaris onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Tweede belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    # When Druk op zaak: "WZD-IBS" link voor: "<Scenario>" sla op met filenaam: "request_WLZ_New_Client_test1_WZD_IBS.json" op tab: "1"
    When Druk op zaak: "WZD-IBS" link voor: "<Scenario>" op tab: "1"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    ###### Controleren Administratieve volledigheid #######
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "1" op tab: "2"
    When Select option by value: "WVGGZ" voor index: "0" op tab: "2"
    ##### Vooronderzoek - schermonderdeel Checklist medische verklaring #####
    Then Druk op type: "radio" met naam: "Sir" met index: "0" op tab: "2"
    When Fill in veld value: "Ik ben de dokter" voor index: "2" op tab: "2"
    When Fill in veld value: "12345678" voor index: "3" op tab: "2"
    When Select option by value: "SO" voor index: "1" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziektebiografie #####
    Then Druk op type: "button" met naam: "Datum toevoegen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Reload pagina op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziekte/Aandoening #####
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Wzd beoordeling - schermonderdeel Diagnose, ernstig nadeel en reikweidte #####
    Then Druk op type: "radio" met naam: "Groundwork" met index: "0" op tab: "2"
    Then Select option by value: "PhysicalHandicap" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "No" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "No" met index: "2" op tab: "2"
    When Druk op type: "checkbox" met naam: "Ander gevaar" met index: "0" op tab: "2"
    When Iframe fill in value: "Toelichting bij 'Ander gevaar'" voor index: "0" op tab: "2"
    When Iframe fill in value: "Beschrijf de diagnose en het gedrag die leiden tot ernstig nadeel" voor index: "1" op tab: "2"
    When Iframe fill in value: "Beschrijf de houding ten aanzien van opname en verblijf in een accommodatie" voor index: "2" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    Then Druk op type: "radio" met naam: "No" met index: "5" op tab: "2"
    When Iframe fill in value: "Toelichting Subsidiariteit, proportionaliteit en doelmatigheid" voor index: "3" op tab: "2"
    # When Iframe fill in value: "Toelichting Subsidiariteit, proportionaliteit en doelmatigheid" voor index: "4" op tab: "2"
    Then Druk op type: "radio" met naam: "No" met index: "6" op tab: "2"
    Then Select option by value: "FormalRequirements" voor index: "5" op tab: "2"
    When Iframe fill in value: "Toelichting Subsidiariteit, proportionaliteit en doelmatigheid" voor index: "4" op tab: "2"
    Then Select option by value: "FormalRequirements" voor index: "5" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    When Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    #### Scherm Informeren Zorgaanbieder ####
    Then Zoeken en invullen value: "Onvoldoende informatie" voor index: "1" indexpijl: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Postal" met index: "0" op tab: "2"
    Then Fill in veld value: "Zuidplas" voor index: "2" op tab: "2"
    Then Fill in veld value: "05-12-2024" voor index: "3" op tab: "2"
    Then Druk op type: "button" met naam: "Voltooien" met index: "0" op tab: "2"
    Then Sla zaak met naam "WZD-IBS" voor: "<Scenario>" in filenaam: "request_WLZ_New_Client_test1_WZD_IBS.json" op tab: "2"

    Examples:
      | Scenario | env | bsn       | klant  | geboortedatum | Aanvraagwijze | Aanvraagdatum | Aanvraagsoort | naamgebruik | burgerlijkeStaat       | leefSituatie | juridischeMaatregelen | verblijfStatus | geheimNummer | geheimNummer2 | taal  | telefonischeCommunicatie | bijzondereCommunicatieVorm | relatie                     | wettelijkeRelatie | partnerGeboorteDatum | woontOpZelfdeAdres | huisArtsClient | verzekering     | nieuwOfBestaandZorg           | zorgVraag1 | zorgVraag2 | zorgVraag3 | WZDversneld | checkboxes | stroom     | isIDVastgesteld  | orientatieStoornis  | psychischFunctioneren | motorischFunctioneren | psychoSociaalWelzijn | probleemGedrag      | verslavingsProblemen | socialeRaadZaamheid | mobiliteit          | persoonlijkeZorg    | huishoudelijkLeven  | socialeRelatiesEnMaatschappelijk | deelnameOnderwijs   | deelnameWerk        | grondslag | eersteGrondslag      | permanentToezicht | toegangWLZ | negatiefBesluit | opstarten | zorgProfielReeks | zorgProfiel | Besluitbrief | aanvragenReview | checkboxes |
      |        1 | WLZ | 695870117 | nieuwe |            10 | Written       |    25-12-2023 | WzdIBS        | BirthName   | NeverMarriedNorPartner | AtParents    | None                  | Permanent      | no           | no            | Dutch | yes                      | None                       | WettelijkeVertegenwoordiger | Curator           | None                 | None               | search data    | Dutch insurance | Bestaande Wlz-zorg stopzetten | nee        | nee        | nee        | n.v.t       | nee        | Beoordelen | Ja, face to face | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld   | Nvt/Niet beoordeeld   | Nvt/Niet beoordeeld  | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld  | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld              | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | ja        | Lichamelijk handicap | ja                | ja         | nee             | nee       | GGZB             | GGZ01B      | ZB05         | nee             | ja         |
