Feature: WzD-IBS E2E flow met als eindstatus Wacht op rechtbank. Dit vanwege het feit dat ZSD-34796 expliciet in deze test wordt meegenomen

  Background: https://ciz.atlassian.net/browse/ZSD-26769
    # https://ciz.atlassian.net/browse/ZSD-26780
    # https://ciz.atlassian.net/browse/ZSD-26781
    # https://ciz.atlassian.net/browse/ZSD-33495
    # https://ciz.atlassian.net/browse/ZSD-34796

  @ZSD-26769_ZSD-26780_26781_33495_WzD-IBS_End2End_Status_OPGELOST_AFGEROND
  Scenario Outline:
    Given We testen scenario: "<Scenario>"
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "26-01-2022" voor index: "2" op tab: "1"
    When Fill in veld value: "roepnaam-baby-Test" voor index: "3" op tab: "1"
    When Fill in veld value: "baby-Test" voor index: "4" op tab: "1"
    When Fill in veld value: "van den" voor index: "5" op tab: "1"
    When Fill in veld value: "Baby test" voor index: "6" op tab: "1"
    When Fill in veld value: "BT" voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "Curator" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "7-1-2025" voor index: "1" op tab: "1"
    Then Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Aanvrager onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgaanbieder onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgverantwoordelijke onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Wzd-functionaris onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Tweede belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    When Druk op zaak: "WZD-IBS" link voor: "<Scenario>" op tab: "1"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    ##### Vooronderzoek - Vastleggen medische verklaring #######
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Fill in veld value: "9-12-2024" voor index: "1" op tab: "2"
    When Select option by value: "WVGGZ" voor index: "0" op tab: "2"
    ##### Vooronderzoek - schermonderdeel Checklist medische verklaring #####
    Then Druk op type: "radio" met naam: "Sir" met index: "0" op tab: "2"
    When Fill in veld value: "Ik ben de dokter" voor index: "2" op tab: "2"
    When Fill in veld value: "12345678" voor index: "3" op tab: "2"
    When Select option by value: "SO" voor index: "1" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziektebiografie #####
    Then Druk op type: "button" met naam: "Datum toevoegen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Reload pagina op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziekte/Aandoening #####
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Wzd beoordeling - schermonderdeel Diagnose, ernstig nadeel en reikweidte #####
    Then Druk op type: "radio" met naam: "Groundwork" met index: "0" op tab: "2"
    Then Select option by value: "PhysicalHandicap" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    When Druk op type: "checkbox" met naam: "Ander gevaar" met index: "0" op tab: "2"
    When Iframe fill in value: "Toelichting bij 'Ander gevaar'" voor index: "0" op tab: "2"
    When Iframe fill in value: "Beschrijf de diagnose en het gedrag die leiden tot ernstig nadeel" voor index: "1" op tab: "2"
    When Iframe fill in value: "Beschrijf de houding ten aanzien van opname en verblijf in een accommodatie" voor index: "2" op tab: "2"
    ##### Wzd beoordeling - schermonderdeel Noodzaak #####
    Then Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    Then Druk op type: "radio" met naam: "No" met index: "5" op tab: "2"
    When Iframe fill in value: "Toelichting Subsidiariteit, proportionaliteit en doelmatigheid" voor index: "3" op tab: "2"
    ##### Wzd beoordeling - schermonderdeel Conclusie, advies en ondertekening #####
    Then Druk op type: "radio" met naam: "No" met index: "6" op tab: "2"
    Then Select option by value: "FormalRequirements" voor index: "5" op tab: "2"
    When Iframe fill in value: "Toelichting Subsidiariteit, proportionaliteit en doelmatigheid" voor index: "4" op tab: "2"
    When Fill in veld value: "06-02-2025" voor index: "1" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Informeren Zorgaanbieder #####
    Then Zoeken en invullen value: "Onvoldoende informatie" voor index: "1" indexpijl: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Postal" met index: "0" op tab: "2"
    Then Fill in veld value: "Zuidplas" voor index: "2" op tab: "2"
    Then Fill in veld value: "05-12-2024" voor index: "3" op tab: "2"
    Then Druk op type: "button" met naam: "Voltooien" met index: "0" op tab: "2"
    Then Status geupdate naar: "Wacht op rechtbank" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Wachten op rechtbank #####
    # Then Druk op local action "Vastleggen uitspraak" op tab "2"
    ##### Vastleggen uitspraak #####
    # Then Druk op type: "checkbox" met naam: "" met index: "0" op tab: "2"
    # When Fill in veld value: "09-12-2024" voor index: "0" op tab: "2"
    # Then Druk op type: "radio" met naam: "Fully awarded" met index: "0" op tab: "2"
    # Then Druk op type: "radio" met naam: "Custody" met index: "0" op tab: "2"
    # Then Fill in veld value: "01-12-2024" voor index: "1" op tab: "2"
    # Then Fill in veld value: "31-12-2024" voor index: "2" op tab: "2"
    # Then Druk op type: "button" met naam: "Nieuwe geldige juridische status overschrijven" met index: "0" op tab: "2"
    # Then Select option by value: "Art 21: neither willingness nor resistance" voor index: "1" op tab: "2"
    # Then Fill in veld value: "02-02-2023" voor index: "4" op tab: "2"
    # Then Fill in veld value: "30-12-2025" voor index: "5" op tab: "2"
    # Then Druk op type: "button" met naam: "Nog een status toevoegen" met index: "0" op tab: "2"
    # Then Select option by value: "Conditional Authorization" voor index: "2" op tab: "2"
    # Then Fill in veld value: "31-12-2025" voor index: "6" op tab: "2"
    # Then Fill in veld value: "31-12-2026" voor index: "7" op tab: "2"
    # Then Druk op type: "radio" met naam: "Cassation" met index: "0" op tab: "2"
    # Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    ##### Controle op eindstatus - End2End flow #####
    # Then Status geupdate naar: "Wacht op rechtbank" voor index: "0" op tab: "2"
    #### vastleggen uitspraak
    Then Druk op local action "Vastleggen uitspraak" op tab "2"
    Then Druk op type: "checkbox" met naam: "<tijdelijkeUitspraak>" met index: "0" op tab: "2"
    When Fill in veld value: "<datumUitspraak>" voor index: "0" op tab: "2"
    Then Select option by value: "<Uitspraak>" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "<specificatieUitspraak>" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "<juridischeStatus>" met index: "0" op tab: "2"
    When Fill in veld value: "<startDatum>" voor index: "1" op tab: "2"
    When Fill in veld value: "<eindDatum>" voor index: "2" op tab: "2"
    When Fill in veld value: "<beindigdPer>" voor index: "3" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op local action "Correctie vastleggen uits..." op tab "2"
    When Select option by value: "<reden_correctiebesluit>" voor index: "0" op tab: "2"
    When Fill in block value: "Dit is een toelichting voor correctie vastleggen uitspraak" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    When Druk op sidebar optie "Bijbehorende zaken" op tab "2"
    When Druk op zaak: "WLZWZD-OM" link voor: "<Scenario>" op tab: "2"
    Then Initieer nieuwe pagina op tab: "3"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "3"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "3"
    ##### Controle op eindstatus - End2End flow #####
    Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "2"
    Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "3"
    Then Sla zaak met naam "WZD-IBS" voor: "<Scenario>" in filenaam: "request_WLZ_New_Client_test1_WZD_IBS.json" op tab: "2"

    Examples:
      | Scenario | env | bsn       | Aanvraagwijze | Aanvraagdatum | Aanvraagsoort | tijdelijkeUitspraak | datumUitspraak | Uitspraak      | specificatieUitspraak | juridischeStatus | startDatum | eindDatum | beindigdPer | reden_correctiebesluit |
      |        1 | WLZ | 695870117 | Written       |    25-12-2023 | WzdIBS        | n.v.t.              |     09-12-2024 | Not admissible | n.v.t.                | n.v.t.           | n.v.t.     | n.v.t.    | n.v.t.      | IncorrectDate          |
