Feature: Aanvraagsoort TNOV en Opstellen verzoekschrift = Ja
Dit is een feature voor het testen van de functionaliteit voor Informeren Zorgaanbieder

  Background: https://ciz.atlassian.net/browse/ZSD-32698
    # Bij het uitvoeren van WzD-beoordelen voor aanvraagsoort = TNOV geldt dat altijd het veld 'Opstellen Verzoekschrift' + keuzes Ja en Nee enabled moet worden getoond. De schermen Informeren Rechtbank en Informeren Aanvrager worden getoond   
    # Het scenario dat Opstellen verzoekschrift = Nee en Aanvraagsoort = WzdRM moet leiden tot tot schermen Informeren Aanvrager en Zorgaanbieder 
    # wordt getest in test @ZSD-32434_32634_VerzoekSchrift_Nee_Informeren_Zorgaanbieder_Wzd_RM

  @ZSD_32698_33506_WLZ_TNOV_E2E_Status_OPGELOST_AFGEROND
  Scenario Outline:
    Given We testen scenario: "<Scenario>"
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "26-01-2022" voor index: "2" op tab: "1"
    When Fill in veld value: "roepnaam-baby-Test" voor index: "3" op tab: "1"
    When Fill in veld value: "baby-Test" voor index: "4" op tab: "1"
    When Fill in veld value: "van den" voor index: "5" op tab: "1"
    When Fill in veld value: "Baby test" voor index: "6" op tab: "1"
    When Fill in veld value: "BT" voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "<wettelijkeRelatie>" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "7-1-2025" voor index: "1" op tab: "1"
    Then Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Aanvrager onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgaanbieder onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgverantwoordelijke onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Wzd-functionaris onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Tweede belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    When Druk op zaak: "WZD-TNOV" link voor: "<Scenario>" op tab: "1"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    ##### Controleren Administratieve volledigheid #######
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziektebiografie #####
    Then Druk op type: "button" met naam: "Datum toevoegen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Ziekte/Aandoening #####
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Wzd beoordeling - schermonderdeel Diagnose, ernstig nadeel en reikweidte #####
    When Zoeken en invullen value: "Afschrift van de beslissing tot opname van de zorgverantwoordelijke" voor index: "1" indexpijl: "0" op tab: "2"
    Then Druk op type: "checkbox" met naam: "Het ernstig nadeel niet langer buiten een geregistreerde accommodatie kan worden afgewend." met index: "0" op tab: "2"
    When Iframe fill in value: "Toelichting" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Opstellen Verzoekschrift #####
    When Fill in veld value: "09-12-2024" voor index: "2" op tab: "2"
    When Fill in textvak value: "Verzoekschrift" voor index: "2" op tab: "2"
    When Fill in veld value: "09-12-2024" voor index: "4" op tab: "2"
    When Fill in textvak value: "Verzoekschrift" voor index: "3" op tab: "2"
    Then Druk op type: "button" met naam: "Voltooien" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    ##### Informeren Rechtbank #####
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    ##### Informeren Aanvrager #####
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Postal" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Status geupdate naar: "Wacht op rechtbank" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Sla zaak met naam "WLZ-TNOV" voor: "<Scenario>" in filenaam: "ZSD_32698_WLZ_TNOV_Informeren_Rechtbank.json" op tab: "2"
    ##### Wachten op rechtbank #####
    Then Druk op local action "Vastleggen uitspraak" op tab "2"
    ##### Vastleggen uitspraak #####
    When Fill in veld value: "09-12-2024" voor index: "0" op tab: "2"
    Then Select option by value: "Not admissible" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Given We testen scenario: "<Scenario>"
    ##### Controle op eindstatus - End2End flow #####
    Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "2"
    Then Sla zaak met naam "WZD-TNOV" voor: "<Scenario>" in filenaam: "request_WLZ_New_Client_test1_WZD_TNOV.json" op tab: "2"

    Examples:
      | Scenario | env | bsn       | klant  | geboortedatum | Aanvraagwijze | Aanvraagdatum | Aanvraagsoort | naamgebruik | burgerlijkeStaat       | leefSituatie | juridischeMaatregelen | verblijfStatus | geheimNummer | geheimNummer2 | taal  | telefonischeCommunicatie | bijzondereCommunicatieVorm | relatie                     | wettelijkeRelatie | partnerGeboorteDatum | woontOpZelfdeAdres | huisArtsClient | verzekering     | nieuwOfBestaandZorg           | zorgVraag1 | zorgVraag2 | zorgVraag3 | WZDversneld | checkboxes | stroom     | isIDVastgesteld  | orientatieStoornis  | psychischFunctioneren | motorischFunctioneren | psychoSociaalWelzijn | probleemGedrag      | verslavingsProblemen | socialeRaadZaamheid | mobiliteit          | persoonlijkeZorg    | huishoudelijkLeven  | socialeRelatiesEnMaatschappelijk | deelnameOnderwijs   | deelnameWerk        | grondslag | eersteGrondslag      | permanentToezicht | toegangWLZ | negatiefBesluit | opstarten | zorgProfielReeks | zorgProfiel | Besluitbrief | aanvragenReview | checkboxes |
      |        1 | WLZ | 695870117 | nieuwe |            10 | Written       |    25-12-2023 | WzdTNOV       | BirthName   | NeverMarriedNorPartner | AtParents    | None                  | Permanent      | no           | no            | Dutch | yes                      | None                       | WettelijkeVertegenwoordiger | Curator           | None                 | None               | search data    | Dutch insurance | Bestaande Wlz-zorg stopzetten | nee        | nee        | nee        | n.v.t       | nee        | Beoordelen | Ja, face to face | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld   | Nvt/Niet beoordeeld   | Nvt/Niet beoordeeld  | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld  | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld              | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | ja        | Lichamelijk handicap | ja                | ja         | nee             | nee       | GGZB             | GGZ01B      | ZB05         | nee             | ja         |

  @ZSD_32698_33506_WLZ_TNOV_E2E_Status_OPGELOST_VERVALLEN
  Scenario Outline:
    Given We testen scenario: "<Scenario>"
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "26-01-2022" voor index: "2" op tab: "1"
    When Fill in veld value: "roepnaam-baby-Test" voor index: "3" op tab: "1"
    When Fill in veld value: "baby-Test" voor index: "4" op tab: "1"
    When Fill in veld value: "van den" voor index: "5" op tab: "1"
    When Fill in veld value: "Baby test" voor index: "6" op tab: "1"
    When Fill in veld value: "BT" voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "<wettelijkeRelatie>" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "7-1-2025" voor index: "1" op tab: "1"
    Then Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Aanvrager onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgaanbieder onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgverantwoordelijke onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Wzd-functionaris onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Tweede belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    When Druk op zaak: "WZD-TNOV" link voor: "<Scenario>" op tab: "1"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    Then Druk op local action "Vervallen" op tab "2"
    ##### Scherm Vervallen #####
    When Select option by value: "Foutief ingevoerde aanvraag" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op local action "Wachten op statuswijziging" op tab "2"
    ##### Controle op eindstatus - End2End flow #####
    Then Status geupdate naar: "Opgelost - Vervallen" voor index: "0" op tab: "2"
    Then Sla zaak met naam "WZD-TNOV" voor: "<Scenario>" in filenaam: "request_WLZ_New_Client_test1_WZD_TNOV.json" op tab: "2"

    Examples:
      | Scenario | env | bsn       | klant  | geboortedatum | Aanvraagwijze | Aanvraagdatum | Aanvraagsoort | naamgebruik | burgerlijkeStaat       | leefSituatie | juridischeMaatregelen | verblijfStatus | geheimNummer | geheimNummer2 | taal  | telefonischeCommunicatie | bijzondereCommunicatieVorm | relatie                     | wettelijkeRelatie | partnerGeboorteDatum | woontOpZelfdeAdres | huisArtsClient | verzekering     | nieuwOfBestaandZorg           | zorgVraag1 | zorgVraag2 | zorgVraag3 | WZDversneld | checkboxes | stroom     | isIDVastgesteld  | orientatieStoornis  | psychischFunctioneren | motorischFunctioneren | psychoSociaalWelzijn | probleemGedrag      | verslavingsProblemen | socialeRaadZaamheid | mobiliteit          | persoonlijkeZorg    | huishoudelijkLeven  | socialeRelatiesEnMaatschappelijk | deelnameOnderwijs   | deelnameWerk        | grondslag | eersteGrondslag      | permanentToezicht | toegangWLZ | negatiefBesluit | opstarten | zorgProfielReeks | zorgProfiel | Besluitbrief | aanvragenReview | checkboxes |
      |        1 | WLZ | 695870117 | nieuwe |            10 | Written       |    25-12-2023 | WzdTNOV       | BirthName   | NeverMarriedNorPartner | AtParents    | None                  | Permanent      | no           | no            | Dutch | yes                      | None                       | WettelijkeVertegenwoordiger | Curator           | None                 | None               | search data    | Dutch insurance | Bestaande Wlz-zorg stopzetten | nee        | nee        | nee        | n.v.t       | nee        | Beoordelen | Ja, face to face | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld   | Nvt/Niet beoordeeld   | Nvt/Niet beoordeeld  | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld  | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld              | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | ja        | Lichamelijk handicap | ja                | ja         | nee             | nee       | GGZB             | GGZ01B      | ZB05         | nee             | ja         |

  @ZSD_32698_33506_WLZ_TNOV_E2E_Status_OPGELOST_AFGEBROKEN
  Scenario Outline:
    Given We testen scenario: "<Scenario>"
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "26-01-2022" voor index: "2" op tab: "1"
    When Fill in veld value: "roepnaam-baby-Test" voor index: "3" op tab: "1"
    When Fill in veld value: "baby-Test" voor index: "4" op tab: "1"
    When Fill in veld value: "van den" voor index: "5" op tab: "1"
    When Fill in veld value: "Baby test" voor index: "6" op tab: "1"
    When Fill in veld value: "BT" voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "<wettelijkeRelatie>" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "7-1-2025" voor index: "1" op tab: "1"
    Then Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Aanvrager onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgaanbieder onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgverantwoordelijke onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Wzd-functionaris onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Tweede belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    When Druk op zaak: "WZD-TNOV" link voor: "<Scenario>" op tab: "1"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "2"
    Then Nieuwe sessie starten op tab: "2"
    Then Druk op local action "Afbreken" op tab "2"
    When Select option by value: "Foutief ingevoerde aanvraag" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op local action "Wachten op statuswijziging" op tab "2"
    ##### Controle op eindstatus - End2End flow #####
    Then Status geupdate naar: "Opgelost - Afgebroken" voor index: "0" op tab: "2"
    Then Sla zaak met naam "WZD-TNOV" voor: "<Scenario>" in filenaam: "request_WLZ_New_Client_test1_WZD_TNOV.json" op tab: "2"

    Examples:
      | Scenario | env | bsn       | klant  | geboortedatum | Aanvraagwijze | Aanvraagdatum | Aanvraagsoort | naamgebruik | burgerlijkeStaat       | leefSituatie | juridischeMaatregelen | verblijfStatus | geheimNummer | geheimNummer2 | taal  | telefonischeCommunicatie | bijzondereCommunicatieVorm | relatie                     | wettelijkeRelatie | partnerGeboorteDatum | woontOpZelfdeAdres | huisArtsClient | verzekering     | nieuwOfBestaandZorg           | zorgVraag1 | zorgVraag2 | zorgVraag3 | WZDversneld | checkboxes | stroom     | isIDVastgesteld  | orientatieStoornis  | psychischFunctioneren | motorischFunctioneren | psychoSociaalWelzijn | probleemGedrag      | verslavingsProblemen | socialeRaadZaamheid | mobiliteit          | persoonlijkeZorg    | huishoudelijkLeven  | socialeRelatiesEnMaatschappelijk | deelnameOnderwijs   | deelnameWerk        | grondslag | eersteGrondslag      | permanentToezicht | toegangWLZ | negatiefBesluit | opstarten | zorgProfielReeks | zorgProfiel | Besluitbrief | aanvragenReview | checkboxes |
      |        1 | WLZ | 695870117 | nieuwe |            10 | Written       |    25-12-2023 | WzdTNOV       | BirthName   | NeverMarriedNorPartner | AtParents    | None                  | Permanent      | no           | no            | Dutch | yes                      | None                       | WettelijkeVertegenwoordiger | Curator           | None                 | None               | search data    | Dutch insurance | Bestaande Wlz-zorg stopzetten | nee        | nee        | nee        | n.v.t       | nee        | Beoordelen | Ja, face to face | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld   | Nvt/Niet beoordeeld   | Nvt/Niet beoordeeld  | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld  | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld              | Nvt/Niet beoordeeld | Nvt/Niet beoordeeld | ja        | Lichamelijk handicap | ja                | ja         | nee             | nee       | GGZB             | GGZ01B      | ZB05         | nee             | ja         |
