Feature: Create client in WLZ application
  as a user
  I want to be able to create a new client in the WLZ application
  so i can complete the registration

  @ZSD_33517_WZD_WFZ
  Scenario Outline: Register and validate a new client in WLZ application
    Given We testen scenario: "<Scenario>"
    Given Go to AppFactoryApp app page
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "0"
    When Druk op app: "Aanvraag" met index: "1" op tab: "0"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "1"
    Then Navigeer naar "<env>" omgeving op tab: "1"
    When Fill in veld value: "<bsn>" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Zoek cliënt" met index: "9999" op tab: "1"
    When Druk op type: "checkbox" met naam: "Aanvraag creëren met een nieuwe cliënt" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Persoonlijk######
    When Fill in veld value: "03-09-2010" voor index: "2" op tab: "1"
    When Fill in veld value: "Testr" voor index: "3" op tab: "1"
    When Fill in veld value: "Testr" voor index: "4" op tab: "1"
    When Fill in veld value: "Testr" voor index: "5" op tab: "1"
    When Fill in veld value: "van de" voor index: "6" op tab: "1"
    When Fill in veld value: "Ter" voor index: "7" op tab: "1"
    When Select option by value: "M" voor index: "0" op tab: "1"
    When Select option by value: "BirthName" voor index: "1" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Aanvullend persoonlijk######
    When Select option by value: "NeverMarriedNorPartner" voor index: "0" op tab: "1"
    When Select option by value: "AtParents" voor index: "1" op tab: "1"
    When Select option by value: "Guardianship" voor index: "2" op tab: "1"
    When Select option by value: "Permanent" voor index: "3" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    ######Stap Registratie - scherm Contact######
    When Fill in veld value: "thisismymail@mailme.com" voor index: "3" op tab: "1"
    When Select option by value: "Dutch" voor index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Relatie toevoegen" met index: "9999" op tab: "1"
    When Druk op type: "label" met naam: "<wettelijkeRelatie>" met index: "0" op tab: "1"
    When Fill in veld value: "Mama" voor index: "2" op tab: "1"
    When Fill in veld value: "Van der" voor index: "3" op tab: "1"
    When Fill in veld value: "MA" voor index: "4" op tab: "1"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "2" op tab: "1"
    When Fill in veld value: "9" voor index: "3" op tab: "1"
    When Fill in veld value: "4671DS" voor index: "10" op tab: "1"
    When Fill in veld value: "9" voor index: "11" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    # Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Select option by value: "<Aanvraagwijze>" voor index: "0" op tab: "1"
    Then Fill in veld value: "7-1-2025" voor index: "1" op tab: "1"
    Then Select option by value: "<Aanvraagsoort>" voor index: "1" op tab: "1"
    Then Select option by value: "2 weeks" voor index: "2" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Aanvrager onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgaanbieder onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Zorgverantwoordelijke onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Wzd-functionaris onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "checkbox" met naam: "Tweede belanghebbende onbekend" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "1"
    Then Druk op type: "button" met naam: "Aanmaken" met index: "0" op tab: "1"
    When Druk op local action "Vernieuwen" op tab "1"
    Then Druk op sidebar optie "Bijbehorende zaken" op tab "1"
    When Druk op zaak: "WZD-WFZ" link voor: "<Scenario>" op tab: "1"
    When Log in op pagina, met user: "test.automationWLZ@ciz.nl" en wachtwoord: "Rules@123!" op tab: "2"
    #### vooronderzoek
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Fill in veld value: "Pakketje" voor index: "4" op tab: "2"
    Then Fill in veld value: "7-1-2025" voor index: "2" op tab: "2"
    Then Fill in veld value: "7-9-2025" voor index: "3" op tab: "2"
    Then Fill in veld value: "Kenmerk" voor index: "1" op tab: "2"
    Then Select option by value: "9" voor index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Select option by value: "Living at home" voor index: "1" op tab: "2"
    Then Fill in veld value: "01-01-2025" voor index: "7" op tab: "2"
    Then Druk op type: "radio" met naam: "Sir" met index: "0" op tab: "2"
    Then Fill in veld value: "Benny" voor index: "8" op tab: "2"
    Then Fill in veld value: "6688" voor index: "9" op tab: "2"
    Then Select option by value: "SO" voor index: "2" op tab: "2"
    Then Druk op type: "radio" met naam: "No" met index: "1" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    ### WMC verzoek ###
    When Druk op local action "Verzoek WMC" op tab "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "1" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "2" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "3" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "4" op tab: "2"
    When Druk op type: "radio" met naam: "Yes" met index: "5" op tab: "2"
    When Select option by value: "Intended conclusion remains" voor index: "0" op tab: "2"
    When Select option by value: "An adjustment is required in the client file" voor index: "1" op tab: "2"
    Then Fill in block value: "Dit is een voorbeeld voor de test" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Wacht op deze pagina voor "60000" miliseconden op tab: "2"
    When Druk op zaak: "WZD-WFZ" link voor: "<Scenario>" op tab: "1"
    # Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    # Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Doorgaan" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    Then Druk op type: "radio" met naam: "Public Prosecutor" met index: "0" op tab: "2"
    When Select option by value: "Amsterdam" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Voltooien" met index: "0" op tab: "2"
    Given Status geupdate naar: "Wacht op OM" voor index: "0" op tab: "2"
    Then Sla zaak met naam "WZD-WFZ" voor: "<Scenario>" in filenaam: "request_WZD_New_Client_WFZ_OM.json" op tab: "2"
        ## zaak opzoek
    Then Navigeer naar "startpagina" omgeving op tab: "2"
    Then Selecteer werkwachtrij: "Wachten op OM" op tab: "2"
    Then Druk op type: "aria label" met naam: "ID Actions" met index: "1" op tab: "2"
    Then Druk op type: "Menu item" met naam: "Filter toepassen" met index: "0" op tab: "2"
    Then In "inactieve zaken" zoek zaak op index: "2" op tab: "2"
    # Then Druk op type: "button" met naam: "Ga" met index: "1" op tab: "2"
    # Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "2"
    When Druk op local action "Vastleggen reactie OM" op tab "2"
    Then Druk op type: "radio" met naam: "Yes" met index: "0" op tab: "2"
    Then Fill in veld value: "7-9-2025" voor index: "0" op tab: "2"
    # When Select option by value: "13" voor index: "0" op tab: "2"
    # When Select option by value: "10" voor index: "1" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Status geupdate naar: "Wacht op rechtbank" voor index: "0" op tab: "2"
    #### vastleggen uitspraak
    Then Druk op local action "Vastleggen uitspraak" op tab "2"
    When Fill in veld value: "09-12-2024" voor index: "0" op tab: "2"
    Then Select option by value: "Not admissible" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "2"
    Given We testen scenario: "<Scenario>"
    When Druk op local action "Correctie vastleggen uits..." op tab "2"
    When Select option by value: "<reden_correctiebesluit>" voor index: "0" op tab: "2"
    When Fill in block value: "Dit is een toelichting voor correctie vastleggen uitspraak" voor index: "0" op tab: "2"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "2"
    Then Sla zaak met naam "WZD-WFZ" voor: "<Scenario>" in filenaam: "request_WZD_New_Client_WFZ_OM.json" op tab: "2"
    When Gerelateerde Dossiers: "WLZWZD-OM" voor index: "0" op tab: "2"
    # Then Initieer nieuwe pagina op tab: "3"
    Then Druk op type: "button" met naam: "Ga" met index: "0" op tab: "3"
    Then Druk op type: "button" met naam: "Indienen" met index: "0" op tab: "3"
    ##### Controle op eindstatus - End2End flow #####
    Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "2"
    # Then Status geupdate naar: "Opgelost - Afgerond" voor index: "0" op tab: "3"

    Examples:
      | Scenario                      | env | bsn       | klant  | geheimPersoon | speciaalOnderzoek | geboortedatum | reden_correctiebesluit | wettelijkeRelatie | Aanvraagsoort | Aanvraagdatum | Aanvraagwijze |
      | request_WZD_New_Client_WFZ_OM | WLZ | 459441929 | nieuwe | no            | no                |            10 | IncorrectDate          | Curator           | WzdWFZ        |    12-10-2023 | Written       |
