export enum TestData {
    svbNumber = '23452345125',
    telNumber1 = '0645822367',
    telNumber2 = '0646723367',
    contactPerson = 'TB Tester',
    secretPersonReason = 'Anoniem blijven',
    endDateSecretPerson = '12-07-2027',
    voorvoegsel = 'van der',
    voornamen = 'Barbera',
    callSign = 'de kleine tester',
    firstName = 'Barbera',
    ininitials = 'B',
    genderM = 'M',
    genderF = 'F',
    partnerLastName = 'Oppenheimer',
    partnerPrefix = 'BSA',
    email = 'thisismymail@mailme.com',
    countryCodeNL = '31',
    countryCodeSR = '597',
    countryCodeTur = '90',
    countryCodeMar = '212',
    birthName = 'Barbera',
    countryNL = 'NLD',
    LandNL = 'Nederland',
    relationshipPostcode = '4671 DS',
    relationshipHouseNumber = '9',
    relationshipHouseLetter = '',
    RelationshipAdditionOfHouseNumber = '',
    RelationshipFillInHouseNumberIndication= 'Opposite',
    explanation ='this is my explanation why i fill in this info for explanation',
    postCode = '3081GN',
    houseNumber = '191',
    houseLetter = 'c',
    additionOfHouseNumber ='',
    houseNumberIndication = 'At',
    room = 'My room',
    straatNaam = 'Verdwaalstraat',
    plaats = 'Paramaribo',
    GP = 'dhr. Bartyers',
    namePractice = 'maanlandpraktijk',
    voorletters = 'E.E.L',
    realtie = 'ouder/verzorger',
    huisnummeraanduiding1 ='At',
    huisnummeraanduiding2 = 'Tegenover',
    Bereikbaarheid = 'Beneath the stars, whispers dance in the night, telling secrets to the moon '+ 
    "In a garden of dreams, butterflies paint the sky with their delicate wings" + 
    "Lost in the melody, time surrenders to the rhythm of a heart's song.", 
    gerichtOpBejegening = 'Gericht op bejegening',
    gerichtOpDeInformatieverstrekking = "Gericht op de informatieverstrekking",
    gerichtOpDeskundigheidVanDeMedewerker = 'Gericht op deskundigheid van de medewerker',
    gerichtOpBereikbaarheid = 'Gericht op bereikbaarheid',
    gerichtOpDoorlooptijd = 'Gericht op doorlooptijd',
    WzdArtikel21 = 'Wzd Artikel 21',
    datalek = 'Datalek',
    anders = 'Anders',
    BetreffendeWzd = 'Betreffende Wzd',
    TelefonischContact = 'Telefonisch contact',
    gegevensKlacht_soortKlacht_OmschrijvingVanDeKlachtEnGewensteOplossing ="De klant heeft een klacht ingediend over de recent gekochte elektronische apparatuur. Volgens de klant vertoont het apparaat een storing waarbij het onverwacht uitvalt na enkele minuten gebruik. De klant heeft de gebruikershandleiding nauwkeurig gevolgd en heeft ook geprobeerd het probleem op te lossen door het apparaat opnieuw op te starten, maar zonder succes. De klant zoekt assistentie om het probleem te verhelpen of om het apparaat te vervangen door een correct werkend exemplaar.",
    stoornis = 'Yes',
    toelichting = 'Dit is een toelichting',
    eindDatum = '01-12-2028',
    toelichtingBijZorgvraag = 'Dit is een toelichting bij de zorgvraag',
    beschikbaarheidHoorzitting = 'Beschikbaarheid voor (hoor)zitting is volgende maand',
    optioneleAanvulling = 'Box is beschikbaar voor optionele aanvulling of opmerkingen.',
}

export enum waitTime{
    time = 5000
}